### PR TITLE
API, Core: Use Google findbugs dependency but as compileonly

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
fixes https://github.com/apache/iceberg/issues/6966

This undoes the change I did here: https://github.com/apache/iceberg/pull/6815 so that we don't have any compile warnings and don't rely on the deprecated findbugs dependency. This change also updates other areas in the code to use the google findbugs dependency. This is a follow up from the last community sync.

cc: @rdblue @nastra @jackye1995

### CODE REVIEW

**Comment by jackye1995** [comment]
@nastra @rdblue could you take a quick look?

**Review by jackye1995 — APPROVED** [review]

**Review by ajantha-bhat — APPROVED** [review]
LGTM. 

Also verified that [this complier warning ](https://github.com/apache/iceberg/pull/6815#issuecomment-1434587642) is fixed with this change.

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by jackye1995** [comment]
Given the fact that this is blocking 1.2 release, and we already had consensus in the community sync, I will go ahead to merge this PR. Thanks for the review @nastra and @ajantha-bhat !

**Pull request merged**
