### PR TITLE
Flink: Port #7171 to flink 1.17

### PR DESCRIPTION
**Pull request by ConeyLiu**
This ports #7171 to Flink 1.17.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
@stevenzwu please take a look when you are free. Thanks a lot.

**Comment by stevenzwu** [comment]
@ConeyLiu I assume you verified the diff doesn't contain anything related to the backport

```
git diff --no-index  flink/v1.15/flink/src/ flink/v1.17/flink/src
git diff --no-index  flink/v1.16/flink/src/ flink/v1.17/flink/src
```

**Comment by ConeyLiu** [comment]
Just verified this `git diff --no-index  flink/v1.16/flink/src/ flink/v1.17/flink/src` and there doesn't contain.

**Review by stevenzwu — APPROVED** [review]

**Comment by stevenzwu** [comment]
thanks @ConeyLiu for the backport

**Comment by ConeyLiu** [comment]
Thanks @stevenzwu

**Pull request merged**
