### PR TITLE
Docs: Enhance Spark pages

### PR DESCRIPTION
**Pull request by manuzhang**
1. Fix internal links
2. Move `Type Compatibility` section from spark-writes.md to spark-getting-started.md

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by nastra** [comment]
@manuzhang have you verified that all links works by locally running the site as described [here](https://github.com/apache/iceberg/blob/main/site/README.md)?

**Comment by bitsondatadev** [comment]
### Oops

Apologies, as I asked this and accidentally made a review instead of posted a comment. I generally don't dislike GH's UI but that one has bitten me quite a few times. I digress...

### Original / Updated note

@manuzhang @nastra did you test the links locally? _I realized after I asked this we haven't set up the `nightly` build yet, which would enable testing the current changes in `docs` and we can also run a link validator on that live build each day._

That said, I'm pretty sure this will break the links if we don't revert the link changes in the next build as it works on the site now, and did the day before when I originally posted this.

https://iceberg.apache.org/docs/latest/spark-configuration/#catalogs

Links are a [bit strange at the moment](https://github.com/apache/iceberg/tree/main/site#how-links-work-in-this-project) so depending on if you're in a subproject or top-level site, it will change how you format links. Also the number of directories between versioned mkdocs projects and the top level site change from static code to build. Static code analysis that is common practice in mkdocs will fail, hence all the warnings when you build. We knew this wasn't perfect going into it, but we just needed to get this out incrementally and will be slowly addressing this.

So moving forward, I will create a PR to build locally so that any time we update docs, you will have an option to validate those changes in a local site, especially links, and I'll update the readme there.

I'll also work on another PR to add nightly builds that will run a link check on the live site after each nightly build and generate a report, while still hosting the nightly build.

@nastra, could you please revert just the links in this change and keep the content changes? Or if it's better, do the full revert and reapply only the content changes.

Thanks!

**Comment by manuzhang** [comment]
@bitsondatadev @nastra 
There is already https://github.com/apache/iceberg/pull/9939 reverting some of the links.
I can submit another PR fixing other link changes in the following PRs
#9819
#9919 
#9920

**Comment by nastra** [comment]
Can we just have one single PR to fix all the broken links for the current version of the docs (`main`)? We would then also have to fix broken links for 1.4.0 / 1.4.1 / 1.4.2 / 1.4.3 / 1.5.0 as those doc versions have the same broken links.

**Comment by manuzhang** [comment]
Yes, after merging in #9943 and #9939, I will submit a fix

**Comment by nastra** [comment]
I don't think we want to merge #9939 because it only fixes some links.

**Comment by manuzhang** [comment]
@Fokko is fixing it in https://github.com/apache/iceberg/pull/9965

**Pull request merged**
