### PR TITLE
Nessie: Upgrade nessie dependencies to 0.50.0

### PR DESCRIPTION
**Pull request by dimas-b**
This version bump includes two Nessie releases:

https://github.com/projectnessie/nessie/releases/tag/nessie-0.50.0

https://github.com/projectnessie/nessie/releases/tag/nessie-0.49.0

### CODE REVIEW

**Comment by dimas-b** [comment]
cc: @snazy @ajantha-bhat

**Comment by dimas-b** [comment]
Hmmm... `TestNessieTable` passed locally, but failed in CI :thinking: I'll investigate next week.

**Comment by dimas-b** [comment]
CI is broken because of https://github.com/projectnessie/nessie/issues/6156

**Review by ajantha-bhat — APPROVED** [review]
LGTM.

nit: we can add release notes link in the PR description.

**Review by snazy — APPROVED** [review]

**Comment by snazy** [comment]
@Fokko could you merge this one?

**Comment by dimas-b** [comment]
Rebased

**Review by Fokko — APPROVED** [review]
Will merge after a green CI

**Comment by Fokko** [comment]
Thanks @dimas-b for the PR, and fixing the issue in 0.49. @ajantha-bhat and @snazy for the review!

**Comment by dimas-b** [comment]
Thanks, @Fokko !

**Pull request merged**
