### PR TITLE
Core: Support aggregated basic stats in partition summary

### PR DESCRIPTION
**Pull request by deniskuzZ**
ref: https://github.com/apache/hive/pull/5498

### CODE REVIEW

**Comment by pvary** [comment]
@deniskuzZ: Could you please provide a short description what data is stored in the summary and in what format?

I think it is important to understand the cost for keeping this stat up-to-date. How costly is to calculate it, and what is the data size increase caused by this change.

@findepi: Could this be useful for Trino? Does Trino have some optimiyation like this?

**Comment by deniskuzZ** [comment]
Found partition stats tracker issue https://github.com/apache/iceberg/issues/8450 with the following design doc: https://docs.google.com/document/d/1vaufuD47kMijz97LxM67X8OX-W2Wq7nmlz3jRo8J5Qk
But it doesn't seem to be completed yet: https://github.com/apache/iceberg/pull/11216

**Comment by ajantha-bhat** [comment]
Yes, it is still active. But it is not getting enough reviews. 
I am facing very hard to get reviews. 

https://github.com/apache/iceberg/pull/11216 is the last PR that is needed for the functionality to work.

**Comment by ajantha-bhat** [comment]
@deniskuzZ: Could you please comment on my last PR that this feature will be helpful for Hive? and you are looking for it. 
It might help get more attention for review.

**Comment by jbonofre** [comment]
Should we reopen this PR or is it superseded by another one ?

**Pull request closed without merging**
