### PR TITLE
Core: Use HEAD request to check if view exists

### PR DESCRIPTION
**Pull request by nastra**

### CODE REVIEW

**Comment by nastra** [comment]
@Fokko since you reviewed https://github.com/apache/iceberg/pull/10999 already, could you review this one please?

**Review by Fokko — APPROVED** [review]
Looks good to me, thanks for adding this @nastra 

Spec ref: https://github.com/apache/iceberg/blob/6c05f35e67093491aa054d0b41b1ada367df1072/open-api/rest-catalog-open-api.yaml#L1691

**Review by ebyhr — APPROVED** [review]

**Review by amogh-jahagirdar — COMMENTED** [review]
Could we add a test to `TestRESTCatalog` that makes sure the client is issuing a head request when checking if a view exists? Other than that the changes themselves look good to me

**Comment by nastra** [comment]
@amogh-jahagirdar good point, I've added a test to `TestRESTViewCatalog` as that's the more appropriate place to check this (instead of `TestRESTCatalog`)

**Review by amogh-jahagirdar — APPROVED** [review]
Awesome, thanks for fixing this @nastra , thanks @Fokko @ebyhr for reviewing!

**Pull request merged**
