### PR TITLE
Spark 3.5: Fix flaky TestSparkExecutorCache

### LINKED ISSUE #9511: Flaky test: TestSparkExecutorCache > testMergeOnReadDelete()
build: https://github.com/apache/iceberg/actions/runs/7569167293/job/20611887361
PR: https://github.com/apache/iceberg/pull/9507

position deletes are missing? cache? 

```
TestSparkExecutorCache > testMergeOnReadDelete() > catalogName = testhive, implementation = org.apache.iceberg.spark.SparkCatalog, config = {type=hive, io-impl=org.apache.iceberg.spark.TestSparkExecutorCache$CustomFileIO, default-namespace=default} FAILED
    java.lang.AssertionError: 
    Expecting all elements of:
      [GenericDeleteFile{content=position_deletes, file_path=/tmp/junit17911827767769921495/pos-deletes-da2fc9e8-2fc7-42ad-901b-9139ee8102b0, file_format=PARQUET, spec_id=0, partition=PartitionData{}, record_count=2, file_size_in_bytes=1267, column_sizes={2147483546=145, 2147483545=69}, value_counts=null, null_value_counts=null, nan_value_counts=null, lower_bounds=null, upper_bounds=null, key_metadata=null, split_offsets=[4], equality_ids=null, sort_order_id=null, data_sequence_number=null, file_sequence_number=null},
        GenericDeleteFile{content=equality_deletes, file_path=/tmp/junit17911827767769921495/eq-deletes-15c2d19c-c3dd-4b17-95cc-7e68759550f0, file_format=PARQUET, spec_id=0, partition=PartitionData{}, record_count=2, file_size_in_bytes=448, column_sizes={1=46}, value_counts={1=2}, null_value_counts={1=0}, nan_value_counts={}, lower_bounds=org.apache.iceberg.SerializableByteBufferMap@e1782, upper_bounds=org.apache.iceberg.SerializableByteBufferMap@e1787, key_metadata=null, split_offsets=[4], equality_ids=[1], sort_order_id=0, data_sequence_number=null, file_sequence_number=null}]
    to match given predicate but this element did not:
      GenericDeleteFile{content=equality_deletes, file_path=/tmp/junit17911827767769921495/eq-deletes-15c2d19c-c3dd-4b17-95cc-7e68759550f0, file_format=PARQUET, spec_id=0, partition=PartitionData{}, record_count=2, file_size_in_bytes=448, column_sizes={1=46}, value_counts={1=2}, null_value_counts={1=0}, nan_value_counts={}, lower_bounds=org.apache.iceberg.SerializableByteBufferMap@e1782, upper_bounds=org.apache.iceberg.SerializableByteBufferMap@e1787, key_metadata=null, split_offsets=[4], equality_ids=[1], sort_order_id=0, data_sequence_number=null, file_sequence_number=null}
        at org.apache.iceberg.spark.TestSparkExecutorCache.checkDelete(TestSparkExecutorCache.java:268)
        at org.apache.iceberg.spark.TestSparkExecutorCache.testMergeOnReadDelete(TestSparkExecutorCache.java:254)
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has 
```

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds code to destroy all currently live table broadcasts after initialization to fix #9511.

Our tests have the following behavior:

```
Append
Append
Execute a row-level operation
``` 

The cleanup logic for each of the appends may trigger invalidation in delete, potentially making all requests go to the underlying storage and skipping the cache.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
I am going to run this a number of times to make sure the new logic is not flaky and then will test it one more time on a cluster.

**Comment by aokolnychyi** [comment]
Re-triggering one more time.

**Comment by aokolnychyi** [comment]
@amogh-jahagirdar @szehon-ho @nastra, could you check this one? I had 5 successful CI runs.

**Comment by szehon-ho** [comment]
Sorry i admit i am not following, can you explain the issue more clearly what randomly fails?  

Each operation should invalidate its table's delete files afterwards, or is it not supposed to because of Spark caching catalog?  Not sure how clearing all cache ahead of the test helps?

**Comment by aokolnychyi** [comment]
> Each operation should invalidate its table's delete files afterwards, or is it not supposed to because of Spark caching catalog? Not sure how clearing all cache ahead of the test helps?

The problem is that the cleanup happens once the table broadcast is garbage collected, which we can't control. We know it happens sometime after the job is done. However, there may be a delay and the following job can start running in the meantime.

**Comment by szehon-ho** [comment]
Got it, is another fix just to make it different table name?  Seems table.close() will only clear files of its own name.  That being said, this looks fine to me.

**Review by szehon-ho — APPROVED** [review]

**Review by amogh-jahagirdar — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
Thanks @aokolnychyi for fixing this, and @szehon-ho for the review. I'll go ahead and merge this.

**Pull request merged**
