### PR TITLE
Core: Drop unused MERGE cardinality check table properties

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR removes no longer used MERGE cardinality check table properties.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@ajantha-bhat @Fokko @rdblue @danielcweeks @amogh-jahagirdar @RussellSpitzer @flyrain

**Comment by Fokko** [comment]
@aokolnychyi can you run:

```sh
./gradlew revapiAcceptAllBreaks --justification "Spark 3.1 has been dropped"
```

**Review by Fokko — APPROVED** [review]

**Review by singhpk234 — APPROVED** [review]

**Comment by aokolnychyi** [comment]
All api + core tests and checks passed, some engine CI jobs are still running but the table properties are not used there. I am going to merge this one to proceed with a release candidate.

**Comment by aokolnychyi** [comment]
Thanks, @Fokko @singhpk234!

**Pull request merged**
