### PR TITLE
Upgrade to Gradle 8.9

### LINKED ISSUE #10685: Upgrade to Gradle 8.9
### Feature Request / Improvement

Gradle 8.9 has just been released including the fix on old MacOS versions (see https://github.com/gradle/gradle/issues/29476).

See https://docs.gradle.org/8.9/release-notes.html for complete changelog.

### Query engine

None

### PR DESCRIPTION
**Pull request by jbonofre**
This closes #10685

### CODE REVIEW

**Comment by jbonofre** [comment]
This PR closes #10686

**Comment by jbonofre** [comment]
@Fokko @nastra thanks in advance gentlemen ! 😄

**Review by nastra — APPROVED** [review]

**Review by ajantha-bhat — APPROVED** [review]

**Review by Fokko — APPROVED** [review]
Just before the finish line, thank you @jbonofre! 🙌

**Review by snazy — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @jbonofre for bumping Gradle here, and thanks @nastra, @ajantha-bhat and @snazy for the prompt review 🚀

**Comment by jbonofre** [comment]
@Fokko do you mind to set milestone to 1.6.0 for this one (for the tracking) ?

**Comment by Fokko** [comment]
@ajantha-bhat beat me to it :D

**Pull request merged**
