### PR TITLE
Add partition files to SparkBatchScan description

### PR DESCRIPTION
**Pull request by nvitucci**
I've created this draft to discuss about a potential solution to https://github.com/apache/iceberg/issues/2517. 

A few items to discuss:
- Is it too expensive to call `planInputPartitions` before it is actually needed?
- Is the name of each partition file the only relevant piece of information to show in the description?
- The list of partition files is potentially very long. Can it be too expensive to create and keep? Should it be limited to _n_ elements? Should its string representation be shortened?

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
This is adding every file touched to the description which is probably too much (since this could be in the thousands of files). One of the big issues here is this description will set on the Spark Driver for a while so it's a pretty large chunk of memory. Maybe just a summary would be sufficient? Reading Z Manifests - X files from Y partitions?

I think it's a little dangerous to run planning in description since that may be called even when the plan isn't executed and since it becomes caching in this implementation it may have issues if a user runs "Explain" then adds more clauses or something. For a long planned query that also means calling "explain" ends up being a rather expensive operation.

That said I would really like to have more information visible so let's keep thinking on this.

**Comment by nvitucci** [comment]
> This is adding every file touched to the description which is probably too much (since this could be in the thousands of files). One of the big issues here is this description will sit on the Spark Driver for a while so it's a pretty large chunk of memory. Maybe just a summary would be sufficient? Reading Z Manifests - X files from Y partitions?

I agree. With this change, my aim is to have means to show that the partition filters are actually being used. I'll try to figure out the minimal amount of information that can still be useful with this respect.

> I think it's a little dangerous to run planning in description since that may be called even when the plan isn't executed and since it becomes caching in this implementation it may have issues if a user runs "Explain" then adds more clauses or something. For a long planned query that also means calling "explain" ends up being a rather expensive operation.

Yes, this is my main doubt. I've changed the implementation to use the lazy `tasks` variable in the extending classes. I'm not quite sure this will make a lot of difference, but could this be going in the right direction?

**Comment by RussellSpitzer** [comment]
I think we probably could do better by just saying how Iceberg will handle the predicates it gets, like for example it will use X & Y predicates in a partition evaluation expression and Z as a Data file evaluation expression

Then we keep the "which partitions were touched" info as maybe an optional "DEBUG" line in the logs?

**Comment by nvitucci** [comment]
> That way we only display this information at runtime in the logs, but we are sure we don't prematurely calculate scans and read manifests or what not.

I like this use of the logs and especially the varying level of detail, yet I'd like to have a more "on demand" tool available as well to get such information. Is there a way to use an `EXPLAIN EXTENDED`, or `EXPLAIN PLAN` or something similar, where it can be made clear that running it could potentially be expensive?

**Comment by rdblue** [comment]
@nvitucci, I'm not aware of a way for Spark to request extended information from a source. You could implement that in Spark so that it shows a summary of the planning results?

Also, @puneetzaroo is looking into extended our event notifications to include more information about a scan, like the number of manifest files read, number of file splits, number of data files, number of delete files, etc. Maybe that would help you here because you could register a listener, get more detailed information, and do something with it.

**Comment by nvitucci** [comment]
> @nvitucci, I'm not aware of a way for Spark to request extended information from a source. You could implement that in Spark so that it shows a summary of the planning results?

Do you mean as a Spark component out of Iceberg?

> Also, @puneetzaroo is looking into extended our event notifications to include more information about a scan, like the number of manifest files read, number of file splits, number of data files, number of delete files, etc. Maybe that would help you here because you could register a listener, get more detailed information, and do something with it.

This sounds interesting. Where can I get some more information on this?

**Comment by rdblue** [comment]
I'm going to close this since there hasn't been an update in a while. I'm also concerned that this leaks user data into logs, so we should probably look more into the notification for making this info available, rather than updating the description.

**Pull request closed without merging**
