### PR TITLE
SPARK[docs]：Add Warning information under the MERGE INTO syntax

### PR DESCRIPTION
**Pull request by zpi1223**
Changelog category (leave one):
- Documentation (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
For situations where the description of MERGE INTO ... USING (SELECT ...) is not clear enough, add relevant warning information.

Detailed description / Documentation draft:

1. For the regular select syntax, it will be misunderstood as the from operation is followed, so add related warning instructions.
2. If the order of the name field in the table is not the second field, the fields between name and id must be completed in the order of the Schema column of the table, otherwise the data storage part will be misaligned.
3. The test case is as follows：

- create table 
```
CREATE TABLE IF NOT EXISTS hadoop_prod.schema.table16 (
id string,
data string,
jydw_no string,
ts timestamp
) USING iceberg
PARTITIONED BY (bucket(12, id))
```
- merge into syntax（index <- 1 to 6）
```
MERGE INTO hadoop_prod.schema.table16 t
USING (select 6 as id, 'testdata6' as data, 'B36' as jydw_no) s 
ON t.id = s.id and t.jydw_no = s.jydw_no
WHEN MATCHED THEN UPDATE SET t.id = s.id, t.data = s.data, t.jydw_no = s.jydw_no
WHEN NOT MATCHED THEN INSERT (id, data, jydw_no, ts) VALUES ($index, 'testdata, 'B3$index', CURRENT_TIMESTAMP)
```
- Use Merge into wrong syntax to insert 6 pieces of data，the following error will be reported：
```
MERGE INTO hadoop_prod.schema.table16 t
USING (select * from hadoop_prod.schema.table16) s
ON t.id = s.id and t.jydw_no = s.jydw_no
WHEN MATCHED THEN UPDATE SET * || t.id = s.id, t.data = s.data, t.jydw_no = s.jydw_no
WHEN NOT MATCHED THEN INSERT (id, data, jydw_no, ts) VALUES ($index, 'testdata', 'B3$index', CURRENT_TIMESTAMP)
```
```
Exception in thread "main" org.apache.spark.SparkException: The ON search condition of the MERGE statement matched a single row from the target table with multiple rows of the source table. This could result in the target row being operated on more than once with an update or delete operation and is not allowed.
```
- Use Merge into the `correct syntax` to insert 6 pieces of data(First execution), the initial results are as follows：
```
+---+----------+---------+------------------------+
|id |data      |jydw_no  |ts                      |
+---+----------+---------+------------------------+
|1  |testdata  |B31      |2021-12-02 11:29:00.275 |
|2  |testdata  |B32      |2021-12-02 11:29:08.746 |
|3  |testdata  |B33      |2021-12-02 11:29:11.072 |
|4  |testdata  |B34      |2021-12-02 11:29:12.721 |
|5  |testdata  |B35      |2021-12-02 11:29:14.056 |
|6  |testdata  |B36      |2021-12-02 11:29:15.319 |
+---+----------+---------+------------------------+
```
- Use Merge into the `correct syntax` to insert 6 pieces of data(Second execution), the initial results are as follows：
```
+---+----------+--------+------------------------+
|id |data      |jydw_no |ts                      |
+---+----------+--------+------------------------+
|1  |testdata  |B31     |2021-12-02 11:29:00.275 |
|2  |testdata  |B32     |2021-12-02 11:29:08.746 |
|3  |testdata  |B33     |2021-12-02 11:29:11.072 |
|4  |testdata  |B34     |2021-12-02 11:29:12.721 |
|5  |testdata  |B35     |2021-12-02 11:29:14.056 |
|6  |testdata6 |B36     |2021-12-02 11:29:15.319 |
+---+----------+--------+------------------------+
```
- Use Merge into the `wrong syntax` to insert 6 pieces of data(Second execution), the initial results are as follows：
```
MERGE INTO hadoop_prod.schema.table16 t
USING (select 6 as id, 'B36' as jydw_no, 'testdata7' as data) s
ON t.id = s.id and t.jydw_no = s.jydw_no
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT (id, data, jydw_no, ts) VALUES ($index, 'testdata', 'B3$index', CURRENT_TIMESTAMP)
```
```
+---+----------+--------------+------------------------+
|id |data      |jydw_no       |ts                      |
+---+----------+--------------+------------------------+
|1  |testdata  |B31           |2021-12-02 11:29:00.275 |
|2  |testdata  |B32           |2021-12-02 11:29:08.746 |
|3  |testdata  |B33           |2021-12-02 11:29:11.072 |
|4  |testdata  |B34           |2021-12-02 11:29:12.721 |
|5  |testdata  |B35           |2021-12-02 11:29:14.056 |
|6  |B36       |testdata7     |2021-12-02 11:29:15.319 |
+---+----------+--------------+------------------------+
```
4.Therefore, I think it is necessary to add this waring information to clearly indicate how to use it.

### CODE REVIEW

**Review by kbendick — COMMENTED** [review]
Hi @zpi1223! Thanks for the PR.

For your own information, If this is what I think you're talking about (that `MERGE INTO` is resolved by position), this has actually been fixed in Spark 3.2.

I have some unit tests here demonstrating that `MERGE INTO` will do by name resolution starting with Spark 3.2: https://github.com/apache/iceberg/pull/3440

Of course, Spark 3.2 support won't be generally available until Iceberg 0.13.0 is released, but wanted to let you know.

**Comment by zpi1223** [comment]
> Hi @zpi1223! Thanks for the PR.
> 
> For your own information, If this is what I think you're talking about (that `MERGE INTO` is resolved by position), this has actually been fixed in Spark 3.2.
> 
> I have some unit tests here demonstrating that `MERGE INTO` will do by name resolution starting with Spark 3.2: #3440
> 
> Of course, Spark 3.2 support won't be generally available until Iceberg 0.13.0 is released, but wanted to let you know.

Hi @kbendick , Thank you very much for your prompt reply. I personally think that these two are not conflicting.

First，You are talking about the realization of functions, and what I want to express in this PR is to add certain warning information at the document level, so that the description information on the official website can be more complete, so as not to cause misunderstandings and affect the use in actual production.

Secondly，Because we misunderstood the first time we used it, it took a certain amount of time to use it correctly at the end.

**Comment by kbendick** [comment]
> > Hi @zpi1223! Thanks for the PR.
> > For your own information, If this is what I think you're talking about (that `MERGE INTO` is resolved by position), this has actually been fixed in Spark 3.2.
> > I have some unit tests here demonstrating that `MERGE INTO` will do by name resolution starting with Spark 3.2: #3440
> > Of course, Spark 3.2 support won't be generally available until Iceberg 0.13.0 is released, but wanted to let you know.
> 
> Hi @kbendick , Thank you very much for your prompt reply. I personally think that these two are not conflicting.
> 
> First，You are talking about the realization of functions, and what I want to express in this PR is to add certain warning information at the document level, so that the description information on the official website can be more complete, so as not to cause misunderstandings and affect the use in actual production.
> 
> Secondly，Because we misunderstood the first time we used it, it took a certain amount of time to use it correctly at the end.

I don’t disagree. We should probably document it as well as it’s not clearly documented in the Spark docs (and people likely come to our docs for MERGE INTO information given that vanilla spark doesn’t implement merge into, just provide the primitives for us to do it).

But maybe the documentation can state that it’s a Spark bug and not an issue in Spark 3.2 and later?

**Comment by zpi1223** [comment]
> > > Hi @zpi1223! Thanks for the PR.
> > > For your own information, If this is what I think you're talking about (that `MERGE INTO` is resolved by position), this has actually been fixed in Spark 3.2.
> > > I have some unit tests here demonstrating that `MERGE INTO` will do by name resolution starting with Spark 3.2: #3440
> > > Of course, Spark 3.2 support won't be generally available until Iceberg 0.13.0 is released, but wanted to let you know.
> > 
> > 
> > Hi @kbendick , Thank you very much for your prompt reply. I personally think that these two are not conflicting.
> > First，You are talking about the realization of functions, and what I want to express in this PR is to add certain warning information at the document level, so that the description information on the official website can be more complete, so as not to cause misunderstandings and affect the use in actual production.
> > Secondly，Because we misunderstood the first time we used it, it took a certain amount of time to use it correctly at the end.
> 
> I don’t disagree. We should probably document it as well as it’s not clearly documented in the Spark docs (and people likely come to our docs for MERGE INTO information given that vanilla spark doesn’t implement merge into, just provide the primitives for us to do it).
> 
> But maybe the documentation can state that it’s a Spark bug and not an issue in Spark 3.2 and later?

I still don't understand.
First of all, the original intention of this PR is to improve the document information to avoid unnecessary understanding of the related Merge Into function when users use it, so that users can get a better experience.

Secondly, I did not understand the Spark 3.2 bug that you explained. This PR is just a document-level information supplement. What does it have to do with Spark bugs?

**Pull request closed without merging**
