### PR TITLE
[Python] support BucketByteBuffer and BucketUUID

### PR DESCRIPTION
**Pull request by jun-he**
Follow up https://github.com/apache/iceberg/pull/2689#discussion_r650597195

### CODE REVIEW

**Comment by jun-he** [comment]
@TGooch44 and @rymurr can you help to review it? Thanks.

**Comment by rymurr** [comment]
Thanks @jun-he ! This looks good. However I am worried about #2837 and if python and Java might return different results. What do you think?

**Comment by TGooch44** [comment]
> Thanks @jun-he ! This looks good. However I am worried about #2837 and if python and Java might return different results. What do you think?

It looks like the following matches the expected output(which I guess is different than the Java output):
```
>>> import mmh3
>>> (mmh3.hash("💰".encode("utf-8")) & 2147483647) % 32
12

```

**Comment by jun-he** [comment]
@rymurr @TGooch44 they might mismatch. I will take a look at all the hashcode generated in Python versus Java. This might be a problem for many.

**Comment by rymurr** [comment]
I guess python is doing the 'right' thing. The question for me is: will Java start doing the right thing or maintain the wrong thing for backwards compatibility. Python should, I think, be consistent w/ Java.

**Comment by TGooch44** [comment]
@ryanmurr Unfortunately, I think you're right that matching Java is more
important than being correct according to spec.  We may want to wait on
this until the java community decides if they are going to fix this or not.

Seems like they're trying to decide how likely existing users are to have
been impacted.

**Comment by findepi** [comment]
Elevating the 'wrong' behavior to be 'the standard' will be hard for non-Java languages.
Please take a look at my proposed fix in Guava https://github.com/google/guava/pull/5649 for this.
In order to match Iceberg Java implementation, one would perhaps need to translate that code (without the fix) into Python.

Waiting for Java bucketing version to be fixed seems reasonable though. This avoids correctness issues -- no support for bucketing in Python, means no bugs at all.

FWIW, in Trino, bucketing did not have the bug (that's how we found https://github.com/apache/iceberg/issues/2837), so 'correctly' bucketed data can be out there too.

**Comment by rymurr** [comment]
> Elevating the 'wrong' behavior to be 'the standard' will be hard for non-Java languages.

I agree. I think the last thing we want to do is start duplicating guava bugs in other languages. It is hard and unnecessary. 

Shall we wait for the guava fix to be merged and propagated to Iceberg then?

**Comment by TGooch44** [comment]
Waiting seems like the best option here.

**Comment by findepi** [comment]
> Shall we wait for the guava fix to be merged and propagated to Iceberg then?

Per @rdblue 's https://github.com/apache/iceberg/issues/2837#issuecomment-884562950 i posted a proposed fix https://github.com/apache/iceberg/pull/2849.
If it gets merged, the work here would be unblocked.

**Comment by jun-he** [comment]
Thanks @findepi for the fix.

@TGooch44 @rymurr  I think python should just hash the UTF-8 bytes. I will run a quick check to see if Java and Python match in various cases.

**Review by findepi — COMMENTED** [review]
code lgtm

is there any place in tests where hash values could be asserted?

**Comment by jun-he** [comment]
@findepi  I added additional tests to check the hash values.
It matched the result in [Java test](https://github.com/apache/iceberg/blob/master/api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java#L64-L119)

**Pull request merged**
