### PR TITLE
make ApplyNameMapping keep field's name after name mapping.

### PR DESCRIPTION
**Pull request by zhongyujiang**
This PR makes ApplyNameMapping keep field's name after name mapping, which is for compatibility while reading the migrated Iceberg table with legacy parquet schema mentioned in this issue #3604.

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
Looks correct, could you please add a unit test for this？

**Comment by zhongyujiang** [comment]
> Looks correct, could you please add a unit test for this？

Of course!

**Comment by zhongyujiang** [comment]
Hi @chenjunjiedada, I found that [RemoveIds](https://github.com/apache/iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/RemoveIds.java#L50) haven't keep the original name of repeatedElement of list/map type too:
```
@Override
  public Type list(GroupType array, Type item) {
    return Types.list(array.getRepetition())
        .element(item)
        .named(array.getName());
  }
```
I think this also need a fix.
And speaking of unit test, I found that [TestPruneColumns](https://github.com/apache/iceberg/blob/master/parquet/src/test/java/org/apache/iceberg/parquet/TestPruneColumns.java) already did a similar one for PruneColumns, maybe I can reuse the fileSchema in it, so can I just rename TestPruneColumns to TestParquetTypeVisitor and put the unit tests for RemoveIds and ApplyNameMapping in it? What do you think?

**Comment by zhongyujiang** [comment]
Hey @chenjunjiedada , I make RemoveIds keeps field's original name too and add unit tests for both RemoveIds and ApplyNameMapping in the latest commit, could you please give it a review?

**Comment by uncleGen** [comment]
Is there same issue in ORC ff?

**Comment by uncleGen** [comment]
Besides, could you please add an end-to-end unit test?

**Comment by zhongyujiang** [comment]
> In general, this pr makes sense to me, and is there same issue in ORC ff?

Sorry, I don't know much of ORC, and I think this issue is already solved by this [pr](https://github.com/apache/iceberg/pull/3723), it's already merged. I'll close this one.

**Pull request closed without merging**
