### PR TITLE
Arrow: Fix errorprone warnings

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Screenshot 2023-05-02 at 1 13 22 PM

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
cc: @nastra, @Fokko

**Comment by ajantha-bhat** [comment]
Re-trrigering the build due to 

> Could not resolve org.antlr:antlr4:4.8.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.8/antlr4-4.8.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.8/antlr4-4.8.pom'.
               > repo.maven.apache.org

**Review by nastra — APPROVED** [review]

**Comment by ajantha-bhat** [comment]
I think it is ready for merge.

**Comment by nastra** [comment]
thanks for fixing this @ajantha-bhat

**Pull request merged**
