### PR TITLE
REST: Use HEAD request to check table existence

### LINKED ISSUE #10993: Use `HEAD` operation for `tableExists` in REST-Catalog
### Feature Request / Improvement

It looks like we just load the table and fail if it raises an exception:

https://github.com/apache/iceberg/blob/f2d62757e210df5498f147aa126926477ac6c156/api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java#L180-L187

Instead we would love to override this for the REST-Catalog, and use the `HEAD` call instead:

https://github.com/apache/iceberg/blob/97e034b2cec9408a6f792c410a8eb8dddb452e14/open-api/rest-catalog-open-api.yaml#L833-L864

This will be more friendly on the catalog since it doesn't have to load the metadata, and will also return a faster response. We also use this when creating a view to double-check if there is not a table with the same name: https://github.com/apache/iceberg/blob/f2d62757e210df5498f147aa126926477ac6c156/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L1303

The HEAD operation will be much faster than trying to load the table.

### Query engine

None

### Willingness to contribute

- [ ] I can contribute this improvement/feature independently
- [ ] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [ ] I cannot contribute this improvement/feature at this time

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #10993

### CODE REVIEW

**Comment by ebyhr** [comment]
@Fokko Gentle reminder.

**Review by Fokko — APPROVED** [review]
@ebyhr Sorry, I was out on paternity leave. This looks good to me, could you pull in the latest main branch?

**Comment by ebyhr** [comment]
(Rebased on main without any changes)

**Comment by ebyhr** [comment]
@Fokko Thank you for your review. CI is green now.

**Comment by Fokko** [comment]
@ebyhr Thanks, let's move this forward.

**Pull request merged**
