### PR TITLE
Flink: Backport: Flink: Refactor sink tests to use HadoopCatalogResource

### PR DESCRIPTION
**Pull request by pvary**
Backport of #6583

### CODE REVIEW

**Comment by pvary** [comment]
- 1.15 is a clean backport
- 1.14 the `tablePath` is a class variable, so it is not clean, but easy to follow the changes

**Comment by pvary** [comment]
The root cause of the difference of the backport is that #4699 is missing from the v1.14 code path.

**Comment by pvary** [comment]
Created #6603 for backporting #4699 to v1.14

**Review by stevenzwu — APPROVED** [review]

**Comment by pvary** [comment]
Merged to master. 
Thanks for the review @stevenzwu!

**Pull request merged**
