### PR TITLE
Spark: Added merge schema as spark configuration

### PR DESCRIPTION
**Pull request by aleenamg21-1**
Current implementation sets merge-schema as a write option which limits it from being set globally. This pull request aims to address this limitation by enabling merge-schema as a Spark configuration.

### CODE REVIEW

**Review by aleenamg21-1 — COMMENTED** [review]
@RussellSpitzer can you please review this P.R.

**Review by aleenamg21-1 — COMMENTED** [review]
@nastra, @amogh-jahagirdar, @manuzhang  Could you please review this P.R

**Review by RussellSpitzer — APPROVED** [review]
Looks fine to me

**Comment by RussellSpitzer** [comment]
Thanks for the PR @aleenamg21-1

**Pull request merged**
