### PR TITLE
Spark-3.0: Remove spark/v3.0 folder

### PR DESCRIPTION
**Pull request by ajantha-bhat**
As a follow-up to https://github.com/apache/iceberg/pull/6093,
removes spark/v3.0 folder.

### CODE REVIEW

**Comment by rdblue** [comment]
@ajantha-bhat, I merged #6093. Can you rebase this one?

**Comment by ajantha-bhat** [comment]
@rdblue: I have rebased this PR now. Thanks.

**Comment by ajantha-bhat** [comment]
cc: @Fokko

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @ajantha-bhat

**Pull request merged**
