### PR TITLE
Spark 3.1:Port #3557 to Spark 3.1

### PR DESCRIPTION
**Pull request by hililiwei**
Spark 3.1:Port #3557 to Spark 3.1
Split from #5479

### CODE REVIEW

**Review by singhpk234 — APPROVED** [review]
LGTM, Thanks @hililiwei for the change !

**Comment by jackye1995** [comment]
@hililiwei is this still needed? Trying to close some old PRs

**Comment by hililiwei** [comment]
For those of using Spark 3.1 version , it's valuable. Let me resolve the conflict. @jackye1995

**Comment by ajantha-bhat** [comment]
Closing this PR as spark-3.1 module is removed from master code.

**Pull request closed without merging**
