### PR TITLE
AWS: Remove S3URI usage from public constructors

### PR DESCRIPTION
**Pull request by edgarRd**
While `S3InputFile` and `S3OutputFile` are public, in order to build a custom `FileIO` using them, `S3URI` needs to be public like the rest of the arguments in their public constructors.

PTAL @danielcweeks @jackye1995 - Thanks!

### CODE REVIEW

**Comment by danielcweeks** [comment]
Hey, @edgarRd, if I remember correctly, the reason it is currently package is that the `S3URI` implementation covers most common S3 identifiers, but not all (there was some prior discussion about the complexity of this and lack of a good utility with the aws sdkv2 implementation).

I'm thinking at this point that maybe we shouldn't expose the S3URI, but rather push the S3URI reference down into the `BaseS3File` so that we don't expose it at the `S3FileIO` level.

Does that make sense and would that address your use case?

Thanks,
Dan

**Comment by edgarRd** [comment]
Hey, @danielcweeks - thanks for the quick reply. Yeah, I think that makes sense. I can update this PR with that change pushing `S3URI` down to `BaseS3File` and removing the direct reference from the constructors in `S3InputFile` and `S3OuputFile`.

**Comment by jackye1995** [comment]
Could you describe more about why you need them public to build a custom `FileIO`? I don't see a use case why `S3InputFile` and `S3OutputFile` should be directly referenced in any place outside the package itself, and `S3URI` is just a implementation detail for it.

**Comment by edgarRd** [comment]
@jackye1995 We have an internal implementation of a `FileIO` based on S3, `S3OutputFile` and `S3InputFile` are public so seems like they are already part of a public API, which helps since they are generic enough to handle other S3 use cases we have internally.
I think the solution proposed by @danielcweeks works for most of the use cases given that `S3InputFile` and `S3OutputFile` are public by removing non-public arguments from the constructors.

**Comment by jackye1995** [comment]
I see, thanks for the explanation.

I would suggest that we should continue to keep constructor package protected, and expose a public static method like 

```java
S3InputFile.fromLocation(String location, S3Client client, AwsProperties awsProperties) {
 ...
}
```

So that the method signatures between `S3InputFile` and `HadoopInputFile` are consistent. The same applies for `S3OutputFile` versus `HadoopOutputFile`.

**Review by jackye1995 — APPROVED** [review]
LGTM. We are changing the public constructor, but since the constructor cannot be used anyway, I think that is fine. @danielcweeks I don't have any further concerns, please take a look when you have time, thanks!

**Comment by danielcweeks** [comment]
+1 LGTM. Thanks @edgarRd and @jackye1995

**Comment by edgarRd** [comment]
Thanks for the reviews, folks!

**Pull request merged**
