### PR TITLE
Spark 3.1: Remove module

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR removes support for Spark 3.1 as discussed on the dev list [here](https://lists.apache.org/thread/znvy3fqw5pqrx4nhz0bvntdpqzbgy8mk).

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @Fokko @nastra @amogh-jahagirdar @RussellSpitzer @flyrain

**Review by ajantha-bhat — APPROVED** [review]
LGTM. 

Some more followups may be needed.
- We can remove spark 3.1 mention from documents also. (spark-writes.md, nessie.md)
- Some table properties can be removed which was only used in spark-3.1
https://github.com/apache/iceberg/blob/1e52f2edc4ec79179662b2179d64833d88f3311d/core/src/main/java/org/apache/iceberg/TableProperties.java#L356-L367

I can raise the followup PR if you are busy (If you can't handle in this PR maybe)

**Review by Fokko — APPROVED** [review]
I agree that we should remove 3.1, but why not do it after 1.4? Am I missing any downsides besides having to upload a few more artifacts?

Some folks went through the trouble of backporting features to 3.1 (eg. https://github.com/apache/iceberg/pull/8217). Also, as @ajantha-bhat mentioned, we need to clean up the docs as well: https://github.com/apache/iceberg/pull/7390#pullrequestreview-1394732034

**Comment by aokolnychyi** [comment]
@Fokko, you are right that we did cherry-pick some changes to 3.1 but it is heavily behind in capabilities. There are some known limitations that may affect performance (e.g. the way we do cardinality check, for example). Someone may test the brand new Iceberg jar with Spark 3.1 and think that's the best we offer.

That said, it is minor. I am debating this too and have no problem doing 1.4 with this module in.

**Comment by aokolnychyi** [comment]
@ajantha-bhat, I'd appreciate if you could help with the changes in core and docs in a follow-up PR.

**Comment by aokolnychyi** [comment]
@danielcweeks @RussellSpitzer @rdblue, any thoughts on removing or keeping Spark 3.1 before 1.4?

**Comment by RussellSpitzer** [comment]
+1 On removing it now, I think any work on 3.1 is really just sunk costs. We don't gain that much and we are basically saying we will continue supporting 3.1 for any 1.4.x releases that may need to occur.

**Comment by danielcweeks** [comment]
I'm +1 on removing it as well for removal (agree with @RussellSpitzer points).

**Review by danielcweeks — APPROVED** [review]

**Comment by aokolnychyi** [comment]
Agreed, let's remove now.

**Comment by aokolnychyi** [comment]
@ajantha-bhat, I've submitted a PR to quickly drop the table props to cut an RC asap. Could you look into other places that I missed?

**Comment by ajantha-bhat** [comment]
>  @ajantha-bhat, I've submitted a PR to quickly drop the table props to cut an RC asap. Could you look into other places that I missed?

Sorry for the dealy. I live in India timezone. 
Here is the PR https://github.com/apache/iceberg/pull/8671
We can merge this and use it if there is another RC for some reason.

**Pull request merged**
