### PR TITLE
Bump Jackson to 2.11.4

### PR DESCRIPTION
**Pull request by Fokko**
Will solve issues in https://github.com/apache/iceberg/pull/1648#issuecomment-759135813

Quoting @rdblue:
> our Jackson version should be okay to update. We shade and relocate it in the runtime Jars to avoid conflicts with Spark.

### CODE REVIEW

**Comment by Fokko** [comment]
Same issue as https://github.com/apache/iceberg/pull/1648#issuecomment-759304104

**Comment by rdblue** [comment]
I think the test problem might be that we have some Jackson Scala dependencies forced in `build.gradle`:

```
      resolutionStrategy {
        force 'com.fasterxml.jackson.module:jackson-module-scala_2.11:2.10.2'
        force 'com.fasterxml.jackson.module:jackson-module-scala_2.12:2.10.2'
        force 'com.fasterxml.jackson.module:jackson-module-paranamer:2.10.2'
      }
```

@aokolnychyi, do you have more context on that?

I'm not sure that those are even used. I don't see dependencies on `jackson-module-scala_*` in iceberg-spark3-extensions.

**Comment by Fokko** [comment]
@rdblue that did the trick, thanks!

**Comment by rdblue** [comment]
I think this is okay, but I'd prefer to get it in after the 0.11.0 release is out so that we don't accidentally introduce a library incompatibility with little time to catch it. Is that okay with you, @Fokko?

**Comment by Fokko** [comment]
@rdblue Yes, I think that's a great idea. Would be a pity to brick the 0.11 release. I would also postpone #2110 and #1648 in that case since they also pull in the latest version of Avro.

**Comment by rdblue** [comment]
@Fokko, could you rebase this? Now that 0.11.0 is out, we can get it into master.

**Comment by Fokko** [comment]
Awesome, sure thing. Pulled in latest master, and resolved the conflicts!

**Comment by rdblue** [comment]
@aokolnychyi FYI

**Comment by rdblue** [comment]
Thanks for the update, @Fokko!

**Pull request merged**
