### PR TITLE
Build: Remove version.txt that was accidentally added in bde2d896ac

### PR DESCRIPTION
**Pull request by rdblue**

### CODE REVIEW

**Review by jackye1995 — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks for the review, @jackye1995!

**Comment by jackye1995** [comment]
np, sorry for the inconvenience caused

**Comment by rdblue** [comment]
No worries, accidents happen.

**Review by kbendick — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks for reviewing, @jackye1995 & @kbendick!

**Pull request merged**
