### PR TITLE
Core: Allow one data writer in BasePositionDeltaWriter

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR allows using a single data writer in `BasePositionDeltaWriter`.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@szehon-ho, could you check this out?

**Review by szehon-ho — APPROVED** [review]
Looks good. For some general context, where will this be used?

**Comment by aokolnychyi** [comment]
@szehon-ho, I am going to use this on the Spark side to write a delta where I want to produce only one data file.

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @szehon-ho!

**Pull request merged**
