### PR TITLE
replaced DateDayVector and TimestampMicroTZVector

### PR DESCRIPTION
**Pull request by pranaydharmale**
With IntVector and BigIntVector #834

### CODE REVIEW

**Comment by rdblue** [comment]
@samarthjain, can you take a look at this?

What is the context for #834? Is that to make Spark faster?

**Comment by samarthjain** [comment]
The idea behind #834 was to see we can get rid of our usage of `DateDayVector` and `TimestampMicroTZVector` since date and timestamps can be stored as integers and longs in `IntVector` and `BigIntVector`, respectively. It also prevents us from paying possible dynamic dispatch costs when calling getInt() and getLong() in `ArrowVectorAccessors` (in iceberg-spark module) by getting rid of `DateAccessor` and `TimestampAccessor` classes added in #828. We may also need to add/update tests specific to Date and Timestamp types to ensure this change won't break anything.

@pranaydharmale - I think we should wait for the #828 PR to be merged first. Once that is in, this PR would need to be updated to get rid of the two classes along with tests.

**Comment by pranaydharmale** [comment]
@samarthjain noted; will wait for #828

**Comment by rdblue** [comment]
@pranaydharmale, #828 is in if you'd like to pick this up again. Thanks!

**Comment by pranaydharmale** [comment]
@rdblue I'll pick it back up. Thank you.

**Comment by rdblue** [comment]
I'm going to close this for now. Feel free to reopen if you'd like to work on it!

**Pull request closed without merging**
