### PR TITLE
Update flink-connector.md

### PR DESCRIPTION
**Pull request by 911432**
1. Added Rest Catalogs.
2. The link has been modified from a specific version to a stable version.

### CODE REVIEW

**Comment by Fokko** [comment]
@911432 We had a reorganization in https://github.com/apache/iceberg/pull/7099, could you rebase your PR? Fixed to the docs are very welcomed.

**Comment by 911432** [comment]
Great. I'll try.

**Comment by 911432** [comment]
I have done rebase about https://github.com/apache/iceberg/pull/7214 and https://github.com/apache/iceberg/pull/7215

**Comment by 911432** [comment]
@Fokko I have done rebase about https://github.com/apache/iceberg/pull/7214 and https://github.com/apache/iceberg/pull/7215

**Pull request closed without merging**
