### PR TITLE
Build: switch to slf4j-simple 2.x for test implementation dependency

### PR DESCRIPTION
**Pull request by stevenzwu**
right now, logging for tests is broken. it appears to affect both `main` and `apache/1.6.x` branch.

```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/Users/stevenwu/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

test logging seems to have been broken since `apache-iceberg-1.4.0` by mock netty server

```
org.slf4j:slf4j-api:2.0.6
+--- org.mock-server:mockserver-client-java:5.15.0
|    +--- testRuntimeClasspath
|    \--- org.mock-server:mockserver-netty:5.15.0
|         \--- testRuntimeClasspath
+--- org.mock-server:mockserver-core:5.15.0
|    +--- org.mock-server:mockserver-netty:5.15.0 (*)
|    \--- org.mock-server:mockserver-client-java:5.15.0 (*)
\--- org.mock-server:mockserver-netty:5.15.0 (*)
```

It seems that Avro `1.12.0` brings in slf4j-api dependency to 2.x for runtime dependency. That could affect the downstream applications (like Spark, Trino, Flink etc.)
```
 ./gradlew -q :iceberg-core:dependencyInsight --dependency slf4j-api --configuration runtimeClasspath
```

Here are some snippets from the above output
```
org.slf4j:slf4j-api:2.0.13
\--- org.apache.avro:avro:1.12.0
     \--- runtimeClasspath

org.slf4j:slf4j-api:1.7.36 -> 2.0.13
+--- project :iceberg-api
|    \--- runtimeClasspath
+--- project :iceberg-common
|    \--- runtimeClasspath
+--- runtimeClasspath
\--- org.apache.httpcomponents.client5:httpclient5:5.3.1
     \--- runtimeClasspath
```

This PR brings the `testImplementation` dep of `slf4j-simple`  to 2.x to match the `slf4j-api`. You can verify the logging break and fix by running the `TestInMemoryCatalog` and observe the log output.

### CODE REVIEW

**Comment by stevenzwu** [comment]
right now, logging for tests is broken. it appears to affect both `main` and `apache/1.6.x` branch.

```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/Users/stevenwu/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

It seems that Avro `1.12.0` brings in slf4j-api dependency to 2.x which caused this issue.
```
./gradlew -q :iceberg-core:dependencyInsight --dependency slf4j-api --configuration tRC
```

Here are some snippets from the above output
```
org.slf4j:slf4j-api:2.0.13
\--- org.apache.avro:avro:1.12.0
     \--- testRuntimeClasspath

org.slf4j:slf4j-api:2.0.6 -> 2.0.13
+--- org.mock-server:mockserver-client-java:5.15.0
|    +--- testRuntimeClasspath
|    \--- org.mock-server:mockserver-netty:5.15.0
|         \--- testRuntimeClasspath
+--- org.mock-server:mockserver-core:5.15.0
|    +--- org.mock-server:mockserver-netty:5.15.0 (*)
|    \--- org.mock-server:mockserver-client-java:5.15.0 (*)
\--- org.mock-server:mockserver-netty:5.15.0 (*)

org.slf4j:slf4j-api:2.0.9 -> 2.0.13
+--- org.eclipse.jetty:jetty-http:11.0.22
|    \--- org.eclipse.jetty:jetty-server:11.0.22
|         +--- testRuntimeClasspath
|         \--- org.eclipse.jetty:jetty-security:11.0.22
|              \--- org.eclipse.jetty:jetty-servlet:11.0.22
|                   \--- testRuntimeClasspath
```

This PR brings the `testImplementation` dep of `slf4j-simple`  to 2.x to match the `slf4j-api`. You can verify the logging break and fix by running the `TestInMemoryCatalog` and observe the log output.

**Comment by stevenzwu** [comment]
test logging seems to have been broken since `apache-iceberg-1.4.0` by mock nets server

```
org.slf4j:slf4j-api:2.0.6
+--- org.mock-server:mockserver-client-java:5.15.0
|    +--- testRuntimeClasspath
|    \--- org.mock-server:mockserver-netty:5.15.0
|         \--- testRuntimeClasspath
+--- org.mock-server:mockserver-core:5.15.0
|    +--- org.mock-server:mockserver-netty:5.15.0 (*)
|    \--- org.mock-server:mockserver-client-java:5.15.0 (*)
\--- org.mock-server:mockserver-netty:5.15.0 (*)
```

**Comment by dramaticlly** [comment]
change LGTM but dependent bot tried to upgrade in #9688 but @jbonofre mentioned [there's -1 on this upgrade](https://github.com/apache/iceberg/pull/9688#issuecomment-1935668919), maybe he has more context

**Comment by jbonofre** [comment]
@dramaticlly the reason about my previous -1  was about dependencies (in the tests) bring other slf4j bindings (from slf4j 1).
For instance, I remember aliyum test was using old spring-boot version with slf4j binding.
Let me do a new pass on this PR and align the versions if needed.

FYI, I'm working on removing some dependencies (like spring-boot that I started 😄 ) now that we have new JDK version support.

**Review by nastra — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
@jbonofre Have you had a chance to check this again?

**Comment by jbonofre** [comment]
Not yet but I don't want to hold this change. I propose to merge and as I'm working on dependencies cleanup and versions alignement I will check at that time.

**Review by jbonofre — APPROVED** [review]

**Review by RussellSpitzer — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Ok, I think we are good to merge here. We can always revert if this ends up causing issues that we haven't forseen.

**Comment by RussellSpitzer** [comment]
Thanks @stevenzwu and @nastra and @jbonofre  For Review

**Comment by rdblue** [comment]
Thanks for doing the research and getting this in, @stevenzwu!

**Pull request merged**
