### PR TITLE
Spark: Make ignored UPDATE tests deterministic

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR makes ignored UPDATE tests deterministic.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @rdblue @dilipbiswal @RussellSpitzer

**Review by RussellSpitzer — APPROVED** [review]
I assume you hit this when running on a patched Spark build? 

lgtm

**Comment by aokolnychyi** [comment]
Yep, @RussellSpitzer

**Review by dilipbiswal — APPROVED** [review]

**Review by shardulm94 — APPROVED** [review]
Thanks @aokolnychyi! Merging this.

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @RussellSpitzer @dilipbiswal @shardulm94!

**Pull request merged**
