### PR TITLE
Spark 3.2: Add a new Spark SQLConf to influence the write distribution mode

### PR DESCRIPTION
**Pull request by dramaticlly**
backport of #6838 , this presume #6877 need to be merged first 

CC @aokolnychyi @amogh-jahagirdar @szehon-ho

### CODE REVIEW

**Review by jackye1995 — APPROVED** [review]
looks good to me!

**Comment by aokolnychyi** [comment]
@dramaticlly, I merged #6877. Could you rebase this one?

**Comment by dramaticlly** [comment]
@an

> @dramaticlly, I merged #6877. Could you rebase this one?

Thank you @aokolnychyi , rebased latest upstream and I see the parent is what you just merged. I guess we cam wait until all check to pass

**Review by aokolnychyi — APPROVED** [review]
Pending tests.

**Review by amogh-jahagirdar — APPROVED** [review]
Looks good to me! thanks @dramaticlly

**Comment by aokolnychyi** [comment]
Thanks, @dramaticlly! Thanks for reviewing, @jackye1995 @amogh-jahagirdar!

**Pull request merged**
