### PR TITLE
reduce enum array allocation

### PR DESCRIPTION
**Pull request by sullis**
## Motivation

reduce enum array allocation

## Modifications

cache enum .values() in a static variable

## Additional context

https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/

### CODE REVIEW

**Comment by nastra** [comment]
@sullis thanks for the improvement. I think it might make sense to also update other enums that do it like this. Could you please check the codebase and update those?

**Comment by sullis** [comment]
> @sullis thanks for the improvement. I think it might make sense to also update other enums that do it like this. Could you please check the codebase and update those?

Agreed.  I just pushed an update to this PR.  I identified 9 occurrences in the Apache Iceberg source tree.

**Comment by sullis** [comment]
> Looks like CI is failing. Please run `./gradlew spotlessApply`

Done. Ready for review.

**Comment by sullis** [comment]
CI build looks good ✅

**Pull request merged**
