### PR TITLE
Core: Use current user ugi to run in WORKER_POOL to prevent wrong cre…

### PR DESCRIPTION
**Pull request by jshmchenxi**
…dentials

For #2753, fix token expiration when using WORKER_POOL with Spark Thrift Server.

### CODE REVIEW

**Comment by rdblue** [comment]
@jshmchenxi, it sounds like the problem might be that the UGI in your environment changes based on the incoming request, but the thread pool that handles planning keeps its initial user information?

I'm suspicious that the solution is to add Hadoop-specific UGI code everywhere that Iceberg uses a thread pool. This solution doesn't seem sustainable to me. One easy solution is to disable the thread pool in your environment by setting `iceberg.scan.plan-in-worker-pool=false` in Java's system properties. If you want to use a thread pool, we could update the `TableScan` interface and Spark to manage thread pools at a session level.

**Comment by jshmchenxi** [comment]
> the UGI in your environment changes based on the incoming request, but the thread pool that handles planning keeps its initial user information?

@rdblue Yes, that's the problem.
I found it not elegant to add UGI related code to Iceberg, too. However, we need to use thread pool otherwise it will slow down the processing.

> we could update the TableScan interface and Spark to manage thread pools at a session level.

Does it mean that we should create a thread pool with a session lifetime (I'm not sure how to implement), or just replace the WORKER_POOL with a newly created one when it's necessary?

**Comment by rdblue** [comment]
> Does it mean that we should create a thread pool with a session lifetime (I'm not sure how to implement), or just replace the WORKER_POOL with a newly created one when it's necessary?

The worker pool is shared and is not something we want to change. In your case, you'd want to add the ability to pass a pool when planning a scan and then update the Spark code to keep track of a pool per session.

**Comment by zuston** [comment]
You means that expired ugi is remained in single thread? @jshmchenxi

**Comment by jshmchenxi** [comment]
Yes, the ugi remains to be the one when the thread was first accessed in the global thread pool. @zuston

**Pull request closed without merging**
