### PR TITLE
Core: Skip context for object storage in table prefixes

### PR DESCRIPTION
**Pull request by rdblue**
This detects when an object storage location is within a table's prefix and avoids adding the table and database names to file paths as context.

### CODE REVIEW

**Review by szehon-ho — APPROVED** [review]
I think this is a great change, I had seen this myself and filed an overcomplicated issue https://github.com/apache/iceberg/issues/3086, this is much cleaner.

So, upon upgrade of Iceberg, tables will start writing files to new locations (still under the configured location), should be minimal user impact.

Do you think its worth effort to add a small test in TestLocationProvider ?

**Review by anuragmantri — APPROVED** [review]
Thanks for making this change. Maybe it's worth adding 
- a unit test
- a note in the [docs](https://iceberg.apache.org/docs/latest/aws/#object-store-file-layout) about this behavior

**Comment by rdblue** [comment]
Thanks for reviewing, @szehon-ho and @anuragmantri!

**Comment by rdblue** [comment]
> a note in the [docs](https://iceberg.apache.org/docs/latest/aws/#object-store-file-layout) about this behavior

There's currently no discussion of how object storage paths are laid out and I'm not sure I'd over-complicate the page by describing it in enough detail to cover this. I think it is sufficient to say that we use a hash in the location to distribute files.

**Pull request merged**
