### PR TITLE
Spec: Explicitly specify `operation` as a required field of Snapshot's `summary` field

### PR DESCRIPTION
**Pull request by sungwy**
Be more specific about `operation` being a required field, as a follow up to the [mail list discussion thread](https://lists.apache.org/thread/g8fwsfv9nv4k17pdc75gxz74oz3mcf5b) on the topic.

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Review by kevinjqliu — APPROVED** [review]
Also enforcing this when parsing `Snapshot` from JSON, #11354

**Review by Fokko — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
@sungwy Can you please rebase this? I think we are good to merge once the conflicts are resolved

**Comment by sungwy** [comment]
Hi @RussellSpitzer appreciate the chase up 🙂 

I've resolved the conflicts - does this look good to merge?

**Comment by RussellSpitzer** [comment]
All good with me @sungwy ! Thanks for the PR and thanks @Fokko, @nastra and @kevinjqliu  for reviewing

**Pull request merged**
