### PR TITLE
Hive: HiveSchemaConverter should use one-based indexing like Iceberg …

### PR DESCRIPTION
**Pull request by boroknagyz**
…does

### CODE REVIEW

**Comment by rdblue** [comment]
I think that this change is fine, but you should be able to use any IDs that you choose so it isn't really a functional change. IDs are reassigned when we create an Iceberg table anyway, so they're for internal consistency. The IDs produced here shouldn't really matter.

**Comment by pvary** [comment]
@rdblue: We have a corresponding change in the Hive code where during the migration of an external Hive table to Iceberg table we would like to set the "schema.name-mapping.default", so Impala could read the migrated table.

We can do in a different way:
- When Iceberg rewrites the schema, it should rewrite the `schema.name-mapping.default` value too - This might be a more general solution than depending on the Hive schema generation creating the same ids as the Iceberg schema generation. On the other hand I am not sure this worth the added complexity.

What are your thoughts Ryan?

**Comment by rdblue** [comment]
@pvary, it sounds like what you're saying is that you're generating a schema, then a name mapping, and then creating a table and want the table schema to match the name mapping. I think it makes the most sense to create the table, then base the name mapping on the schema, and then add it to the table. That way you don't rely on the IDs that you pass into create table -- the IDs passed in are reassigned and we make no guarantees about them.

**Comment by pvary** [comment]
> @pvary, it sounds like what you're saying is that you're generating a schema, then a name mapping, and then creating a table and want the table schema to match the name mapping. I think it makes the most sense to create the table, then base the name mapping on the schema, and then add it to the table. That way you don't rely on the IDs that you pass into create table -- the IDs passed in are reassigned and we make no guarantees about them.

Wouldn't this create a transiently invalid table? Also this would create an extra write to the S3 as we need to create a second metadata file.

Maybe some other way to provide the mapping would be better.

**Comment by boroknagyz** [comment]
Another thing is that you can create a partitioned Iceberg table in Hive by setting the table property 'iceberg.mr.table.partition.spec':
https://github.com/apache/hive/blob/392c4f259ad57d746280790a21e560319ace4c8d/iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q#L11

To define this property, the user has to be aware of details of the Iceberg specification, i.e. field ids, source ids, and so on. Without this change the user would need to use different ids than the ids assigned by Iceberg later, which I think can be very confusing.

**Comment by boroknagyz** [comment]
The HiveSchemaConverter in the Hive repo already have this change:
https://github.com/apache/hive/blob/4b7a948e45fd88372fef573be321cda40d189cc7/iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java#L50

Can we move forward with this PR? Or should we do things differently?

**Pull request closed without merging**
