### PR TITLE
Core: Validate transforms while building partition type

### PR DESCRIPTION
**Pull request by aokolnychyi**
Until we store the output type of transforms, we should fail building the partition type if we hit `UnknownTransform`.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @RussellSpitzer @szehon-ho @jackye1995 @yyanyy @kbendick @karuppayya @rdblue

**Review by kbendick — APPROVED** [review]
This looks good to me overall. A few questions for my own understanding.

A few questions:
1) I'm assuming you're using this subset of metadata tables because they're partitioned?
2) Is there a way to add a test against a table itself (and not just the metadata tables)?

**Comment by aokolnychyi** [comment]
@kbendick, this is a follow-up to #2936 where I added `Partitioning#partitionType`. It is only used within these metadata tables that I added tests for. W.r.t. reading the table itself, we have `TestForwardCompatibility` that already covers writing and reading to a table with unknown transforms.

**Review by yyanyy — APPROVED** [review]
I guess I'm not familiar with the context, is this case only going to be hit when there's a new writer that commit partition spec to the table that contains a new transform, and the metadata tables associated with the table is read by the old reader which does not recognize this transform; and we are updating the logic for this old reader to fail gracefully?

**Comment by aokolnychyi** [comment]
@yyanyy, that's exactly the use case.

**Review by jackye1995 — APPROVED** [review]
this also looks good to me

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @kbendick @yyanyy @jackye1995!

**Pull request merged**
