### PR TITLE
Removes Flink version 1.16

### PR DESCRIPTION
**Pull request by rodmeneses**

### CODE REVIEW

**Comment by rodmeneses** [comment]
cc: @pvary @nastra please take a look. Thanks

**Review by nastra — APPROVED** [review]
LGTM, thanks

**Comment by pvary** [comment]
Thanks for the PR @rodmeneses and @nastra for the review!

**Comment by Fokko** [comment]
Thanks @rodmeneses for working on this. Can you [update the table here](https://github.com/apache/iceberg/blob/main/site/docs/multi-engine-support.md#apache-flink) as well?

**Comment by rodmeneses** [comment]
@Fokko Thanks for the reminder. Here's the PR: https://github.com/apache/iceberg/pull/10155

**Pull request merged**
