### PR TITLE
Spark 3.4: Tests for coalescing small writing tasks

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds tests to verify AQE can coalesce small writing tasks.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @singhpk234 @amogh-jahagirdar @jackye1995 @flyrain @RussellSpitzer @szehon-ho @rdblue

**Review by szehon-ho — APPROVED** [review]
Test looks good, can you add what pr this is testing?

**Comment by aokolnychyi** [comment]
This was automatically consumed by removing our custom logic for writes in PR #7443.

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @szehon-ho!

**Pull request merged**
