### PR TITLE
Fix Objects.requireNonNull usages

### PR DESCRIPTION
**Pull request by findepi**
Per project code style, Preconditions.checkNotNull should be used
instead.

### CODE REVIEW

**Comment by findepi** [comment]
> Looks good to me, is this something we have in our Static Analysis rules?

i don't think so. That's something reviewers point out during review process.

**Comment by RussellSpitzer** [comment]
> > Looks good to me, is this something we have in our Static Analysis rules?
> 
> i don't think so. That's something reviewers point out during review process.

We should probably add that as well then, we can have checkstyle automatically fail any code which adds it like we do with usages of unshaded guava.

**Comment by findepi** [comment]
Good idea, let's do this. I don't plan on doing this within this PR though.

**Comment by RussellSpitzer** [comment]
Uh looks like we already had some :) 
```
Error: eckstyle] [ERROR] /home/runner/work/iceberg/iceberg/nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java:53: Use Preconditions.checkNotNull(Object, String). [RegexpSinglelineJava]
```

**Comment by RussellSpitzer** [comment]
https://github.com/apache/iceberg/issues/4613

**Comment by RussellSpitzer** [comment]
Just waiting on tests here

**Review by kbendick — APPROVED** [review]
lgtm

**Pull request merged**
