### PR TITLE
[Parquet]Fix RemoveIds change parquet repeatedElement name

### PR DESCRIPTION
**Pull request by zhongyujiang**
https://github.com/apache/iceberg/pull/3605#issuecomment-980645315
The RemoveIds won't keep the original custom name of repeatedElement of list/map type passed to it, instead uses a default name in new Parquet version. This PR fixed it.@rdblue can you help review this pr? Thanks!

### CODE REVIEW

**Comment by rdblue** [comment]
@zhongyujiang, what is the problem caused by this?

**Comment by kbendick** [comment]
@zhongyujiang could you update the PR description to further clarify what problem this is solving? It's hard to to tell when it's linked via a comment if we weren't involved in the initial comment discussion.

**Comment by rdblue** [comment]
This is only called from test code, so I think the motivation was to speculative since other classes had similar updates. I don't think that we should move forward with this since it isn't actually used.

What you could do instead is move this into src/test/java.

**Comment by zhongyujiang** [comment]
> This is only called from test code, so I think the motivation was to speculative since other classes had similar updates. I don't think that we should move forward with this since it isn't actually used.

I didn't notice that this is only used in test, and no, I am not speculating. If you read this [issue](https://github.com/apache/iceberg/issues/3604) and this [pr](https://github.com/apache/iceberg/pull/3605), you can find that I found the problem of ApplyNameMapping change custom parquet schema before another merged pr, I checked other classes extend ParquetTypeVisitor and found RemoveIds has the same problem. I fixed both in this [pr](https://github.com/apache/iceberg/pull/3605), but no one reviewed. Yesterday I found the issue of ApplyNameMapping is solved in another pr and already merged, so I closed my last pr and extracted the part of RemoveIds here. That's my  motivation.

**Pull request closed without merging**
