### PR TITLE
ORC: Upgrade to 1.7.6

### PR DESCRIPTION
**Pull request by williamhyun**
Apache ORC 1.7.6 is the latest version of ORC which will bring the following bug fixes:

https://orc.apache.org/news/2022/08/17/ORC-1.7.6/
https://github.com/apache/orc/releases/tag/v1.7.6

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

**Comment by dongjoon-hyun** [comment]
cc @aokolnychyi , @RussellSpitzer , @kbendick

**Review by aokolnychyi — APPROVED** [review]

**Comment by aokolnychyi** [comment]
Thanks, @williamhyun @dongjoon-hyun!

**Comment by kbendick** [comment]
Thanks @williamhyun @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you so much, @aokolnychyi and @kbendick !

**Pull request merged**
