### PR TITLE
Spark 3.3: Fix comment formatting

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR fixes auto formatting for some existing comments that look weird after applying Spotless.

### CODE REVIEW

**Review by amogh-jahagirdar — APPROVED** [review]
Looks good to me @aokolnychyi , there are a few places with awkward commenting formatting like this throughout the library as well, so I think I'll also raise PRs to address them.  I wonder if there's something at the spotless level we can configure so the comment formatting maximizes line length usage more. It seems more ideal if spotless tooling can handle it for us.

**Review by Fokko — APPROVED** [review]
Thanks for cleaning this up @aokolnychyi

**Comment by aokolnychyi** [comment]
> I wonder if there's something at the spotless level we can configure so the comment formatting maximizes line length usage more. 

Yeah, it would make sense to explore but I am also afraid purely auto formatting may be suboptimal in some cases. Let me know once you have PRs for other parts. I think it is better to make them targeted vs one giant PR.

**Comment by aokolnychyi** [comment]
Thanks, @amogh-jahagirdar @Fokko!

**Pull request merged**
