### PR TITLE
Update README local build instructions

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by jackye1995** [comment]
I think this skips checkstyle which is quite important, I would personally prefer to just exclude tests like what Russell suggested, `-x test -x testSpark31 -x integrationTest -x spark31IntegrationTest`, not sure what others think.

**Comment by findepi** [comment]
i agree with you @jackye1995 that this would be better, provided it skips all the tests.

**Comment by szehon-ho** [comment]
I think there is still value for me to add this :). should we open a new PR with @jackye1995's suggestion?

**Comment by jackye1995** [comment]
Yeah, let me do that

**Comment by jackye1995** [comment]
I will merge it once the CI steps are completed.

**Pull request closed without merging**
