### PR TITLE
Spark: Bump Spark 3 version to 3.1.1

### PR DESCRIPTION
**Pull request by leoluan2009**
Upgrade spark 3 version to 3.1.1

### CODE REVIEW

**Comment by leoluan2009** [comment]
cc @Fokko @rdblue  can you help to review this pr? thanks

**Comment by leoluan2009** [comment]
Retest please

**Comment by rdblue** [comment]
@rymurr is currently looking into the build error. We'll need to wait for that to be fixed, unfortunately.

**Comment by rymurr** [comment]
> @rymurr is currently looking into the build error. We'll need to wait for that to be fixed, unfortunately.

this is being tracked at #2462

**Comment by leoluan2009** [comment]
Retest please

**Comment by leoluan2009** [comment]
@rdblue  Can you give some help for how to trigger a retest for this pr?

**Comment by pan3793** [comment]
> @rdblue Can you give some help for how to trigger a retest for this pr?

You can push empty commit to trigger CI

**Comment by Fokko** [comment]
@leoluan2009 Rebasing against latest master would be best :)

**Comment by leoluan2009** [comment]
@pan3793 @Fokko  thanks for your suggestion

**Comment by openinx** [comment]
Closed via https://github.com/apache/iceberg/pull/2512

**Pull request closed without merging**
