### PR TITLE
S3 InputsStream: Reopen connection on Connection Reset

### PR DESCRIPTION
**Pull request by shanielh**
This commit aims to fix issue #10340 where a connection reset is thrown from Apache HTTP Client (even when Keep Alive is set to true)

### CODE REVIEW

**Comment by singhpk234** [comment]
weren't we thinking of fixing this by retrys in the broader level https://github.com/apache/iceberg/pull/10433 ?

**Comment by shanielh** [comment]
> weren't we thinking of fixing this by retrys in the broader level #10433 ?

Haven't seen #10433 since it wasn't connected to the issue :( , note that this fix only fixes reading from a stream that was closed due to connection reset (which happens when you idle stream for a long period) and doesn't add retry mechanism over existing retry mechanisms of AWS SDK when calling SDK requests (I.e read tail and read specific byte range)

**Comment by amogh-jahagirdar** [comment]
@shanielh Sorry about missing to link the issue on #10433, that's totally my bad. As @singhpk234 said, that PR should address the issue you're seeing here. I'll be revisiting the PR this week.

Although one interesting thing about this PR is that you're retrying SocketException, which I should also be retrying on my PR (currently retrying SocketTimeoutException for client side connection reset, but SocketException can occur and be retried for server side).

**Comment by shanielh** [comment]
> @shanielh Sorry about missing to link the issue on #10433, that's totally my bad. As @singhpk234 said, that PR should address the issue you're seeing here. I'll be revisiting the PR this week.
> 
> Although one interesting thing about this PR is that you're retrying SocketException, which I should also be retrying on my PR (currently retrying SocketTimeoutException for client side connection reset, but SocketException can occur and be retried for server side).

No worries, I see this PR is still on draft, any chances to look @ my PR as I validated and it fixes an issue in real world situation where I read a long partition file and taking a long sleep between row groups, before this PR, when getting to process the second row group I get "SocketException".

What is the expected time to merge #10433?

**Pull request closed without merging**
