### PR TITLE
Parquet: deprecate Decimal Metadata usage in favor of DecimalLogicalTypeAnnotation

### PR DESCRIPTION
**Pull request by slfan1989**
The code has some deprecated methods about parquet, this pr will fix it.

The code has the following usage:

```
DecimalMetadata decimal = primitive.getDecimalMetadata();

/**
 * @deprecated use {@link org.apache.parquet.schema.LogicalTypeAnnotation.DecimalLogicalTypeAnnotation}
 * with proper precision and scale parameters instead
 */
@Deprecated
public class DecimalMetadata {
...
}
```

This pr will use the new recommended method instead of the deprecated method.

### CODE REVIEW

**Comment by slfan1989** [comment]
@Fokko Can you help review this pr? Thank you very much!

**Comment by slfan1989** [comment]
@Fokko @jackye1995 Can you help review this pr? Thank you very much!

**Review by jackye1995 — COMMENTED** [review]
overall looks good to me, thanks for doing the fix! 

Can we just use 1 line instead of creating a new variable? something like

```
LogicalTypeAnnotation.DecimalLogicalTypeAnnotation decimal =
                (LogicalTypeAnnotation.DecimalLogicalTypeAnnotation)
                primitive.getLogicalTypeAnnotation();
```

**Review by jackye1995 — APPROVED** [review]
Looks good to me!

**Comment by slfan1989** [comment]
> Looks good to me!

@jackye1995 Thank you very much for your help in reviewing the code!

**Comment by slfan1989** [comment]
@jackye1995 Can you help to merge this pr into the trunk branch? Thank you very much!

**Comment by jackye1995** [comment]
Typically we require two committers to sign off. I see you requested Fokko for review, let me see if I can find someone else tomorrow if he is not available.

**Comment by slfan1989** [comment]
> Typically we require two committers to sign off. I see you requested Fokko for review, let me see if I can find someone else tomorrow if he is not available.

Thank you for your reply!

**Review by yyanyy — APPROVED** [review]
lgtm!

**Comment by jackye1995** [comment]
Thanks for the work, and thanks for the review @yyanyy !

**Pull request merged**
