### PR TITLE
 Nessie: Fix possible table-metadata loss (backport #8413)

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
PR title need to be updated? It seems to be a backport of https://github.com/apache/iceberg/pull/7641

**Review by dimas-b — APPROVED** [review]

**Comment by nastra** [comment]
why do we need the backport? We only do backports to older branches if we plan to do another release

**Comment by snazy** [comment]
How is it then assured that no important backport falls through the cracks, if a patch-release is scheduled?

**Comment by nastra** [comment]
We only backport if there's a need for a patch release and then ask people to tag PRs for that particular patch release. That being said, the project generally doesn't pro-actively backport PRs to earlier Iceberg version branches.

**Comment by snazy** [comment]
Still feels prone to miss backports. Have you thought about adding labels to matching PRs against master?

**Pull request closed without merging**
