### PR TITLE
Flink: add fixed field type for DataGenerators test util

### PR DESCRIPTION
**Pull request by stevenzwu**
this is a follow-up to PR #6377

### CODE REVIEW

**Comment by stevenzwu** [comment]
@pvary regarding your other comments, I am not sure how to proceed yet.

> Null values

 for null values, would optional primitive types at top level be enough? 

> Edge cases, like year differences based on TZ, or non valid timestamps based on TZ

not very clear

**Comment by pvary** [comment]
> @pvary regarding your other comments, I am not sure how to proceed yet.
> 
> > Null values
> 
> for null values, would optional primitive types at top level be enough?

I would use a schema, where the fields are optional. I would like to test that null primitive values, and null map/list/struct is handled correctly.
Also I have seen cases where the null value inside a struct was causing errors. So I would add either a different test, or one field added to the existing records where the value is null

> > Edge cases, like year differences based on TZ, or non valid timestamps based on TZ
> 
> not very clear

Test  records where the timestamp and the same timestamp in UTC are different years.
Test records where the timestamp is invalid because of the summer time / winter time change - on second thought, I am not entirely sure about this. We might need a quick check if it is possible to do or the java classes will prevent the creation of these timestamps.
Another idea is, very old, or timestamps in the far future. I have seen issues with timestamp before epoch, and also timestamps before the calendar change (before around 1400?). Also I have seen issues with timestamps around year 9999, which moved to 10000 when converted to UTC.

What is the range of the timestamps supported by Iceberg anyways.

That said, I would create 2 sets of test records:
- common tests
- extensive tests - with the edge cases
And run the tests with extensive tests only in specific cases

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Looks reasonable to me, but I don't have context on the rest of the discussion. Feel free to merge when you both are happy with this, @pvary and @stevenzwu.

**Review by pvary — APPROVED** [review]
This is good for the Fixed type. If we want to move forward with the other edge cases, we can add that later

**Pull request merged**
