### PR TITLE
Spark 3.5: Support filtering with buckets in RewriteDataFilesProcedure

### PR DESCRIPTION
**Pull request by manuzhang**
This adds support of filtering with buckets in RewriteDataFilesProcedure. For this support, I add a method `partitionFilter` to the `Scan` interface, which can be submitted in a separate PR if you think it's a good approach.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Why does this need a new api?

**Comment by manuzhang** [comment]
@RussellSpitzer could you please give an example of passing partition(esp. bucket) via filter expression?

**Comment by wangtaohz** [comment]
I can provide you with an example that has been tested, but I'm not sure if it's the best practice.

https://github.com/NetEase/amoro/blob/master/core/src/main/java/com/netease/arctic/utils/ExpressionUtil.java#L61

**Comment by manuzhang** [comment]
@wangtaohz thanks for the example. Will a "native" partition filter be more efficient?

**Comment by manuzhang** [comment]
Implemented by https://github.com/apache/iceberg/pull/8560

**Pull request closed without merging**
