### PR TITLE
Build: remove .java-version file

### PR DESCRIPTION
**Pull request by szehon-ho**
This was added in https://github.com/apache/iceberg/pull/3651, and I would like to propose its removal.  We no longer have Spark 2, which was the only reason Java 8 was set here.

This is actually now the wrong default for jenv users.

### CODE REVIEW

**Comment by szehon-ho** [comment]
@findepi @nastra @RussellSpitzer does it make sense?

**Review by nastra — APPROVED** [review]
I'm ok removing this because I don't use it, but let's see what @findepi thinks

**Comment by szehon-ho** [comment]
In my thought, as [build.gradle](https://github.com/apache/iceberg/blob/master/build.gradle#L58) supports building of all Java versions, it could be a surprise to jenv users that Iceberg overrides the user's global default.  Also i took a brief look at some other projects like Parquet/Spark/Flink/Hive, and didn't see .java-version there.  I think this made sense before when Spark 2 was not built without java8, but now that has been removed and don't see a strong reason to default Iceberg to a specific java version overriding the user's default.  That being said, I can leave this a little bit and see if anyone has strong comments against its removal.

**Comment by aokolnychyi** [comment]
Are there any other modules that are only compiled using JDK 8? Hive? Is that even being used?

I guess the primary benefit of having this file was to force building of all modules, which is helpful to catch compile-time errors after changes in `core`. Given that we changed our deprecation model and added support for quite a bit of Java versions at this point, I see how it may be surprising to have this override. I am OK either way but we need to double check our release scripts to make sure they have proper validation. We still have to use Java 8 there.

**Comment by szehon-ho** [comment]
I think this file is for jenv users only.  There is a explicit check for java version in release:  https://github.com/apache/iceberg/blob/master/deploy.gradle#L21 so we should be fine there as I can see.

**Review by dramaticlly — APPROVED** [review]
LGTM, I use jenv for building iceberg locally and I dont think we need to dictate on java version here

**Comment by szehon-ho** [comment]
Merging, I think there's no strong objection.  If we have some reason in future to must build with a certain Java version, we can put this back.  For now, as Iceberg can be built in many distro using different Java version, this allows more flexibility.

**Pull request merged**
