### PR TITLE
Flink: fix flaky test that might fail due to classloader check

### PR DESCRIPTION
**Pull request by stevenzwu**

### CODE REVIEW

**Comment by stevenzwu** [comment]
see an example of failed test here: https://github.com/apache/iceberg/actions/runs/7091452262/job/19300609355?pr=9212

```
    exception caught while trying to get the future result: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
    	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
    	at org.assertj.core.internal.Futures.assertSucceededWithin(Futures.java:109)
    	at org.assertj.core.api.AbstractCompletableFutureAssert.internalSucceedsWithin(AbstractCompletableFutureAssert.java:400)
    	at org.assertj.core.api.AbstractCompletableFutureAssert.succeedsWithin(AbstractCompletableFutureAssert.java:396)
    	at org.apache.iceberg.flink.source.TestIcebergSourceWithWatermarkExtractor.waitForRecords(TestIcebergSourceWithWatermarkExtractor.java:416)
    	at org.apache.iceberg.flink.source.TestIcebergSourceWithWatermarkExtractor.testThrottling(TestIcebergSourceWithWatermarkExtractor.java:307)
```

**Review by nastra — APPROVED** [review]

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
Thanks for catching and fixing this @stevenzwu !

**Comment by ajantha-bhat** [comment]
I think this is not fully fixed. 

With the latest code, it has failed again
https://github.com/apache/iceberg/actions/runs/7208855885/job/19638664888?pr=9296

cc: @nastra, @stevenzwu, @pvary

**Comment by ajantha-bhat** [comment]
Aah, never mind. We need to backport to other flink version. I will do it now. 

The failure was in 1.16

**Comment by ajantha-bhat** [comment]
@stevenzwu: Looks like the code is already there in 1.16, but still it is failed. Please take a look.

**Comment by stevenzwu** [comment]
@pvary can you follow up?

**Comment by pvary** [comment]
I was originally not able to run the tests multiple times using IntelliJ, but found some issues, and fixed them.
Now I have a test which I was able to run 1000 times from IntelliJ without errors.
Let me prepare the PR

**Pull request merged**
