### PR TITLE
Fix the problem of shadow jar without modifying meta-inf/services at the same time

### PR DESCRIPTION
**Pull request by renshangtao**
#6561 

When I developed ORC encryption, I found that it can be encrypted successfully on IDEA, but failed to execute it in Flink engine.

After troubleshooting, I found that the package path of orc is '/org/apache/iceberg/shaded/org/apache/orc/impl/mask/MaskProvider' but the in the META-INF/services is 'org.apache.orc.impl.mask.MaskProvider'

So when the code is executed to Datamask.Factory.DataMask the ServiceLoader load the Provider.class failed

### CODE REVIEW

**Comment by renshangtao** [comment]
cc @rdblue @openinx

**Comment by nastra** [comment]
@renshangtao thanks for the PR. That will only add/merge the service descriptor files to the final jar, but I don't think it will actually solve #6561 as that service provider will still have `org.apache.orc.impl.mask.MaskProvider` in it. In any case, I think it's still correct to merge the service descriptor files but we need a way to deal with packages that are being relocated.

**Review by nastra — APPROVED** [review]

**Comment by renshangtao** [comment]
@nastra thank you for your reply. After this modification, the code can be executed as expected. I open the runtime jar package, and the class corresponding to shadowjar in META-INF/services has changed to org.apache.iceberg.shaded.org.apache.orc.inpl.maskMaskProvider, which should be correct

**Comment by nastra** [comment]
> @nastra thank you for your reply. After this modification, the code can be executed as expected. I open the runtime jar package, and the class corresponding to shadowjar in META-INF/services has changed to org.apache.iceberg.shaded.org.apache.orc.inpl.maskMaskProvider, which should be correct

oh you're right, it shows up as the relocated name, all good then and still +1 on merging this

**Pull request closed without merging**
