### PR TITLE
Spark 3.5: Add distibuted planning benchmarks

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds local benchmarks for distributed planning.

```
Benchmark                                                                           Mode  Cnt   Score   Error  Units
PlanningBenchmark.distributedPlanningWithMinMaxFilter                                 ss    5   2.232 ± 0.135   s/op
PlanningBenchmark.localPlanningWithMinMaxFilter                                       ss    5   2.264 ± 0.077   s/op

PlanningBenchmark.distributedPlanningWithPartitionAndMinMaxFilter                     ss    5   0.502 ± 0.008   s/op
PlanningBenchmark.localPlanningWithPartitionAndMinMaxFilter                           ss    5   0.481 ± 0.019   s/op

PlanningBenchmark.distributedPlanningWithoutFilter                                    ss    5   3.364 ± 1.577   s/op
PlanningBenchmark.localPlanningWithoutFilter                                          ss    5   2.688 ± 0.514   s/op

PlanningBenchmark.distributedDataLocalDeletesPlanningWithoutFilterWithStats           ss    5  40.808 ± 7.004   s/op
PlanningBenchmark.distributedPlanningWithoutFilterWithStats                           ss    5  42.093 ± 7.437   s/op
PlanningBenchmark.localDataDistributedDeletesPlanningWithoutFilterWithStats           ss    5   8.497 ± 1.381   s/op
PlanningBenchmark.localPlanningViaDistributedScanWithoutFilterWithStats               ss    5   8.239 ± 1.063   s/op
PlanningBenchmark.localPlanningWithoutFilterWithStats                                 ss    5   8.504 ± 0.223   s/op
```

The purpose of this benchmark is to have a way to profile and reduce the overhead in distributed planning. We never expect distributed planning to be faster in this environment as there is no cluster. Distributed planning when column stats must be returned to the driver is slow, as expected. There is a change to default to local planning in such cases as part of #8595. In other cases, the cost of serialization is reasonable.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @amogh-jahagirdar @flyrain @RussellSpitzer

**Comment by RussellSpitzer** [comment]
If these only test the overhead in a local context, are we worried there may be a time where performance in a local context would become worse with a code change but performance in a distributed context would be better?

**Comment by aokolnychyi** [comment]
@RussellSpitzer, these benchmarks can be used to profile local planning too. I was just explaining why distributed planning can't be faster and why the numbers look worse.

**Comment by RussellSpitzer** [comment]
> @RussellSpitzer, these benchmarks can be used to profile local planning too. I was just explaining why distributed planning can't be faster and why the numbers look worse.

Yeah I understand that I was thinking more of the context of comparing changes to Distributed Planning. If Version A gets a score of 10 and Version B gets a score of 9 does that mean something to us if a distributed benchmark of A scores 5 and a distributed benchmark of b scored 15

**Comment by aokolnychyi** [comment]
> Yeah I understand that I was thinking more of the context of comparing changes to Distributed Planning. If Version A gets a score of 10 and Version B gets a score of 9 does that mean something to us if a distributed benchmark of A scores 5 and a distributed benchmark of b scored 15

Probably? However, I would imagine comparing before/after value of the same benchmark to be the primary metric.

**Comment by aokolnychyi** [comment]
@RussellSpitzer, got you. Yeah, we can't benchmark the distributed planning locally for sure. However, it is still beneficial for local profiling. It helped me quite a bit to reduce the overhead.

**Comment by RussellSpitzer** [comment]
SGTM, Just want to make sure we don't have this as the only gatekeeping on perf improvements to Dist Planning

**Review by RussellSpitzer — APPROVED** [review]

**Comment by aokolnychyi** [comment]
@RussellSpitzer, 100%. The biggest issue is usually the speed with which we can fetch the result from other nodes. That can only be tested on a real cluster.

**Pull request merged**
