### PR TITLE
Port #4627 to Flink 1.14/1.15

### PR DESCRIPTION
**Pull request by ConeyLiu**
This PR just ported #4627 to Flink 1.14/1.15.

### CODE REVIEW

**Review by ajantha-bhat — APPROVED** [review]

**Comment by ConeyLiu** [comment]
cc @szehon-ho @pvary @kbendick who reviewed the original pr.

**Comment by pvary** [comment]
@ConeyLiu - was it a clean backport, or we should specifically check some changes which are different from the original fix?

**Comment by ConeyLiu** [comment]
@pvary, just copy the code to those versions, no other changes.

**Comment by pvary** [comment]
@ConeyLiu: Thanks for the PR

**Comment by ConeyLiu** [comment]
Thanks @pvary for merging this and thanks @ajantha-bhat for the review.

**Pull request merged**
