### PR TITLE
Python: Add catalog name to identifiers of tables loaded by Glue and Hive Catalog

### LINKED ISSUE #7935: Python: tables loaded by Glue catalog should have catalog's name as part of their identifier
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

When loading a table stored in the Glue catalog using pyiceberg, the table identifier does not have the catalog's name in its identifier.  See this line of code: https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/glue.py#L169

If you look at DynamoDB's implementation, it adds the catalog name: https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/dynamodb.py#L590

### PR DESCRIPTION
**Pull request by JonasJ-ap**
Fixes #7935

### CODE REVIEW

**Comment by jackye1995** [comment]
I think we also want to do this for Hive? Currently that is also not having the catalog name. Any thoughts?

**Comment by JonasJ-ap** [comment]
> I think we also want to do this for Hive? Currently that is also not having the catalog name. Any thoughts?

+1. Thanks for mentioning it. I was thinking of doing it in a separate PR. But it seems the required changes for both catalogs are small enough to be combined in one. Just updated the PR

**Review by Fokko — APPROVED** [review]
Great catch @JonasJ-ap Thanks for fixing this!

**Comment by Fokko** [comment]
Thanks for noticing @cccs-eric

**Pull request merged**
