### PR TITLE
Update blogs.md

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Add the recent blog about "How not to use Apache Iceberg"

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
@bitsondatadev : we are using this repo for the site now after https://github.com/apache/iceberg/pull/8919 ? 

So, I raised PR here instead of Iceberg-docs repo. Let me know if I need to raise there instead.

**Comment by bitsondatadev** [comment]
@ajantha-bhat, thanks! If you add it here it won't show up on iceberg.apache.org as soon as we merge this PR. The swap will happen with #9520 once we get some consensus on the mailing list. I will bring this up today.

I would just keep this here as this _should_ happen within the next week.

**Comment by ajantha-bhat** [comment]
Thanks for the info.

**Review by bitsondatadev — APPROVED** [review]
Looks good! This was a super informative blog post Ajantha, thanks!

**Comment by ajantha-bhat** [comment]
I think this can be merged now. 

cc: @nastra, @Fokko

**Review by Fokko — APPROVED** [review]
Nice! Thanks @ajantha-bhat for adding the blog, and @bitsondatadev for the review 🙌

**Pull request merged**
