### PR TITLE
Build: Change Spark Versions to Support M1 Processors

### LINKED ISSUE #2794: Build: Support M1 Processors
Currently the integration tests fail on M1 Processor based machines because the Spark version we specify for running integration tests lacks a Snappy with a compatible native-lib (and proper fallback.)

We can fix this by upgrading to a Spark version which has the updated Snappy.
https://issues.apache.org/jira/browse/SPARK-33725
2.4.8 and 3.0.2 (3.1.0 should already be ok)

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Spark's Snappy native lib support is missing M1 support in
our current build. Upgrading Spark upgrades Snappy to a version
which has these native libs. This has no effect on actual runtime
Spark for end users since we do not include Spark with our
release jars.

Fixes #2794

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Anyone with an M1 could you please try this out :) I don't actually have one @karuppayya or @kbendick I think you have the M1 right?

**Comment by kbendick** [comment]
> Anyone with an M1 could you please try this out :) I don't actually have one @karuppayya or @kbendick I think you have the M1 right?
> 
> We just need someone with an m1 to run through the test suite locally, specifically the Spark related tests.

No unfortunately I don't have an M1 @RussellSpitzer. I'll let you know if somebody comes to mind.

**Comment by karuppayya** [comment]
@RussellSpitzer I also dont have M1.

**Comment by KarlManong** [comment]
@RussellSpitzer 
image
It works. Thank u!

**Comment by RussellSpitzer** [comment]
> [build.log](https://github.com/apache/iceberg/files/6788272/build.log)
> @RussellSpitzer
> Ops! Test failed.

Can you see whether snappy-java-1.1.8.2.jar was successfully included? I checked the contents
```
tar -tvf snappy-java-1.1.8.2.jar | grep -Hsi Mac
(standard input):drwxrwxr-x  0 0      0           0 Nov 28  2020 org/xerial/snappy/native/Mac/
(standard input):drwxrwxr-x  0 0      0           0 Nov 28  2020 org/xerial/snappy/native/Mac/aarch64/
(standard input):-rw-rw-r--  0 0      0       71184 Nov 28  2020 org/xerial/snappy/native/Mac/aarch64/libsnappyjava.dylib
```
It has the right native lib in the snappy jar

and when I run the suite it uses this jar

image

**Comment by KarlManong** [comment]
> > [build.log](https://github.com/apache/iceberg/files/6788272/build.log)
> > @RussellSpitzer
> > Ops! Test failed.
> 
> Can you see whether snappy-java-1.1.8.2.jar was successfully included? I checked the contents
> 
> ```
> tar -tvf snappy-java-1.1.8.2.jar | grep -Hsi Mac
> (standard input):drwxrwxr-x  0 0      0           0 Nov 28  2020 org/xerial/snappy/native/Mac/
> (standard input):drwxrwxr-x  0 0      0           0 Nov 28  2020 org/xerial/snappy/native/Mac/aarch64/
> (standard input):-rw-rw-r--  0 0      0       71184 Nov 28  2020 org/xerial/snappy/native/Mac/aarch64/libsnappyjava.dylib
> ```
> 
> It has the right native lib in the snappy jar
> 
> and when I run the suite it uses this jar
> 
> image

Sorry, I ran on the wrong branch.

The fix works.

**Comment by RussellSpitzer** [comment]
Thats good enough for me! Thanks for testing @KarlManong!

**Pull request merged**
