### PR TITLE
Spark: Perform nullability check on metastore and spark instances before invoking stop

### PR DESCRIPTION
**Pull request by sumeetgajjar**
In this PR, we fix `SparkTestBase#stopMetastoreAndSpark`. 

When `SparkTestBase#startMetastoreAndSpark` throws an exception while starting embedded HMS or while creating `SparkSession`, the respective `metastore` or `spark` instance would be null. Thus when `stop` method is invoked on either of those, an NPE is thrown simply adding noise to the logs.

Adding a nullability check before invoking stop to prevent NPE noise in the test logs.

### CODE REVIEW

**Comment by sumeetgajjar** [comment]
Hi @Fokko @nastra @pvary,
Can you please review this PR?

**Review by pvary — APPROVED** [review]

**Comment by sumeetgajjar** [comment]
The check failure is due to unrelated reasons and not because of this change.
```
org.apache.iceberg.spark.TestFileRewriteCoordinator > testBinPackRewrite[catalogName = testhive, implementation = org.apache.iceberg.spark.SparkCatalog, config = {type=hive, default-namespace=default}] FAILED
    org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;
        at app//org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:113)
        at app//org.apache.spark.sql.hive.HiveExternalCatalog.databaseExists(HiveExternalCatalog.scala:225)
        at app//org.apache.spark.sql.internal.SharedState.externalCatalog$lzycompute(SharedState.scala:137)
        at app//org.apache.spark.sql.internal.SharedState.externalCatalog(SharedState.scala:127)
        at app//org.apache.spark.sql.internal.SharedState.globalTempViewManager$lzycompute(SharedState.scala:157)
        at app//org.apache.spark.sql.internal.SharedState.globalTempViewManager(SharedState.scala:155)
        at app//org.apache.spark.sql.hive.HiveSessionStateBuilder.$anonfun$catalog$2(HiveSessionStateBuilder.scala:60)
```

Pushing an empty commit to retrigger the checks.

**Comment by sumeetgajjar** [comment]
Hi @pvary @nastra,
Thanks a ton for the review, can we please merge this PR since it is already approved?

**Comment by pvary** [comment]
@sumeetgajjar: Sorry for the delay! Thanks for the PR

Merge to the master

**Pull request merged**
