### PR TITLE
Docs : Add snapshot incremental read on spark doc

### PR DESCRIPTION
**Pull request by tprelle**
Since https://github.com/apache/iceberg/pull/829 and https://github.com/apache/iceberg/pull/1782 spark support incremental read but I do not found it inside documentation.

### CODE REVIEW

**Comment by coolderli** [comment]
I have tested the incremental read with spark, it doesn't support the v2 table.  If the operation of the start snapshot is not the `append`, it doesn't work.

**Comment by tprelle** [comment]
@coolderli thanks for the feed back. I was testing in spark 2. And i check it's only tested for spark2 So I add that it's currently supported only for Spark 2. I will check why it's not working in spark 3.

**Comment by tprelle** [comment]
@coolderli only append it's currently supported by the code : https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java#L123

**Comment by rdblue** [comment]
@tprelle, the `spark.md` file has been split across several other files in the docs site. We've left it as-is so that existing links continue to function and so that we can move links internal to the site over to the new pages. But the actual documentation should probably be in [`spark-queries.md` instead](https://iceberg.apache.org/spark-queries/).

**Pull request closed without merging**
