### PR TITLE
Spark: Add more tests with multiple subqueries in DELETE

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds more tests with multiple subqueries in DELETE. Previously, some tests defined two views but used only one.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @rdblue @dilipbiswal @mehtaashish23

**Review by rdblue — APPROVED** [review]

**Comment by aokolnychyi** [comment]
The test failures in `TestFlinkTableSink ` seem unrelated to this PR.

**Comment by rdblue** [comment]
You should be able to re-run the checks from the details page. I think anyone with commit privileges should be able to.

**Comment by dilipbiswal** [comment]
LGTM

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @rdblue @dilipbiswal!

**Pull request merged**
