### PR TITLE
Support for pushdown like filter (endsWith and contains)

### PR DESCRIPTION
**Pull request by yabola**
This PR supports pushing down `endsWith` (like %x) and `contains` (like %x%) to Iceberg. The benefits are:
1. Support for early filtering of partition columns in partitioned tables, before this PR iceberg needs to scan the entire table.
2. Support for pushdown agg  under certain scenarios (before `endWiths` or `contains` could not be pushed down, so it could not pushdown agg).
3. Support for filtering files using Parquet dictionaries for regular columns in tables.

Before this PR, iceberg only support startWith.

### CODE REVIEW

**Comment by yabola** [comment]
I have an example of performance comparison.
Table : `p_lineorder_ice`  has partition column `LO_ORDERDATE`.

1. pushdown partition column
   test sql: select * from ice.ssb10.p_lineorder_ice where LO_ORDERDATE like '%01'
   before this pr:
image
  after this pr:
image


2. pushdown agg column
  test sql: select count(1) from ice.ssb10.p_lineorder_ice where LO_ORDERDATE like '%01';
   before this PR:
image
   after this PR:
image

**Comment by amogh-jahagirdar** [comment]
@yabola This is very cool, could we break up the PR though for easier review? Let me take a deeper look at the code before I propose a way to break it up into separate PRs. On the surface though it seems like we should be able to break apart the expression changes in API/Core and then have separate PRs for the file formats and Spark integration?

**Comment by amogh-jahagirdar** [comment]
Also, I'll need to think more if we can actually support this for delete files. If not, this will need to only be applied for CoW tables. For example, for agg pushdown, we don't support MoR tables.

**Comment by yabola** [comment]
> @yabola This is very cool, could we break up the PR though for easier review? Let me take a deeper look at the code before I propose a way to break it up into separate PRs. On the surface though it seems like we should be able to break apart the expression changes in API/Core and then have separate PRs for the file formats and Spark integration?

I will break up my PR. Thanks for your advice.

**Comment by yabola** [comment]
> Also, I'll need to think more if we can actually support this for delete files. If not, this will need to only be applied for CoW tables. For example, for agg pushdown, we don't support MoR tables (well unless it's compacted)

@amogh-jahagirdar I checked the code. When there are delete rows, it won't pushdown agg and I have tested it.
https://github.com/apache/iceberg/blob/5f577f1b9902ffe6181897a439686a31fc81b89a/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java#L244-L247

**Pull request closed without merging**
