### PR TITLE
Docs: Add/Update Snowflake docs to new docs site

### PR DESCRIPTION
**Pull request by scottteal**
@bitsondatadev I just saw your update in the community sync on the new docs. I hope I'm making updates in the right place and don't miss the 1.5.0 release! As quite a bit has changed on Snowflake's Iceberg support and documentation over the past several months, I'm just trying to make sure Iceberg docs link to the latest & accuarate info from Snowflake.

### CODE REVIEW

**Comment by bitsondatadev** [comment]
@scottteal yup! This is the right place. We'll be switching over once we get a vote in on the mailing list.

I'll review shortly but seems correct from my phone.

**Review by bitsondatadev — APPROVED** [review]

**Comment by bitsondatadev** [comment]
I checked the links and text looks good. I'll ask someone else to TAL. Thanks @scottteal!

**Comment by scottteal** [comment]
@bitsondatadev doesn't look like this PR made it into the docs switch. I submitted a new PR editing the correct files post-switch #9669

**Comment by bitsondatadev** [comment]
@scottteal Sorry about that I saw that you added this PR and figured we would just use this. Could you reopen this please?

**Pull request closed without merging**
