### PR TITLE
Add 1.5.1 docs

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
Add 1.5.1 docs similar to https://github.com/apache/iceberg/pull/9929/files

### CODE REVIEW

**Comment by amogh-jahagirdar** [comment]
Hm this should have the same line number delta as #9929 since I just copied the folder and edited 2 lines in that copy, not sure why this is adding 8700 lines instead of 8538. Let me check

**Comment by amogh-jahagirdar** [comment]
Yeah I think we're good, there were 2 commits to the 1.5.0 docs after #9929, and the changes add up.

**Comment by bitsondatadev** [comment]
Yeah, so three main things I checked:
* The view file was added so files add up
* Search index excludes were properly added to avoid duplicates
* The version in `mkdocs.yml` has the versions updated from `latest` -> `1.5.1`

LGTM!

**Review by bitsondatadev — APPROVED** [review]
LGTM!

**Review by Fokko — APPROVED** [review]
Thanks @amogh-jahagirdar and @bitsondatadev

**Pull request merged**
