### PR TITLE
Spark: Add table properties to control UPDATE mode and isolation level

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds table properties to control UPDATE mode and isolation level.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@rdblue @dilipbiswal, could you review this one, please?

**Comment by dilipbiswal** [comment]
LGTM

**Comment by aokolnychyi** [comment]
I am going to merge this one to unblock follow-up PRs. Thanks for reviewing, @dilipbiswal!

**Comment by rdblue** [comment]
+1

**Pull request merged**
