### PR TITLE
Reset Spark Conf for each test in TestCompressionSettings

### PR DESCRIPTION
**Pull request by huaxingao**
When running `TestCompressionSettings#testWriteDataWithDifferentSetting()`, we want to reset the Spark configuration between tests to ensure that previous settings do not influence subsequent ones. For instance, consider the following scenarios:
The first configuration uses:
```
ImmutableMap.of(COMPRESSION_CODEC, "zstd", COMPRESSION_LEVEL, "1")
```
The second configuration uses:
```
ImmutableMap.of(COMPRESSION_CODEC, "gzip")
```
Currently, the configuration does not reset, so the second setting unexpectedly retains the `COMPRESSION_LEVEL` from the first setting, resulting in `COMPRESSION_CODEC, "gzip", COMPRESSION_LEVEL, "1"`. This can lead to unexpected behavior.

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @szehon-ho

**Review by RussellSpitzer — APPROVED** [review]
LGTM and I really appreciate that you have asserts in to make sure the config is in use!

**Review by RussellSpitzer — APPROVED** [review]

**Comment by huaxingao** [comment]
Thanks a lot @RussellSpitzer

**Comment by RussellSpitzer** [comment]
Thank you @huaxingao ! It's always great to fix those hidden bad tests!

**Pull request merged**
