### PR TITLE
Test: Add test for remove orphan files with delete files

### PR DESCRIPTION
**Pull request by szehon-ho**
Simple test for validating remove orphans work with Delete Files, in particular that they do _not_ remove the delete files.

### CODE REVIEW

**Review by RussellSpitzer — APPROVED** [review]
Looks good to me! Thanks for the PR, I'll merge when the tests finish

**Comment by szehon-ho** [comment]
Thanks for the fast review!

**Comment by aokolnychyi** [comment]
LGTM too.

@szehon-ho, could you check whether we have similar tests for expiring snapshots via the `Table` API? It has a different mechanism compared to actions/procedures.

**Comment by szehon-ho** [comment]
sure, will take a look

**Pull request merged**
