### PR TITLE
Spark 3.0: Make SparkCatalog#alterTable conform to TableCatalog interface

### PR DESCRIPTION
**Pull request by wypoon**
Port of #3548 to 3.0.
Fix is due to Xinbin Huang (@xinbinhuang).

### CODE REVIEW

**Comment by wypoon** [comment]
The fix is applicable to Spark 3.0 as well (`TableCatalog#alterTable` is supposed to return the updated metadata).
@RussellSpitzer can you please review? You merged #3548.

**Comment by wypoon** [comment]
cc @kbendick

**Review by kbendick — APPROVED** [review]
This looks good to me.  Since it's a small change and a port, can you do 3.1 and 3.0 in this same PR? As well as 2.4 (assuming it applies there, which I'm sure it does).

**Comment by kbendick** [comment]
Oh and you might consider marking @xinbinhuang as co-author considering they wrote the original PR.

It's just part of the PR comment (if you didn't already know): https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line

**Comment by wypoon** [comment]
> This looks good to me. Since it's a small change and a port, can you do 3.1 and 3.0 in this same PR? As well as 2.4 (assuming it applies there, which I'm sure it does).

I have already created PRs for both 3.1 and 3.0, since I understood that to be the convention.
There is no `SparkCatalog` in 2.4.

**Comment by wypoon** [comment]
Added @xinbinhuang as co-author. Thanks for the tip, @kbendick.

**Comment by kbendick** [comment]
> > This looks good to me. Since it's a small change and a port, can you do 3.1 and 3.0 in this same PR? As well as 2.4 (assuming it applies there, which I'm sure it does).
> 
> I have already created PRs for both 3.1 and 3.0, since I understood that to be the convention. There is no `SparkCatalog` in 2.4.

Ahh I hadn't noticed at the time that there was ready another PR. I found my way to this review via E-mail.

Then no worries. That would just be more work. This looks good.

**Review by kbendick — APPROVED** [review]
Thanks @wypoon! Sorry I didnt notice there was a PR for the other version already.

**Review by rdblue — APPROVED** [review]

**Pull request merged**
