### PR TITLE
Made ParquetConversions and its methods publicly accessible(#2148)

### PR DESCRIPTION
**Pull request by saurabhagas**

### CODE REVIEW

**Comment by rdblue** [comment]
@saurabhagas, why does this need to be public? This is an internal utility class and I don't think that we need to add it to the API.

**Comment by rdblue** [comment]
I'm closing this since there was no reply. Feel free to reopen if you have time to pick it back up.

**Comment by saurabhagas** [comment]
> I'm closing this since there was no reply. Feel free to reopen if you have time to pick it back up.

@rdblue, sorry, this issue fell out of my radar.  I had given the reasoning behind this change in the tracking issue: https://github.com/apache/iceberg/issues/2148 (I've edited the description slightly to help the reader). If you're convinced, please reopen the PR and accept the change.

**Comment by saurabhagas** [comment]
@rdblue, can you check this PR and give your final verdict please? If the change isn't acceptable, I'll close the tracking issue as well. Thanks!

**Comment by rdblue** [comment]
@saurabhagas, I'm not sure there's enough information in the issue to understand why a different method can't be used, or if it is a good idea to expose this. It sounds like you're constructing different schemas and using stats differently, so how much similarity is there? The Parquet values produced by this are specific to Iceberg's object model. If you're building something different from Iceberg then I would say that it makes the most sense for you to have similar code for your use case.

**Comment by saurabhagas** [comment]
Thanks for the reply. Closing the issue.

**Pull request closed without merging**
