### PR TITLE
Bump Spark 2 branch to 2.4.7

### PR DESCRIPTION
**Pull request by Fokko**
Spark 2.4.6 contains some incorrectness bug.

Related https://github.com/apache/iceberg/pull/1386

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Thanks for doing this, perhaps we should get one of those version update bots so we don't have to keep doing these manually?

**Comment by Fokko** [comment]
Yes, that's a good point. For now, I see two issues:

- Not sure if there is something of the self available for Gradle (using the versions.lock).
- Apache doesn't allow to have 3rd parties write access to the repository. Dependabot requires this :(

**Comment by RussellSpitzer** [comment]
Could we have dependabot just work off another repository and submit pr's? Then at least we only have to click merge :)

**Comment by Fokko** [comment]
I don't mind doing it now and then. Also, some other dependencies need some love, such as https://github.com/apache/iceberg/pull/1648

**Comment by rdblue** [comment]
Thanks for the update, @Fokko!

**Pull request merged**
