### PR TITLE
Spark 3.3/3.4: Align RewritePositionDeleteFilesSparkAction filter case sensitivity with Spark case sensitivity

### PR DESCRIPTION
**Pull request by huaxingao**

### CODE REVIEW

**Review by singhpk234 — APPROVED** [review]
LGTM, thanks @huaxingao !

**Review by szehon-ho — APPROVED** [review]
Looks good, I think the title is not the correct spark version right?

**Review by dramaticlly — APPROVED** [review]

**Comment by szehon-ho** [comment]
Merged, thanks @huaxingao , and also @singhpk234 and @dramaticlly for additional review

**Comment by huaxingao** [comment]
Thanks @szehon-ho @singhpk234 @dramaticlly

**Pull request merged**
