### PR TITLE
Move to Hive 2.3.8

### PR DESCRIPTION
**Pull request by Fokko**
Contains Avro 1.10 :)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
It seems that CI fails.

cc @sunchao

**Comment by sunchao** [comment]
Great to see this! I think you will need to specify version for calcite-core as well since it is excluded from hive-exec.

Note Hive 2.3.8 still uses Avro 1.8.2, although it should be compatible with Avro 1.10.

**Comment by Fokko** [comment]
Thanks for pointing out @sunchao. I've added calcite-core as a dependency as well.

**Comment by dongjoon-hyun** [comment]
Thank you for updating.

**Comment by rdblue** [comment]
Why does this need to add Calcite dependencies?

**Comment by rdsr** [comment]
> Great to see this! I think you will need to specify version for calcite-core as well since it is excluded from hive-exec.
> 
> Note Hive 2.3.8 still uses Avro 1.8.2, although it should be compatible with Avro 1.10.

Seems like calcite-druid is only required during `iceberg-mr` testing [calcite-core is already include in test scope]. Instead of adding at compileOnly, I think we should only add calcite druid as a test dep under `iceberg-mr` only

**Comment by Fokko** [comment]
@sunchao Can you shed some light on why calcite has been removed as a dependency from Hive? I haven't been involved in this discussion.

@rdsr Good catch, I've moved them to `testCompile`.

**Comment by sunchao** [comment]
@Fokko it was removed as part of shading Guava- see [HIVE-22126](https://issues.apache.org/jira/browse/HIVE-22126) and [HIVE-23980](https://issues.apache.org/jira/browse/HIVE-23980).

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Looks good. Thanks for catching the test issue, @rdsr!

Thanks for the update, @Fokko!

**Pull request merged**
