### PR TITLE
Upgrade ORC to 1.6.8

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade ORC to 1.6.8 which has the latest bug fixes.
- https://orc.apache.org/news/2021/05/21/ORC-1.6.8/

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @aokolnychyi and @RussellSpitzer ?
The failure looks irrelevant one because this is tested in my GitHub Action without any problem.
- https://github.com/dongjoon-hyun/iceberg/pull/3

**Review by RussellSpitzer — APPROVED** [review]
Lgtm, if the tests fail again I'll take a look

**Comment by dongjoon-hyun** [comment]
Thank you, @RussellSpitzer . At this time, `extra-checks` passed!

**Comment by RussellSpitzer** [comment]
Is this for Spark 3 or Spark 2? We probably need to change this to target apple-0.12 or Apple-0.9 to respectively

**Comment by dongjoon-hyun** [comment]
Thank you!

**Pull request merged**
