### PR TITLE
Spark3.4: Support Aggregate push down for incremental scan

### PR DESCRIPTION
**Pull request by huaxingao**
This back-ports https://github.com/apache/iceberg/pull/10538/ to spark3.4

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @szehon-ho @amogh-jahagirdar

**Review by singhpk234 — APPROVED** [review]
LGTM !

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks @huaxingao !

**Comment by huaxingao** [comment]
Thanks @amogh-jahagirdar @singhpk234

**Pull request merged**
