### PR TITLE
Set black line-length to 130 in tox settings

### PR DESCRIPTION
**Pull request by samredai**
This adds `--line-length` to the black autoformatter and format checker commands in tox.ini

This may cause some open PRs to require rebasing (there's never a good time to change an auto-formatter) but alternatively we can keep this PR open and wait for a dip in open PRs to rebase this PR, run `tox -e format`, and commit the updates.

The first commit [fcddb35](https://github.com/apache/iceberg/pull/4025/commits/fcddb3545a1aa28184d8860a075207cb1a0f2fdc) is the actual change to the formatter, the second commit [66325f4](https://github.com/apache/iceberg/pull/4025/commits/66325f4d7e3a784fca08ae8b8930c7f74476395d) is the result of running `tox -e format` on the project.

### CODE REVIEW

**Review by kbendick — APPROVED** [review]
LGTM

**Comment by rdblue** [comment]
What was the line length without this? Do we need to do this?

**Comment by samredai** [comment]
@rdblue the default for black is 88. From what I've seen, that's usually bumped up to somewhere in the range of 110-130.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
88 seems a bit small to me. Since we should do this when it will introduce as few changes as possible, I'll go ahead and merge. Thanks, @samredai!

**Comment by samredai** [comment]
Thanks @rdblue. I'm going to open a quick follow-up PR to autoformat again. Looks like a PR was merged after I opened this so wasn't caught here!

**Comment by rdblue** [comment]
Thanks!

**Comment by jun-he** [comment]
Thanks @samredai

**Pull request merged**
