### PR TITLE
Support 2-level list and maps type in RemoveIds.

### PR DESCRIPTION
**Pull request by SinghAsDev**

### CODE REVIEW

**Comment by SinghAsDev** [comment]
Hey @rdblue we missed updating this while updating other places like `ApplyNameMapping` to support 2 level lists and maps. Can you help take a look. Thanks!

**Review by puchengy — APPROVED** [review]

**Review by Fokko — APPROVED** [review]
This makes sense to me, should we add a test for this to go over both of the branches of the `if`?

**Comment by SinghAsDev** [comment]
> This makes sense to me, should we add a test for this to go over both of the branches of the `if`?

Thanks for the review @Fokko ! Since this is exactly what we do in `ApplyNameMapping` I was hoping we can avoid additional test. But, do let me know if you feel strongly about it.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Looks good to me. Merged.

**Pull request merged**
