### PR TITLE
Python: Add mkdir to the FileIO

### PR DESCRIPTION
**Pull request by Fokko**
We need this for Hive to create the `/metadata` directory

### CODE REVIEW

**Review by danielcweeks — COMMENTED** [review]
I don't think we want to add directory operations to FileIO.  We've been pretty aggressive about not turning this into a full file system implementation. Is there some other way that we can work around the hive metastore case?

**Comment by Fokko** [comment]
This is mostly for local testing (against my local file system), but I also think we'll need this in the case of HDFS. We could just stub them out for object stores.

**Comment by danielcweeks** [comment]
> This is mostly for local testing (against my local file system), but I also think we'll need this in the case of HDFS. We could just stub them out for object stores. I agree that we should leave potential harmful methods such as `ls` out 👍🏻

Once we put it into the base class, it becomes part of the api though.  Seems like if this is specific to the implementation (e.g. hive metastore) we could just use something directly from there without going through FileIO.

**Comment by rdblue** [comment]
HDFS will automatically create directories. If we want to test locally, we should make a LocalFileIO that has the expected behavior.

**Comment by Fokko** [comment]
> Once we put it into the base class, it becomes part of the api though. Seems like if this is specific to the implementation (e.g. hive metastore) we could just use something directly from there without going through FileIO.

It would be relevant for every catalog that creates the table metadata (the REST catalog does this for us).

> HDFS will automatically create directories. If we want to test locally, we should make a LocalFileIO that has the expected behavior.

Alright, in that case, it doesn't make sense to implement this in the actual code. I'll create a wrapper for any FileIO that will first create the directory.

**Comment by rdblue** [comment]
> Alright, in that case, it doesn't make sense to implement this in the actual code. I'll create a wrapper for any FileIO that will first create the directory.

I don't think I follow. The expectation is that `OutputStream.create` will create the file and any necessary directory structure above it. That's the default behavior for HDFS, S3, and other object stores, so I don't think that we need a generic wrapper. We may need to ensure that directories exist for some URI schemes in specific implementations (maybe arrow doesn't do this?) but I don't think we could make a generic wrapper that does it. At least, I don't see what a generic wrapper would call.

**Pull request closed without merging**
