### PR TITLE
[Spark][MR]: Reuse InputFilesDecryptor

### PR DESCRIPTION
**Pull request by zhongyujiang**
Reuse InputFilesDecryptor in Spark BaseDataReader and MR IcebergInputFormat to reduce code duplication.

### CODE REVIEW

**Comment by flyrain** [comment]
LGTM. A nice refactor, which follows the same approach in #2905. Do we have any test from Spark/Hive side? Also cc @stevenzwu since he is the author of #2905.

**Comment by ggershinsky** [comment]
Nice optimization, LGTM

**Comment by zhongyujiang** [comment]
Thanks for your review and sorry for my late reply.
> Do we have any test from Spark/Hive side?

This just did some small code optimizations so I didn't add the test. What kind of tests do you think should be added? @flyrain

**Comment by flyrain** [comment]
> This just did some small code optimizations so I didn't add the test. What kind of tests do you think should be added? @flyrain 

It's OK to not add tests. I'm just curious that which test covers the changed code.

**Comment by zhongyujiang** [comment]
> I'm just curious that which test covers the changed code.

I think we don't have relevant tests cause encryption hasn't been implemented yet, only PlaintextEncryptionManager at the moment.

**Comment by flyrain** [comment]
> I think we don't have relevant tests cause encryption hasn't been implemented yet, only PlaintextEncryptionManager at the moment.

It is a bit scary, but probably is fine since we've got https://github.com/apache/iceberg/pull/2905 in.

**Review by flyrain — APPROVED** [review]

**Pull request closed without merging**
