### PR TITLE
Explain how to connect a external table.

### PR DESCRIPTION
**Pull request by 911432**
Duplicate with 'flink-getting-started.md' and 'flink-ddl.md'. It looks unnecessary.

### CODE REVIEW

**Comment by 911432** [comment]
@Fokko
flink-ddl.md is explained creating Catalog, DATABASE, Table.
flink-getting-started.md is explaind createing Catalog, Table and inserting table.
#7099

**Comment by 911432** [comment]
@Fokko
flink-ddl.md is explained creating Catalog, DATABASE, Table.
flink-getting-started.md is explaind createing Catalog, Table and inserting table.
#7099 #7215

**Comment by Fokko** [comment]
@911432 this PR affects `docs/flink-connector.md` and I don't see the use of a connector described in the other files you mentioned.

**Comment by 911432** [comment]
@Fokko 
A brief introduction is here.
https://github.com/apache/iceberg/blob/master/docs/flink-getting-started.md
How to connect  a catalog, a database, and a table is described here.
https://github.com/apache/iceberg/blob/master/docs/flink-ddl.md#create-table-like
Insert explaned this link about it.
https://github.com/apache/iceberg/blob/master/docs/flink-queries.md

**Comment by hililiwei** [comment]
We should not delete this doc. It describes the Connector. It has a different emphasis from DDL.md.

**Comment by 911432** [comment]
@Fokko @hililiwei I understood this document as importing an already created external table.
Thanks for the explanation.

**Comment by 911432** [comment]
@Fokko @hililiwei I understand this document as importing an already created external table.
Thanks for the explanation.

**Comment by 911432** [comment]
I'll try extra on the DDL part.

**Comment by 911432** [comment]
@Fokko @hililiwei
I explained connect external table on flink-ddl.md
Please check about it.

**Comment by 911432** [comment]
@Fokko @hililiwei
I explained connecting external tables on flink-ddl.md
Please check about it.

**Comment by 911432** [comment]
@Fokko @hililiwei
I explained how to connect external tables to flink-ddl.md
Please check about it.

**Comment by 911432** [comment]
@Fokko @hililiwei
I explained how to connect external tables.
Please check about it.

**Comment by 911432** [comment]
I couldn't make a manual that fits the changing iceberg.
So I'll just change the link and upload it again.

**Pull request closed without merging**
