### PR TITLE
Bump Nessie to 0.76.0

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Review by dimas-b — APPROVED** [review]

**Comment by jbonofre** [comment]
LGTM, @rdblue @nastra I would like to include for Iceberg 1.5.0. Thoughts ?

**Comment by jbonofre** [comment]
Maybe worth to have a corresponding issue to populate the changelog/release notes. I will do it.

**Review by dimas-b — APPROVED** [review]

**Review by jbonofre — APPROVED** [review]

**Comment by snazy** [comment]
The build-issue (fixed by the 2nd commit) is caused by a Java 21 class file, properly placed in `META-INF/versions/21/com/fasterxml/jackson/...`. There is yet no shadow-plugin version that can deal with Java 21, except a shadow plugin in a different fork. The "original" [shadow-plugin's](https://github.com/johnrengelman/shadow/) been unmaintained since March/April 2023 - there's [a fork](https://github.com/Goooler/shadow) that has changes to support Java 21 and Gradle 8.5+.

**Review by ajantha-bhat — APPROVED** [review]

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @snazy for the PR, and @jbonofre, @ajantha-bhat and @dimas-b for the prompt review 🙌

**Pull request merged**
