### PR TITLE
[wip]: Decouple Hadoop Configuration from FlinkCategoryFactory

### PR DESCRIPTION
**Pull request by xinbinhuang**
fixed: #3117

### CODE REVIEW

**Comment by kainoa21** [comment]
Thanks for this update @xinbinhuang.  I will attempt to do some testing in non-hadoop environments, although I feel like I am likely to run into the same issue that I ultimately hit while attempting to do a similar fix in [this PR](https://github.com/apache/iceberg/pull/4183/files#diff-07827679a9caad4c43e57c09ee1a1d553559856743af8b5f81d00e3220ca81ce) related to `HadoopFileIO` in `FlinkSource.java`?  

Also, was there a particular reason that you did not include updates for Flink 1.14?

**Comment by xinbinhuang** [comment]
> Thanks for this update @xinbinhuang.  I will attempt to do some testing in non-hadoop environments, although I feel like I am likely to run into the same issue that I ultimately hit while attempting to do a similar fix in [this PR](https://github.com/apache/iceberg/pull/4183/files#diff-07827679a9caad4c43e57c09ee1a1d553559856743af8b5f81d00e3220ca81ce) related to `HadoopFileIO` in `FlinkSource.java`?  

Ah sorry, wasn't aware you were working on similar things when I started the PR. Maybe we can merge incorporate them together somehow? 

> Also, was there a particular reason that you did not include updates for Flink 1.14?

No, I started out in 1.15, but realized that KDA only support up to 1.13 currently. Since this fix benefits KDA the most, so I added 1.13 support as well.

**Comment by xinbinhuang** [comment]
@kainoa21 I don't think the parquet error is necessarily an issue related to our fixes. We try to decouple Hadoop s.t. Flink Iceberg application that doesn't use Hadoop related things doesn't require Hadoop on the classpath i.e. Glue. Parquet depends on Hadoop so I would classify it as Hadoop related

**Comment by dyrnq** [comment]
Stare

**Pull request closed without merging**
