### PR TITLE
Core: Extract filePath comparator into it's own class

### PR DESCRIPTION
**Pull request by deniskuzZ**
extracts DataFileFilter#charSeqEquals logic into Comparators#filePath()

### CODE REVIEW

**Review by dramaticlly — APPROVED** [review]
LGTM, tag @flyrain as original author for tail first char sequence comparator

**Review by anuragmantri — APPROVED** [review]
Looks good to me.

**Comment by RussellSpitzer** [comment]
I worry a little bit about moving this into API because i'm not sure it's actually accurate for unicode ordering, I know it's always right for equality (I think). But i'll let @flyrain chime in

**Review by flyrain — APPROVED** [review]
LGTM. Thanks for the refactoring. Sorry for coming late.

**Comment by flyrain** [comment]
Thanks @deniskuzZ for the PR. Thanks @dramaticlly @anuragmantri @RussellSpitzer for the review.

**Pull request merged**
