### PR TITLE
Parquet: avoid premature closing of FSDataInputStream object

### PR DESCRIPTION
**Pull request by velctor**
https://github.com/apache/iceberg/pull/90 adds a finalizer that closes open streams when they are garbage collected. But the `org.apache.iceberg.io.SeekableStream` object is discarded in the `ParquetIO#stream`，and `HadoopStream#finalizer()` is called, which causes the `FSDataOutputStream` to be closed early. This will result in deletefile reading fails with `Failed to open Parquet file ...` or `Stream closed`.

In order to avoid this, add the member variable `icebergHadoopStream `to the `ParquetIO$ParquetInputFile` class and and use it as the parameter of the `ParquetIO#stream`.

### CODE REVIEW

**Comment by rdblue** [comment]
@velctor, can you post the problem that you're seeing? If you have a stream that was closed by the finalizer, how is anything still using it to hit the `Stream closed` error?

**Comment by velctor** [comment]
> @velctor, why do you think that the stream was closed by the finalizer and not by a normal call to `close`?

In order to determine that the file stream closed by the `Finalizer thread` is the same as the stream in the error log, I add 
informations to the log and recompile the relevant jar package. The log is as follows:
```
2021-*-*T14:47:43.211+0800	DEBUG	20210927_064723_00001_ajsi3.1.0-13-103	org.apache.hadoop.fs.FileSystem	Bypassing cache to create filesystem ***00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00227.parquet
2021-*-*T14:47:43.381+0800	DEBUG	Finalizer	org.apache.hadoop.hdfs.DFSClient	close DFSInputStream ***00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00227.parquet  thread name:Finalizer  client:DFSClient_NONMAPREDUCE_373867554_103
2021-*-*T14:47:43.382+0800	DEBUG	20210927_064723_00001_ajsi3.1.0-13-103	org.apache.hadoop.hdfs.DFSClient	DFSInputStream has been closed already ***00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00227.parquet  thread name:20210927_064723_00001_ajsi3.1.0-13-103  client:DFSClient_NONMAPREDUCE_373867554_103
org.apache.iceberg.exceptions.RuntimeIOException: Failed to open Parquet file: ***00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00227.parquet, thread name: 20210927_064723_00001_ajsi3.1.0-13-103
```

In addition, when I applied these changes to iceberg, no related errors were reported after testing.

**Comment by rdblue** [comment]
@velctor, it looks like that is a different finalizer. If you were seeing something that was closed by the Iceberg finalizer, you'd get a stack trace for where the stream was created and it would be no longer referenced. I think in this case, your `FileSystem` is getting closed by the finalizer, which closes all streams associated with it. That's why you get the DFS classes in those logs (I think). Are you not caching the FS instance in Hadoop's FileSystem class?

**Comment by velctor** [comment]
> @velctor, it looks like that is a different finalizer. If you were seeing something that was closed by the Iceberg finalizer, you'd get a stack trace for where the stream was created and it would be no longer referenced. I think in this case, your `FileSystem` is getting closed by the finalizer, which closes all streams associated with it. That's why you get the DFS classes in those logs (I think). Are you not caching the FS instance in Hadoop's FileSystem class?

Oh, the stack information is too long, so I didn’t add it. The relevant complete information is as follows：
```
2021-11-17T16:50:01.177+0800	DEBUG	20211117_084955_00003_gwkuf.1.2-11-160	org.apache.hadoop.fs.FileSystem	Bypassing cache to create filesystem hdfs://***:9000/user/hive/warehouse/SingleTable2/data/00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00533.parquet
2021-11-17T16:50:01.304+0800    WARN    Finalizer       org.apache.iceberg.hadoop.HadoopStreams call finalize by:
        org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.finalize(HadoopStreams.java:125)
        java.base/java.lang.System$2.invokeFinalize(System.java:2125)
        java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87)
        java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)
2021-11-17T16:50:01.304+0800    DEBUG   Finalizer       org.apache.hadoop.hdfs.DFSClient        close DFSInputStream /user/hive/warehouse/SingleTable2/data/00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00533.parquet  thread name:Finalizer  client:DFSClient_NONMAPREDUCE_1873007395_160
2021-11-17T16:50:01.304+0800    DEBUG   Finalizer       org.apache.hadoop.hdfs.DFSClient        call DFSInputStream close by:
        org.apache.hadoop.hdfs.DFSInputStream.close(DFSInputStream.java:660)
        java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
        org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.close(HadoopStreams.java:92)
        org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.finalize(HadoopStreams.java:129)
        java.base/java.lang.System$2.invokeFinalize(System.java:2125)
        java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87)
        java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)
2021-11-17T16:50:01.304+0800    WARN    Finalizer       org.apache.iceberg.hadoop.HadoopStreams Unclosed input stream created by:
        org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:81)
        org.apache.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:56)
        org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
        io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:98)
        io.trino.plugin.iceberg.HdfsInputFile.newStream(HdfsInputFile.java:60)
        org.apache.iceberg.parquet.ParquetIO$ParquetInputFile.newStream(ParquetIO.java:181)
        org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:773)
        org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
        org.apache.iceberg.parquet.ReadConf.newReader(ReadConf.java:218)
        org.apache.iceberg.parquet.ReadConf.<init>(ReadConf.java:74)
        org.apache.iceberg.parquet.ParquetReader.init(ParquetReader.java:66)
        org.apache.iceberg.parquet.ParquetReader.iterator(ParquetReader.java:77)
        org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.hasNext(CloseableIterable.java:173)
        org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:65)
        org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:50)
        org.apache.iceberg.io.CloseableIterable$4$1.hasNext(CloseableIterable.java:108)
        org.apache.iceberg.io.CloseableIterable$ConcatCloseableIterable$ConcatCloseableIterator.hasNext(CloseableIterable.java:161)
        org.apache.iceberg.relocated.com.google.common.collect.Iterators.addAll(Iterators.java:355)
        org.apache.iceberg.relocated.com.google.common.collect.Sets.newHashSet(Sets.java:275)
        org.apache.iceberg.relocated.com.google.common.collect.Sets.newHashSet(Sets.java:258)
        org.apache.iceberg.deletes.Deletes.toPositionSet(Deletes.java:101)
        org.apache.iceberg.deletes.Deletes.toPositionSet(Deletes.java:96)
        org.apache.iceberg.deletes.Deletes.toPositionSet(Deletes.java:88)
        io.trino.plugin.iceberg.TrinoDeleteFilter.getPositionSet(TrinoDeleteFilter.java:146)
        io.trino.plugin.iceberg.IcebergDeleteFilter.<init>(IcebergDeleteFilter.java:44)
        io.trino.plugin.iceberg.IcebergPageSource.<init>(IcebergPageSource.java:62)
        io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:215)   
    io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
        io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
        io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:306)
        io.trino.operator.Driver.processInternal(Driver.java:387)
        io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
        io.trino.operator.Driver.tryWithLock(Driver.java:683)
        io.trino.operator.Driver.processFor(Driver.java:284)
        io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        io.trino.$gen.Trino_359____20211117_084839_2.run(Unknown Source)
        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        java.base/java.lang.Thread.run(Thread.java:829)
2021-11-17T16:50:01.318+0800	DEBUG	20211117_084955_00003_gwkuf.1.2-11-160	org.apache.hadoop.hdfs.DFSClient	DFSInputStream has been closed already /user/hive/warehouse/SingleTable2/data/00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00533.parquet  thread name:20211117_084955_00003_gwkuf.1.2-11-160  client:DFSClient_NONMAPREDUCE_1873007395_160
org.apache.iceberg.exceptions.RuntimeIOException: Failed to open Parquet file: hdfs://***:9000/user/hive/warehouse/SingleTable2/data/00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00533.parquet, thread name: 20211117_084955_00003_gwkuf.1.2-11-160

2021-11-17T16:50:01.318+0800    DEBUG   20211117_084955_00003_gwkuf.1.2-11-160  org.apache.hadoop.hdfs.DFSClient        DFSInputStream has been closed already /user/hive/warehouse/SingleTable2/data/00000-1-b5ccab76-0db2-4f2e-887f-f70b9833cb91-00533.parquet  thread name:20211117_084955_00003_gwkuf.1.2-11-160  client:DFSClient_NONMAPREDUCE_1873007395_16
```

I have added the call stack log of the `finalize `and `close `functions. Together with the stack trace for where the stream was created, we can see that the stream is closed by the Finalizer.

**Comment by rdblue** [comment]
Thanks for the logs! It's always helpful to have the full picture.

I think what's happening is that Trino is extracting the underlying `FsDataInputStream` and using it directly. The fix should be for whatever in Trino is doing that to keep a reference to the `HadoopSeekableInputStream` that Iceberg creates. I wasn't expecting to see `io.trino.plugin` in the stack trace. That tells me that Trino is injecting something that is non-Iceberg. Since Iceberg only accesses the `FsDataInputStream` from the objects that reference it, that's why I thought it wasn't possible for this to be the Iceberg finalizer. But if something gets the underlying stream and discards the Iceberg wrapper, that could cause this problem.

@electrum, can you help us take a look at this problem? Looks like something is getting the underlying stream from Iceberg and keeping a reference past when the reference to the Iceberg stream is garbage collected.

**Comment by electrum** [comment]
We had this problem in Trino previously that @phd3 fixed in https://github.com/trinodb/trino/pull/8504

@velctor It looks like you are using a patched version of the Trino Iceberg connector. Can you share the patch? I don't believe we see this issue today with the current version, so this might be related to the patch. Are you using a version of https://github.com/trinodb/trino/pull/8534 from @jackye1995?

**Comment by electrum** [comment]
Longer explanation of the problem: https://github.com/trinodb/trino/issues/5201#issuecomment-876089214

**Comment by electrum** [comment]
Looking at this again with fresh eyes, the actual problem is that Trino's `HdfsInputFile` delegates to Iceberg's `HadoopInputFile`, which adds the wrapping. We should either subclass it and override the offending method, or simply re-implement the code rather than delegating (since it's fairly trivial).

**Comment by rdblue** [comment]
Thanks, @electrum!

**Comment by velctor** [comment]
@rdblue @electrum Thanks very much! The version that I used is 359, I will merge with the PR trinodb/trino#8504 to test.

**Pull request closed without merging**
