### PR TITLE
Spark 3.1: add_files data loss when SNAPSHOT_ID_INHERITANCE_ENABLED

### PR DESCRIPTION
**Pull request by abmo-x**
Backport for #6818 

Fix for https://github.com/apache/iceberg/issues/6817

When two spark application runs end up with same manifest file name of format "stage-%d-task-%d-manifest" due to same stage/task planning, the add_file procedure ends up overwriting the manifest resulting in data loss

### CODE REVIEW

**Comment by dramaticlly** [comment]
For backport do you want to put everything together in single PR? I guess #6845 and #6846 can merge into one since they are almost identical ?

**Comment by abmo-x** [comment]
@dramaticlly  I want to leave them separate as they are already created.

**Comment by dramaticlly** [comment]
> @dramaticlly I want to leave them separate as they are already created.

I do see some [3.1 change](https://github.com/apache/iceberg/pull/6845/files#diff-af2bc22256d817e0027ad2ef2a3fc73cd25bc94083a0da3c1bad0039ed2170af) in 3.2 PR #6845 . I feel like we shall close this and move all to that and maybe update the title to be more self-explanatory.

**Comment by abmo-x** [comment]
3.1 change was not intended in that pr, I cleaned it up

**Comment by aokolnychyi** [comment]
I see some test failures in 3.1. @abmo-x, could you check?

**Comment by abmo-x** [comment]
@aokolnychyi  fixed all the tests. Thanks

**Review by aokolnychyi — APPROVED** [review]

**Comment by aokolnychyi** [comment]
Thank you, @abmo-x!

**Pull request merged**
