### PR TITLE
Ensure the metadata isn't cleaned up in the case of unknown error

### PR DESCRIPTION
**Pull request by rymurr**
see #2317

### CODE REVIEW

**Comment by rymurr** [comment]
Moving to draft until #2328 is merged

**Comment by rdblue** [comment]
@rymurr, do you want to update this now that #2328 is in?

**Comment by rymurr** [comment]
Hey @rdblue I have a fix in projectnessie/nessie#1016 which should be released early next week. Will update this PR once iceberg has been updated to `0.6.0` of nessie.

**Comment by yyanyy** [comment]
@rymurr I had a similar change for glue catalog and moved some of the methods from hive to common so that they can be reused from different catalogs, in case you are interested: #2402 thanks!

**Comment by rymurr** [comment]
closed in favor of #2515

**Pull request closed without merging**
