### PR TITLE
0.13.1 Cherry-Picks

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
Cherry-pick commits from milestone 0.13.1 https://github.com/apache/iceberg/milestone/17 onto the 0.13.x branch.

This includes these changes:

https://github.com/apache/iceberg/pull/3986
https://github.com/apache/iceberg/pull/4023
https://github.com/apache/iceberg/pull/4024

### CODE REVIEW

**Comment by jackye1995** [comment]
Thanks, waiting for CI result

**Comment by jackye1995** [comment]
Just to confirm, is there anything you change when cherry-picking the commits?

And could you also run AWS integration test as a verification?

**Comment by amogh-jahagirdar** [comment]
The AWS integ tests are passing.

**Comment by amogh-jahagirdar** [comment]
No problem!

**Pull request merged**
