### PR TITLE
Spark: Use nullSafeEval in transform expressions

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR moves our transform expressions to use `UnaryExpression` and `nullSafeEval`.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @rdblue @holdenk @RussellSpitzer @viirya @dilipbiswal

**Review by viirya — APPROVED** [review]
lgtm

**Comment by RussellSpitzer** [comment]
Looks good to me

**Review by dilipbiswal — APPROVED** [review]

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @viirya @RussellSpitzer @dilipbiswal!

**Pull request merged**
