### PR TITLE
Build: Upgrade to gradle 8.8

### LINKED ISSUE #8485: Upgrade to gradle 8.8
### Feature Request / Improvement

Upgrade gradle wrapper to 8.3 version.

### Query engine

None

### PR DESCRIPTION
**Pull request by jbonofre**
Close #8485

### CODE REVIEW

**Comment by jbonofre** [comment]
I forgot to update the checksum, I'm updating now.

**Comment by jbonofre** [comment]
Working on finding a workaround for `revapi` (it doesn't work out of the box with gradle 8.3).

**Comment by jbonofre** [comment]
I'm testing if gradle 8.3 correctly detects change on the API (via `revapi`).

**Comment by jbonofre** [comment]
Re-testing `revapi` on Gradle 8.4 (it should be the same as with Gradle 8.3).

**Comment by jbonofre** [comment]
Unfortunately `gradle-revapi-plugin` doesn't seem super active (https://github.com/palantir/gradle-revapi).

I think it's important to be up to date in regards of Gradle. I will propose a fix to `gradle-revapi`. If the change is not merge and/or it's hard to have a new release, I will propose an alternative plan.

**Comment by ajantha-bhat** [comment]
> Unfortunately gradle-revapi-plugin doesn't seem super active (https://github.com/palantir/gradle-revapi).
I think it's important to be up to date in regards of Gradle. I will propose a fix to gradle-revapi. If the change is not merge and/or it's hard to have a new release, I will propose an alternative plan.

totally agree, worst case we can drop rev-api and find alternatives. But we can't keep gradle out of date. 

cc: @nastra, @Fokko, @danielcweeks, @rdblue

**Comment by jbonofre** [comment]
I'm resuming my work on this one, upgrading to Gradle 8.5 and proposing a fix for revapi. I will share details soon.

**Comment by jbonofre** [comment]
I'm back on this one, sorry for the delay. I will share the gradle 8.5 update + revapi approach.

**Comment by jbonofre** [comment]
As gradle 8.6 is available, I will resume this PR upgrading to 8.6.

**Comment by jbonofre** [comment]
Now upgrading to Gradle 8.7 and proposing alternative approach to revapi plugin.

**Comment by findepi** [comment]
> Close #8485

nit: currently the PR upgrades to 8.6 and the linked issue says 8.7

**Comment by jbonofre** [comment]
@findepi that's correct for the gradle update PR because we want to fix revapi and shadow plugins first. I will update the PR to avoid confusion. Thanks !

**Comment by jbonofre** [comment]
NB: the `gradle-revapi` plugin used in this PR is one in preparation containing the detection fix.

**Comment by jbonofre** [comment]
@nastra as discussed, I identified the problem with `gradle-revapi` plugin:

1. On current `main` branch (with Gradle 8.1.1 and `gradle-revapi` 1.7.0), we can see:

```
Old API: API[archives=[iceberg-common-1.5.0.jar], supplementary=[iceberg-bundled-guava-1.5.0.jar, slf4j-api-1.7.36.jar]]
New API: API[archives=[iceberg-common-1.6.0-SNAPSHOT.jar], supplementary=[slf4j-api-1.7.36.jar, iceberg-bundled-guava-1.6.0-SNAPSHOT.jar]]
```

2. On the `gradle 8` update branch (with Gradle 8.8 and `gradle-revapi` 1.7.0), we can see:

```
Old API: API[archives=[iceberg-common-1.6.0-SNAPSHOT.jar], supplementary=[iceberg-bundled-guava-1.6.0-SNAPSHOT.jar, slf4j-api-1.7.36.jar]]
New API: API[archives=[iceberg-common-1.6.0-SNAPSHOT.jar], supplementary=[slf4j-api-1.7.36.jar, iceberg-bundled-guava-1.6.0-SNAPSHOT.jar]]
```

So the issue is about the old API where it uses `1.6.0-SNAPSHOT` instead of `1.5.0`. I'm investigating and fixing that.

**Comment by jbonofre** [comment]
@Fokko @nastra  As we fixed gradle-revapi plugin, I propose to set 1.6.0 milestone to this PR as it will allow us to upgrade Parquet.

**Review by Fokko — APPROVED** [review]
Thanks for pushing this @jbonofre, took a bit of time and effort, but it looks like we're there 🎉 

I did a quick check and it triggers the revapi: https://github.com/apache/iceberg/actions/runs/9664376603/job/26658848689?pr=10209

**Comment by jbonofre** [comment]
@Fokko great ! I tested locally and it detects the revapi breaking changes cleanly now 😄 Thanks for testing on GH Actions !

**Review by nastra — APPROVED** [review]
LGTM, I also verified locally that RevAPI correctly detects breaking changes

**Pull request merged**
