### PR TITLE
Port #4627 to Spark 2.4/3.1/3.2

### PR DESCRIPTION
**Pull request by ConeyLiu**
This PR just ported #4627 to Spark 2.4/3.1/3.2.

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
What about 1.16?

**Comment by ajantha-bhat** [comment]
> What about 1.16?

I think flink-1.16 and spark-3.3 is handled in the original PR itself. 
https://github.com/apache/iceberg/pull/4627

**Comment by ajantha-bhat** [comment]
nit: we could at least split it into one spark and one flink PR.

**Comment by ConeyLiu** [comment]
Thanks @chenjunjiedada @ajantha-bhat for the review.

> What about 1.16?
It is already done in #4627.

> nit: we could at least split it into one spark and one flink PR or one PR for each version.
OK, let me split it into two patches.

**Comment by chenjunjiedada** [comment]
Well, I thought flink 1.16 was supported recently. Never thought the change was already in it.

**Comment by ConeyLiu** [comment]
cc @szehon-ho @pvary @kbendick who reviewed the original pr.

**Comment by pvary** [comment]
@ConeyLiu - was it a clean backport, or we should specifically check some changes which are different from the original fix?

**Comment by ConeyLiu** [comment]
@pvary same here, just copy, no other changes.

**Comment by pvary** [comment]
@ConeyLiu: Thanks for the PR

**Comment by ConeyLiu** [comment]
Thanks @pvary for merging this and thanks @chenjunjiedada @ajantha-bhat for the review.

**Pull request merged**
