### PR TITLE
Spark：Fix typo form unpartitionedSpec to unPartitionedSpec

### PR DESCRIPTION
**Pull request by felixYyu**
Camel-case should be followed

### CODE REVIEW

**Comment by felixYyu** [comment]
cc @flyrain @szehon-ho @karuppayya @RussellSpitzer @rdblue

**Comment by szehon-ho** [comment]
Thanks for pr, but I think unpartitioned is one word, so to me it's fine (though can wait for others to see)

**Comment by flyrain** [comment]
Yup, it is one word, https://www.merriam-webster.com/dictionary/unpartitioned#:~:text=Definition%20of%20unpartitioned,not%20partitioned%20%3A%20having%20no%20partitions

**Comment by rdblue** [comment]
I agree. Thanks for proposing this, but we should leave it as-is.

**Pull request closed without merging**
