### PR TITLE
Build: verify integrity of gradle distribution

### PR DESCRIPTION
**Pull request by XN137**
docs:
https://docs.gradle.org/current/userguide/gradle_wrapper.html#configuring_checksum_verification

official checksums:
https://gradle.org/release-checksums/

other projects that also do this:
https://github.com/apache/kafka/blob/d8cf47bf28af0b5eb5be8382883e6a331b788e01/gradle/wrapper/gradle-wrapper.properties
https://github.com/apache/calcite/blob/cbbe5701b7f61d7f8df12d314ba5aabf898c1cae/gradle/wrapper/gradle-wrapper.properties

### CODE REVIEW

**Review by hililiwei — APPROVED** [review]
Looks good.

**Review by nastra — APPROVED** [review]
LGTM, should we add a comment to that file with a link to https://gradle.org/release-checksums/ so that whenever somebody updates the gradle version can also directly update the checksum without having to search for that page?

**Comment by kbendick** [comment]
> LGTM, should we add a comment to that file with a link to https://gradle.org/release-checksums/ so that whenever somebody updates the gradle version can also directly update the checksum without having to search for that page?

+1. I'd definitely add a comment with a link. Probbaly even a comment explicitly stating that we need to use the checksum from here on upgrade (though presumably things will break on upgrade and then somebody will find it). But at least having the link is important imo.

**Comment by XN137** [comment]
i was reluctant to do this originally since the gradle wrapper update command rewrites the whole file, but yeah if the upgrading person needs to re-add the checksum property then they should also be able to keep the comment the helps them with their task, so pushed a change that now includes this comment :+1:

**Review by nastra — APPROVED** [review]

**Comment by nastra** [comment]
@rdblue could you review/merge please?

**Comment by rdblue** [comment]
Looks great. Thanks, @XN137!

**Pull request merged**
