### PR TITLE
Core: FixupTypes copied doc info.

### LINKED ISSUE #8415: The comments losted for timestamp field when creating a table with `use-timestamp-without-timezone-in-new-tables`
### Apache Iceberg version

1.3.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

```
SET `spark.sql.iceberg.use-timestamp-without-timezone-in-new-tables`=`true`;

CREATE TABLE local.db.source (
id int COMMENT 'id field',
pt timestamp COMMENT 'ts field'
) USING iceberg partitioned by (days(pt));

DESC local.db.source
```

The result is :

 
image

I found the root cause of the issue, which is that the "doc" part was not copied when copying the field in `org.apache.iceberg.types.FixupTypes#struct()`

### PR DESCRIPTION
**Pull request by baiyangtx**
Closes #8415

### CODE REVIEW

**Comment by Fokko** [comment]
Oof, that's a great catch @baiyangtx. Can you run `./gradlew :iceberg-core:spotlessApply`?

**Comment by baiyangtx** [comment]
Ok, I will try that.

**Comment by baiyangtx** [comment]
Hi, All checks have passed, can this PR be merged? 

Thanks. @Fokko

**Comment by Fokko** [comment]
@baiyangtx Thanks for working on this, I'll merge this so it is part of 1.4.0

**Pull request merged**
