### PR TITLE
Flink: backport PR #10331 and PR #10457 

### PR DESCRIPTION
**Pull request by stevenzwu**

### CODE REVIEW

**Comment by stevenzwu** [comment]
It is a clean back port (complete copy over from 1.19 to 1.17/1.18)

```
➜  iceberg git:(backport-10457) ✗ diff flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/ flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/
➜  iceberg git:(backport-10457) ✗ diff flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/ flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/

➜  iceberg git:(backport-10457) ✗ diff flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/ flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/
➜  iceberg git:(backport-10457) ✗ diff flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/ flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/
```

**Comment by pvary** [comment]
@stevenzwu: Could you please help me understand why are the changes in flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java are needed?

Thanks, Peter

**Comment by stevenzwu** [comment]
> @stevenzwu: Could you please help me understand why are the changes in flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java are needed?

I assume you were asking about the diff btw 1.19 and 1.18. There were change of API in 1.19 for `TypeSerializerSnapshot` interface.
```
1.18
    @Override
    public TypeSerializerSchemaCompatibility<SortKey> resolveSchemaCompatibility(
        TypeSerializer<SortKey> newSerializer) {

1.19
    @Override
    public TypeSerializerSchemaCompatibility<SortKey> resolveSchemaCompatibility(
        TypeSerializerSnapshot<SortKey> oldSerializerSnapshot) {
```

But I did find a bug in the 1.18 implementation that didn't compare the SortOder for compatibility, this is fixed in the latest commit that I just pushed.

Would also need to add a unit test to test the compatibility check. It could be done in this PR or a separate one.

**Review by pvary — APPROVED** [review]

**Comment by stevenzwu** [comment]
thanks @pvary for the review

**Pull request merged**
