### PR TITLE
Workers gets stuck as there is no-coordinator for emitting Start_Commit request in Incremental Cooperative Rebalancing[ICR] Mode

### PR DESCRIPTION
**Pull request by kumarpritam863**
**Few Observations:**

- In the ICR mode "**open**" receives only the "**newly added partitions**", and "**open**" will "**not be called**" by **connect framework** if there are **No New Partitions Assigned** to the **Task**.

- Similarly in case of "**Close**" the Task receives only the "**removed partitions**" but we **blindly** close the "**Co-ordinator**".
- The **coordinator** is created only in case "**open**" is called but in case when a **partition is revoked** and **no partition is added** on the task then only **close** will be called with that **revoked partition** without any **open call**.

**How this is leading to NO-Coordinator Scenario:**

- Consider the case when a partition other than partition ZERO is removed from the leader task and is assigned to some other task.
- In this case a close call on leader will close the Co-ordinator but since this task will not get open call this will not lead to leader-election on this task. 
- As the other task which received the removed task has not received partition zero, leader election on that task will also not lead to that task being elected as leader.

**Let's see this with the below example:**

Initially we had one worker "**W0**" with two tasks "**T0**" and "**T1**" consuming from two partitions of one topic namely "**P0**" and "**P1**", so the initial configuration is:

**W0 -> [{T0,P0}, {T1, P1}]** -> this will elect "**T0**" as the **co-ordinator** as it has "**P0**"

Now another worker "**W1**" joins:-> this will lead to rebalancing on both tasks as well as topic partitions within those tasks.

- Connect Framework will stop T1 on W0.
- This will cause partition level rebalance and partition P1 will be assigned to T0.

State at this point of time:

**W0 -> [{T0,[P0, P1]}]**
**W1 -> []**

Now,
- Connect FrameWork will start the T1 on W1.
- This will again lead to a rebalance at the partition level.

Assume P1 is removed from T0:

- Connect Framework will call "close" call on T0 with Partition P1.
-  This will close the Co-ordinator on T0.
- An "open" call we be made by the Connect FrameWork on T1 with partition P1.
- This will lead to leader-election on T1 but since it is assigned P1, T1 will not be elected as Co-ordinator.

Hence this leads to a No-Coordinator scenario.

### CODE REVIEW

**Comment by kumarpritam863** [comment]
@bryanck @fqaiser94 can we please review this PR. Thanks.

**Comment by kumarpritam863** [comment]
@bryanck @fqaiser94  @ajantha-bhat We are seeing this issue in ICR mode. Above is our analysis as to why it is happening. Can you please review this analysis.

**Comment by bryanck** [comment]
Thanks @kumarpritam863 , I'm trying to understand the problem you are encountering. My understanding is that Connect will call `close()` then `open()` when rebalancing, in which case, the task that is assigned partition 0 will be elected the coordinator.

**Comment by kumarpritam863** [comment]
Thanks @bryanck for the review. In the **Eager** mode, since on any rebalance all the tasks first leave all the partitions that they have and then they rejoin hence in this case it will always be the case that all the task will necessarily get the "Open()" call always and one of them will be elected as leader. But this is not the case in the **Incremental Cooperative Mode (ICR)**. In ICR, on rebalance Connect Framework calculates only the affected partitions and calls open only if the task is assigned any partition other wise that task continues with performing its job with the partitions it already has.

In the [Consumer Coordinator](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L336):
- [Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L378) first the addedPartitions are calculated.
- [Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L385) the revoked partitions are caluculated
- [Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L402) the consumer co-ordinator calls "invokePartitionsRevoked(revokedPartitions)" with only the revoked partitions.
- Once "invokePartitionsRevoked(revokedPartitions)" is called, the call comes to the "[HandleRebalance](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L710)" of WorkerSinkTask which has implemented the Rebalance Listener to listen to all the changes.
- "OnPartitionsRevoked" calls "[onPartitionsRemoved](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L765)" which checks if the "[removedPartitions](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L780)" are empty then it simply returns without calling "close()" on the sink task.
- Similarly in The ConsumerCoordinator calls "[invokePartitionsAssigned(addedPartitions)"](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L425), on which the call lands "[onPartitionsAssigned()](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L712)" of Handle Rebalance of Worker SinkTask.
- The Worker Sink Task "invokePartitionsAssigned" checks [here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L743) if the "added partitions" are empty then this also simply returns without calling "open" on the sink task.

**Comment by kumarpritam863** [comment]
Hi Bryan,

Thank you for the review and for your valuable input. I'd like to clarify the behavior in the different rebalancing modes:

In Eager mode, during any rebalance, all tasks relinquish their assigned partitions and then rejoin, ensuring that each task will receive the Open() call. One task will always be elected as the leader. However, the scenario is different in Incremental Cooperative Rebalancing (ICR) mode. In ICR, the Connect framework only calculates the affected partitions during rebalancing. The Open() call is only made if a task is assigned new partitions; otherwise, the task continues processing its existing partitions.

In the [ConsumerCoordinator](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L336):

[Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L378), the added partitions are calculated.
[Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L385), the revoked partitions are determined.
[Here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L402), the invokePartitionsRevoked(revokedPartitions) method is called, handling only the revoked partitions.
Following this:

The call proceeds to the "[HandleRebalance](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L710)" method in the WorkerSinkTask, which implements the rebalance listener.
The onPartitionsRevoked() method calls "[onPartitionsRemoved](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L765)," and if the "[removedPartitions](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L780)" are empty, it returns without calling close() on the sink task.
Similarly:

In the invokePartitionsAssigned(addedPartitions) call from the ConsumerCoordinator, the process reaches the "[onPartitionsAssigned](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L712)" method within WorkerSinkTask.
If the "added partitions" are empty in the invokePartitionsAssigned method, it returns without calling Open() on the sink task, as seen [here](https://github.com/apache/kafka/blob/1de4f27ec091fdac4f05add43bf38f8c18d90d8a/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSinkTask.java#L743).
I hope this clarifies the behavior. I'd appreciate any further insights or thoughts you might have.

**Comment by kumarpritam863** [comment]
@bryanck I hope the above analysis was clear. If anything else is needed, pleases let me know.

**Pull request closed without merging**
