### PR TITLE
Core: Missed Nested Schema Projection in AllDataFiles Table

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Fix for nested projection missed doing the same change in AllDataFiles table.

Spotted in #2936 by @aokolnychyi

### CODE REVIEW

**Review by aokolnychyi — APPROVED** [review]
Thanks, @RussellSpitzer!

**Comment by aokolnychyi** [comment]
I have a test that checks this in #2936.

**Comment by aokolnychyi** [comment]
Thanks, @RussellSpitzer!

**Comment by RussellSpitzer** [comment]
Thanks! @aokolnychyi

**Pull request merged**
