### PR TITLE
edit NAMESPACE_PROPERTY_KEY to not be a reserved SQL keyword

### PR DESCRIPTION
**Pull request by syun64**
Issue reference:
https://github.com/apache/iceberg/issues/4952

### CODE REVIEW

**Comment by syun64** [comment]
@rdblue 

Hi Ryan! Here's the PR to remediate the ANSI SQL reserved keyword conflict. I am opening the PR through my company email associated account in accordance with Open Source Contribution standards, as mentioned on the issue:
https://github.com/apache/iceberg/issues/4952

**Comment by rdblue** [comment]
Running CI.

**Comment by syun64** [comment]
Hi @rdblue I fixed an issue where one of the sqlStatements was explicitly using "key" instead of NAMESPACE_PROPERTY_KEY.

Now all the tests are succeeding except for this particular one mentioned on this PR:
https://github.com/apache/iceberg/pull/4825


> Task :iceberg-spark:iceberg-spark-3.2_2.12:test

1552 tests completed, 1 failed, 126 skipped

> Task :iceberg-spark:iceberg-spark-3.2_2.12:test FAILED

```
testOlderThanTimestamp
java.lang.AssertionError: Should delete only 2 files expected:<2> but was:<3>
```

**Comment by rdblue** [comment]
@syun64, I just merged the test fix. Running CI on this now. Thanks!

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @syun64!

**Pull request merged**
