### PR TITLE
Spark: add test on fault tolerance during write (transactional write)

### PR DESCRIPTION
**Pull request by HeartSaVioR**
The functionality is obvious as the concept of Iceberg, but it would be still nice to have a simple test on auditing fault-tolerance situation.

### CODE REVIEW

**Review by RussellSpitzer — APPROVED** [review]
Seems like a good thing to have a test for :)

**Review by aokolnychyi — APPROVED** [review]
+1

**Comment by aokolnychyi** [comment]
Thanks, @HeartSaVioR!

**Comment by HeartSaVioR** [comment]
Thanks all for reviewing and merging!

**Pull request merged**
