### PR TITLE
Core: Update httpclient5 for thread interrupt fix

### PR DESCRIPTION
**Pull request by bryanck**
This PR updates the Apache HTTP client from version 5.1 to 5.2.1. The motivation for this is to [include a fix](https://github.com/apache/httpcomponents-client/pull/394) for a potential hang when a thread is interrupted. Some query engines such as Trino will interrupt threads in some cases, which could cause a hang in the REST catalog or S3 signer.

### CODE REVIEW

**Review by danielcweeks — APPROVED** [review]

**Review by amogh-jahagirdar — APPROVED** [review]
Nice find and fix in the http client library @bryanck !

**Review by singhpk234 — APPROVED** [review]
Awesome find and fix, Thanks @bryanck !

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing

**Review by ajantha-bhat — APPROVED** [review]

**Review by Fokko — APPROVED** [review]
LGTM, thanks @bryanck for catching and fixing this. Thanks @nastra, @danielcweeks, @ajantha-bhat, @singhpk234 and @amogh-jahagirdar for the review 💯

**Pull request merged**
