### PR TITLE
Spark 3.2: Minor updates to ChangelogIterator

### PR DESCRIPTION
**Pull request by flyrain**
Backport #6898 to Spark3.2. cc @aokolnychyi @RussellSpitzer

### CODE REVIEW

**Comment by flyrain** [comment]
The error is NOT related
```
      > java.lang.Error: Error was thrown while processing /home/runner/work/iceberg/iceberg/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
```

**Review by aokolnychyi — APPROVED** [review]
Pending tests.

**Comment by aokolnychyi** [comment]
Thanks, @flyrain!

**Comment by flyrain** [comment]
Thanks @aokolnychyi for the review.

**Pull request merged**
