### PR TITLE
[WIP] Major docs site refactoring

### PR DESCRIPTION
**Pull request by samredai**
new_iceberg_docs

This is a major restructuring of the apache iceberg docs site. Here are the main highlights.

- Meta sections such as Roadmap, Community, Blogs, etc have been moved a static set of links in the top right of the top navbar
- Main navigation has been repositioned from the top navbar to a left navbar and stays static as you navigate through the site
- Java API and Python API have been broken out into their own top level sections
- Versioned docs
  - Docs are now organized in a directory based way that can be versioned
  - The current PR will start with version `0.12.0` and the readme includes how to add docs for a new version
  - A drop down version selector exists at the top nav bar
  - When viewing older versions, a warning shows at the top with a link to the same page in the current latest version
- Search
  - a search bar has been added to the top right and searche results are contained to only the latest version

To try out the site locally, clone the repo, checkout this commit, and run `mkdocs serve`

### CODE REVIEW

**Comment by openinx** [comment]
@samredai  Have we already changed the official apache iceberg document site to the latest version ? 

There seems be some problem in my page: 
image

And the browser debug says: 

```
DevTools failed to load source map: Could not load content for https://iceberg.apache.org/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by samredai** [comment]
@openinx looks like you just need to clear your cache (or F12 in chrome and disable cache on the network tab then refresh the page once). GitHub pages has a 10 minute cache by default and but some browsers cache this more aggressively.

**Comment by samredai** [comment]
@jackye1995 what are your thoughts on moving the docs out to their own iceberg-docs repo? The docs deployment script is very simple (~2 commands). I wouldn't want to add too much complexity there (just yet) to add versioned docs but I do agree that having the massive set of html files in the repo interferes with the local IDE experience.

If we separate out the docs to a separate repo, we can then maintain a single copy of the docs in the site directory on the master branch here. For each iceberg release, we could copy that into a directory in the iceberg-docs repo named after the version. We can also do some simple redirects to allow a `/latest/` path.

This also allows us to add more bonafide docs versioning (such as your suggestion) without creating too much noise in the main iceberg repo.

**Comment by samredai** [comment]
Closing this for now. The discussion should continue over in this issue: https://github.com/apache/iceberg/issues/3616

**Pull request closed without merging**
