### PR TITLE
Flink: Backport #6614 to Flink 1.15  

### PR DESCRIPTION
**Pull request by xuzhiwen1255**
backport....

### CODE REVIEW

**Comment by stevenzwu** [comment]
@xuzhiwen1255 I assume you checked the diff that there is nothing related to this change, right?
```
 git diff --no-index  flink/v1.15/flink/src/ flink/v1.16/flink/src
```

**Comment by xuzhiwen1255** [comment]
@stevenzwu Yes, but I found a problem,  abc forgot to implement the Cloneable interface.

**Comment by xuzhiwen1255** [comment]
Do I need a separate pr to fix this interface problem?

**Comment by xuzhiwen1255** [comment]
@stevenzwu I mentioned a pr #7168 that fixes missing code in #6614 .

**Comment by stevenzwu** [comment]
@xuzhiwen1255 the hotfix has been merged

**Comment by xuzhiwen1255** [comment]
Thanks @stevenzwu  , I've checked the diff and no extraneous code is involved.

**Review by stevenzwu — APPROVED** [review]

**Pull request merged**
