### PR TITLE
Nessie: Bump Nessie dependencies from 0.57.0 to 0.58.1

### PR DESCRIPTION
**Pull request by dimas-b**
CC: @nastra , @snazy , @ajantha-bhat

### CODE REVIEW

**Review by nastra — APPROVED** [review]
LGTM, thanks @dimas-b

**Comment by dimas-b** [comment]
@nastra : A number of CI jobs fails, but GH does not show any info about the failures (maybe just for me?)... WDYT?

**Comment by ajantha-bhat** [comment]
>  @nastra : A number of CI jobs fails, but GH does not show any info about the failures (maybe just for me?)... WDYT?

Same for me too. Maybe we need to re-trigger the jobs.

**Comment by nastra** [comment]
GH actions seem to be having some issues currently

**Review by Fokko — APPROVED** [review]

**Pull request merged**
