### PR TITLE
[1.4.x] AWS: avoid static global credentials provider which doesn't play well with lifecycle management (#8677)

### PR DESCRIPTION
**Pull request by nastra**
This backports #8677 to 1.4.1

### CODE REVIEW

**Comment by rdblue** [comment]
@nastra and @singhpk234, is this safe for a patch release? It seems like a behavior change that would only be safe if the behavior is always the same when creating multiple credentials providers.

**Comment by nastra** [comment]
> @nastra and @singhpk234, is this safe for a patch release? It seems like a behavior change that would only be safe if the behavior is always the same when creating multiple credentials providers.

It appears that multiple people ran into this issue with 1.3.1 on [Slack and on the ML](https://lists.apache.org/thread/1nwb11v1qn1nr86stofkvqlb32fp0q9d). I don't think those people have an easy way to resolve the issue on their own (without building a custom jar with the proposed fix)

**Comment by stevenzwu** [comment]
> would only be safe if the behavior is always the same when creating multiple credentials providers.

@rdblue I think it is a safe change from a static global singleton to creating new objects for object lifecycle management

**Comment by singhpk234** [comment]
> It seems like a behavior change that would only be safe if the behavior is always the same when creating multiple credentials providers.

checked the DEFAULT_CREDENTIALS_PROVIDER singleton supplied earlier, it will be same as that what we would be creating now via `DefaultCredentialsProvider.builder().build()` as far a creds looks up is concerned (no behaviour change), never the less we have been creating a new cred provider instance when ever we supply accessKey or accessKeyId via `StaticCredentialsProvider.create(AwsCreds)`. Considering all of above we should be good imho :) !!

**Comment by nastra** [comment]
Thanks everyone for the feedback. I'll go ahead and include this in the 1.4.1 RC

**Pull request merged**
