### PR TITLE
Hive: Fix using Date type as partition field

### PR DESCRIPTION
**Pull request by lurnagao**
When using date/timestampas a partition field, it will throw IllegalStateException: Not not instance of...

for example:
`create table iceberg_test(id int, name string) partitioned by (dt date) stored by 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler';`

then insert into :
`insert into iceberg_test values(1, 'xxx', '2023-01-01');`

The exception is as follows:
`java.lang.IllegalStateException: Not an instance of java.lang.Integer: 2023-01-01 at org.apache.iceberg.data.GenericRecord.get(GenericRecord.java:123) at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:71) at org.apache.iceberg.Accessors$PositionAccessor.get(Accessors.java:58) at org.apache.iceberg.PartitionKey.partition(PartitionKey.java:104) `

We will need to wrapping the record into an InternalRecordWrapper

### CODE REVIEW

**Comment by Fokko** [comment]
@lurnagao thanks for raising this PR 👍🏻 Would it be possible to add a unit test? To ensure we don't break this in the future.

**Comment by lurnagao** [comment]
> @lurnagao thanks for raising this PR 👍🏻 Would it be possible to add a unit test? To ensure we don't break this in the future.

Hi, I have now added a unit test.

**Comment by lurnagao** [comment]
> @lurnagao I'm seeing some odd test failures, could you pull in latest master?

Hi, I'm sorry for making a very foolish mistake in this pull request，so I resubmitted a request in [https://github.com/apache/iceberg/pull/7359](url)

May I trouble you to take a look at this new pull request？

**Comment by lurnagao** [comment]
closed by [https://github.com/apache/iceberg/pull/7359](https://github.com/apache/iceberg/pull/7359)

**Comment by lurnagao** [comment]
closed by [https://github.com/apache/iceberg/pull/7359](https://github.com/apache/iceberg/pull/7359)

**Pull request closed without merging**
