### PR TITLE
Fix IN predicate performance

### LINKED ISSUE #1588: Don't evaluate IN predicates when it is too expensive
When the number of elements inside IN expressions is huge, evaluating them may actually degrade the performance.

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR fixes the IN predicate performance using hard-coded values.

Resolves #1588.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
I've created this one as a temp solution to the IN predicate issue instead of #1672.

**Comment by aokolnychyi** [comment]
cc @RussellSpitzer @rdblue @shardulm94

**Review by RussellSpitzer — APPROVED** [review]

**Review by rdblue — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
I believe you mean in place of  #1665 but :+1:

**Comment by rdblue** [comment]
+1 when tests are passing. Thanks for splitting this out, I think it will be helpful!

**Comment by aokolnychyi** [comment]
I cancelled the build since Travis did not start it for a while.

**Comment by aokolnychyi** [comment]
I am merging this. Thanks for the review!

**Pull request merged**
