### PR TITLE
[Spark] Add missing Spark 3.1 to JMH configuration

### PR DESCRIPTION
**Pull request by kbendick**
Noticed we don't have Spark 3.1 as a JMH option.

### CODE REVIEW

**Comment by kbendick** [comment]
Once a decision is made with respect to the new Spark naming convention (with Scala versions), https://github.com/apache/iceberg/pull/3624, I'll update this PR to reflect that.

**Review by RussellSpitzer — APPROVED** [review]

**Comment by kbendick** [comment]
Now that we've merged in #3624 , I'll update this to be compatible with that.

**Comment by kbendick** [comment]
After this change, I listed the tasks and could see the 3.1 JMH.

```bash
$ ./gradlew -DsparkVersions=3.1  tasks --all | grep jmh
iceberg-spark:iceberg-spark-3.1_2.12:jmhClasses - Assembles jmh classes.
iceberg-spark:iceberg-spark-3.1_2.12:jmh
iceberg-spark:iceberg-spark-3.1_2.12:jmhCompileGeneratedClasses
iceberg-spark:iceberg-spark-3.1_2.12:jmhJar
iceberg-spark:iceberg-spark-3.1_2.12:jmhRunBytecodeGenerator
...
```

**Comment by kbendick** [comment]
@rdblue @RussellSpitzer should we merge this now that the changes for scala versions have landed?

**Comment by RussellSpitzer** [comment]
When the tests pass I can merge this

**Comment by kbendick** [comment]
> When the tests pass I can merge this

Yeah my bad. Right after I pinged, I rebased it. Should have done it the other way around. Sorry!

**Comment by RussellSpitzer** [comment]
> > When the tests pass I can merge this
> 
> Yeah my bad. Right after I pinged, I rebased it. Should have done it the other way around. Sorry!

I will never forgive you for this.

**Comment by RussellSpitzer** [comment]
Thanks @kbendick , I forgive you now but it was a rough 32 minutes.

**Pull request merged**
