### PR TITLE
Flink: Backport #8553 to v1.15, v1.16

### PR DESCRIPTION
**Pull request by pvary**
Flink: Backport #8553 to v1.15, v1.16

- Clean backport of #8553
- Fix backport differences for #8852 (#8877, #8880)

### CODE REVIEW

**Comment by pvary** [comment]
CC: @nastra, @nk1506 - When backporting changes, please make sure that all of the changes as similar as possible.

After fixing the backport differences caused by previous backports I had a clean backport of #8553 to 1.16.

Flink 1.15 missing a feature, so I had to improvise there. See https://github.com/apache/iceberg/pull/9139/commits/c09aab007ce15dce1df05c8df86fefe6e0bcc9f1

CC: @stevenzwu

**Comment by stevenzwu** [comment]
@pvary can you separate this out as a separate PR?

Fix backport differences for https://github.com/apache/iceberg/pull/8852 (https://github.com/apache/iceberg/pull/8877, https://github.com/apache/iceberg/pull/8880)

**Comment by pvary** [comment]
> @pvary can you separate this out as a separate PR?
> 
> Fix backport differences for #8852 (#8877, #8880)

TBH, I do not really understand your comment here 😞

To decrease the turnaround time, I have created 3 PRs, and you can decide which one we should use to move forward:
- #9146 - #8852 was the original change, and #8877 and #8880 were the backports done. Sadly these backports were not clean backports, resulting in a slightly different code in v1.17/v1.16/v1.15 versions. #9146 is a standalone commit which cleans up the differences, and makes sure that v1.16/v1.15 has the same code as v1.17. The code in v1.17 was used as a master of the changes.
- #9144 - This has 2 commits. The first one (c7b484e31346aaada75188a23e5e6a70ea4325c3) is the same as #9146, the second one (21b3eea789cda091dad5727d2af91eebd0cfce4b) is the backport of the Flink part of #8803. If we accept this one, we can merge the changes without squashing the commits - this way we have a clean history, but we can move forward faster.
- #9145 - This has 3 commits. The first two are the same as #9144, the third one (27333e399e4a6b6e2618229c79c4cdf4d806ced9) is the backport of #8553. If we accept this one, we can merge the changes without squashing the commits - this way we have a clean history, but we can move forward faster.

If someone wants to understand better the contents of the actual backport commit of #8553, the 27333e399e4a6b6e2618229c79c4cdf4d806ced9 is a merge of the clean backport (67d5cdc9ce4ae71cc30dc117e9793827cca0ff8c), and the required v1.15 related fixes (c09aab007ce15dce1df05c8df86fefe6e0bcc9f1) which are needed as Flink v1.15 has a missing feature used by the tests

**Comment by stevenzwu** [comment]
@pvary I meant separate to multiple back port PRs. one PR for one purpose. it is easier to review too.

**Comment by pvary** [comment]
> @pvary I meant separate to multiple back port PRs. one PR for one purpose. it is easier to review too.

Thanks!

**Comment by pvary** [comment]
Merged with specific PRs for the different parts

**Pull request closed without merging**
