### PR TITLE
[Data][Minor] remove useless code

### PR DESCRIPTION
**Pull request by jerqi**
Constant variable EPOCH and EPOCH_DAY are never used, we should remove them

### CODE REVIEW

**Comment by rdblue** [comment]
Running tests.

**Comment by jerqi** [comment]
All tests passed. the pr is ok. cc@rdblue

**Comment by jerqi** [comment]
All tests passed. The pr is ok. cc @rdblue

**Comment by rdblue** [comment]
Thanks for following up, @jerqi! I merged this.

**Pull request merged**
