### PR TITLE
Update ASF DOAP rdf file

### PR DESCRIPTION
**Pull request by ajantha-bhat**
As per https://iceberg.apache.org/releases/

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
cc: @jbonofre

**Review by Fokko — APPROVED** [review]

**Review by jbonofre — CHANGES_REQUESTED** [review]
It's not possible to use list of versions like this.

In order to have multiple release versions, each must be in its own "release" section. Each "Version" entry needs to be in its own "release" section.

**Comment by ajantha-bhat** [comment]
> each must be in its own "release" section

@jbonofre: I just followed Hudi 🙈 
https://github.com/apache/hudi/blob/master/doap_HUDI.rdf

**Comment by ajantha-bhat** [comment]
@jbonofre : Looks like website needs only the latest release info. 
Arrow keeps only the latest release. 
https://github.com/apache/arrow-site/blob/main/arrow.rdf

Shall I update to keep only 1.4.3?

**Comment by jbonofre** [comment]
@ajantha-bhat as you can see on https://projects.apache.org/project.html?hudi only the last release is displayed/parsed :) If they want to list of releases they have to provide several release each with specific version (instead of listing all versions in one release).

I think it's good enough to provide only the latest release (like Arrow is doing). And yes, my bad, I forgot to update when I did 1.4.3 release.

**Review by jbonofre — APPROVED** [review]

**Review by nastra — APPROVED** [review]

**Pull request merged**
