### PR TITLE
[WIP] Spark-3.3: Handle dynamic catalog configurations

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Some catalogs like Nessie supports dynamic catalog configurations (like changing the branch name).
But catalogs obtained from spark always uses the original configuration (from SQLConf) instead of active session configuration. Hence, it needs an update.

Nessie end to end testcases (with Nessie spark extensions) are not maintained in the Iceberg repo. Hence, not added a testcase here. Will be added in the Nessie repo.

original issue from Nessie: https://github.com/projectnessie/nessie/issues/4589

### CODE REVIEW

**Review by rdblue — CHANGES_REQUESTED** [review]
I think this is incorrect.

In Spark, v2 catalogs are tracked in `sparkSession.sessionState.catalogManager`, so the set of catalogs is specific to a session. That's on purpose because you can define catalogs in Spark config when creating a new session.

This attempts to allow a catalog to use the active session instead of the one that created it, which is not correct.

**Comment by ajantha-bhat** [comment]
> I think this is incorrect.
This attempts to allow a catalog to use the active session instead of the one that created it, which is not correct.

@rdblue: I see that other catalogs doesn't support the Dynamic catalog properties. So, the base problem is Nessie supporting configuring reference name dynamically as a spark catalog conf?

Any suggestion to handle this?

**Comment by ajantha-bhat** [comment]
Somehow this problem disappeared.
Iceberg 0.14.0 spark3.2 and spark3.3 doesn't have this issue anymore.

Only spark 3.1 has an issue.

I still need to figure out which PR fixed this.

**Comment by ajantha-bhat** [comment]
Found it. 
Fixed by https://github.com/apache/iceberg/pull/5247 by not using SparkCatalog for the rewriteDataFIles, which was using SQLConf instead of SessionConf for building the IcebergCatalog.

**Pull request closed without merging**
