### PR TITLE
Require Assertions to be statically imported 

### PR DESCRIPTION
**Pull request by findepi**
see https://github.com/apache/iceberg/pull/10500#discussion_r1641210236

### CODE REVIEW

**Comment by findepi** [comment]
currently based on https://github.com/apache/iceberg/pull/10511, https://github.com/apache/iceberg/pull/10512

**Comment by findepi** [comment]
> currently based on #10511, #10512

rebased, no longer the case.

**Comment by nastra** [comment]
This might take a few days to review as I just made it through the first 100 files

**Comment by findepi** [comment]
no worries, thanks for reviewing!
all the static import were added with intellij's "import statically" action
i need to rebase to resolve conflicts with https://github.com/apache/iceberg/pull/10500

**Comment by findepi** [comment]
rebased & updated for https://github.com/apache/iceberg/pull/10500

**Comment by findepi** [comment]
@nastra if this helps, i can split this PR into smaller ones, eg by module.

**Comment by nastra** [comment]
@findepi yeah I think it would make sense to split out the Flink + Spark changes. Everything else can stay in this PR

**Comment by findepi** [comment]
@nastra no problem, extracted https://github.com/apache/iceberg/pull/10531 and https://github.com/apache/iceberg/pull/10532.
I kept those commits here for now, since the last commit adds static code analysis and otherwise wouldn't pass.

**Comment by nastra** [comment]
This can be rebased now, since the other 2 PRs have been merged

**Comment by findepi** [comment]
rebased

**Review by nastra — APPROVED** [review]
LGTM, thanks for cleaning this up

**Comment by findepi** [comment]
thanks for your review @nastra !

**Pull request merged**
