### PR TITLE
Parquet: Release the compressor when calling close in ParquetWriter

### PR DESCRIPTION
**Pull request by hmit**

### CODE REVIEW

**Comment by hmit** [comment]
I discovered this after switching to `ParquetWriter` from iceberg project.
Without this, we see [this log message](https://github.com/rdblue/brotli-codec/blob/master/src/main/java/org/apache/hadoop/io/compress/brotli/BrotliCompressor.java#L249) when using Brotli compression to write data files to iceberg.

**Review by jzhuge — APPROVED** [review]
The commit message should have prefix "Parquet: " instead of "Core: ".

**Review by kbendick — APPROVED** [review]
+1. Good catch @hmit!

I tried to find a place where this could be tested, but there didn't seem to be anywhere that was already testing whether or not things were closed so I think it's fine without it.

**Comment by hmit** [comment]
> +1. Good catch @hmit!
> 
> I tried to find a place where this could be tested, but there didn't seem to be anywhere that was already testing whether or not things were closed so I think it's fine without it.

Yeah, I didn't find a good unit-test to add this to. However, we did test it by deploying (with brotli compression) and it seems to do the trick.

**Review by szehon-ho — APPROVED** [review]

**Comment by szehon-ho** [comment]
Thanks @hmit , and @kbendick @jzhuge for review

**Comment by hmitnflx** [comment]
Thanks all for the quick review and merge!

**Comment by jzhuge** [comment]
Thanks @hmit for discovering the issue and providing a fix. Thanks @kbendick for review. Thanks @szehon-ho for review and merge!

**Pull request merged**
