### PR TITLE
[BUILD][ORC] Upgrade ORC dependency to 1.6.9

### PR DESCRIPTION
**Pull request by kbendick**
Upgrades the ORC dependency to the recently released 1.6.9 version.

This brings in the fixes linked below:
Fixed issues: [ORC-1.6.9](https://issues.apache.org/jira/sr/jira.issueviews:searchrequest-printable/temp/SearchRequest.html?jqlQuery=project+%3D+ORC+AND+fixVersion+%3D+%221.6.9%22&tempMax=500)

Most notably, ORC-1.6.9 brings in support for Apple Silicon.

### CODE REVIEW

**Comment by kbendick** [comment]
Oh this isn't on maven central yet. I tested this here in my fork: https://github.com/kbendick/iceberg/pull/41

**Comment by kbendick** [comment]
I tested this here in my fork: https://github.com/kbendick/iceberg/pull/41/files

Tests seem to be failing due to potential metastore connection issue.

**Comment by kbendick** [comment]
cc @dongjoon-hyun @omalley

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Yes, this is tested already during ORC 1.6.9 vote.

BTW, cc @kbendick since he seemed to try this but closed for some reason.
- https://github.com/apache/iceberg/pull/2771

**Comment by kbendick** [comment]
cc @rdblue if you wouldn’t mind considering this for merging. An ORC PMC has signed off on it (and we’ve both tested it during the ORC 1.6.9 release process).

**Review by nastra — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Looks good to me! Merging. Thanks @kbendick + @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you so much, @kbendick , @nastra , and @RussellSpitzer !

**Pull request merged**
