### PR TITLE
Fixed context classloader of threads in ThreadPools

### LINKED ISSUE #3776: Flink connector thrown `Trying to access closed classloader`
Hi, i'm trying to test the unreleased Flink 1.13 connector on a Flink 1.13.1 cluster running on k8s.

The task is simple like `INSERT OVERWRITE a SELECT * FROM b`.

When i submit a task for the first time, it's ok.
But when i submit the task for the second time(run on the same TaskManager with the first time), the following exception is thrown, it's weird.

<details>
<summary>java.lang.IllegalStateException: Trying to access closed classloader</summary>

```
2021-12-20 11:53:11,697 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - IcebergFilesCommitter -> Sink: IcebergSink ice.t1.d (1/1)#0 (e74babbac1ebb51fe72958bd177ae534) switched from INITIALIZING to RUNNING.
2021-12-20 11:53:11,854 INFO  org.apache.iceberg.flink.sink.IcebergFilesCommitter          [] - Committing dynamic partition overwrite with 1 data files and 0 delete files to table ice.t1.d
2021-12-20 11:53:11,946 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - IcebergFilesCommitter -> Sink: IcebergSink ice.t1.d (1/1)#0 (e74babbac1ebb51fe72958bd177ae534) switched from RUNNING to FAILED with failure cause: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:164)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:172)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.apache.iceberg.common.DynClasses$Builder.impl(DynClasses.java:68)
	at org.apache.iceberg.avro.GenericAvroReader$ReadBuilder.record(GenericAvroReader.java:85)
	at org.apache.iceberg.avro.GenericAvroReader$ReadBuilder.record(GenericAvroReader.java:72)
	at org.apache.iceberg.avro.AvroSchemaVisitor.visit(AvroSchemaVisitor.java:50)
	at org.apache.iceberg.avro.GenericAvroReader.initReader(GenericAvroReader.java:47)
	at org.apache.iceberg.avro.GenericAvroReader.setSchema(GenericAvroReader.java:53)
	at org.apache.iceberg.avro.ProjectionDatumReader.newDatumReader(ProjectionDatumReader.java:80)
	at org.apache.iceberg.avro.ProjectionDatumReader.setSchema(ProjectionDatumReader.java:69)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:133)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:130)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:122)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:66)
	at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:100)
	at org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
	at org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:103)
	at org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
	at org.apache.iceberg.SnapshotProducer.newManifestReader(SnapshotProducer.java:378)
	at org.apache.iceberg.MergingSnapshotProducer$DataFileFilterManager.newManifestReader(MergingSnapshotProducer.java:716)
	at org.apache.iceberg.ManifestFilterManager.filterManifest(ManifestFilterManager.java:295)
	at org.apache.iceberg.ManifestFilterManager.lambda$filterManifests$0(ManifestFilterManager.java:186)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:405)
	at org.apache.iceberg.util.Tasks$Builder.access$300(Tasks.java:71)
	at org.apache.iceberg.util.Tasks$Builder$1.run(Tasks.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

### PR DESCRIPTION
**Pull request by yittg**
Fixes #3776

### CODE REVIEW

**Comment by rdblue** [comment]
@yittg can you please explain what this is doing and why it is the correct behavior?

**Comment by yittg** [comment]
@rdblue The context of thread in ThreadPool inherited from the parent thread. For the first task of one thread, the parent thread is current thread that executes the task, so the context is consistent with where the task is executed. As of the second and following tasks, the context of the existing thread running the task is still the one that started the thread, which can be different from the one that executed the task. And this can cause the context class loader issue described in #3776 .

For example:
1. Thread[A] with Context[Ca] executes Task[T1];
2. ThreadPool starts new Thread[P1] with Context[Ca], and running Task[T1], (OK);
3. Thread[B] with Context[Cb] executes Task[T2];
4. ThreadPool using Thread[P1] with Context[Ca] to run the Task[T2], (not OK);
    > Context[Ca] can be different from Context[Cb] and maybe already expired now.

This change records the context that executes one task in the wrapper Runnable, and sets it to the target thread before actually running the task. This can make sure the consistency of the context.

**Comment by yittg** [comment]
@rdblue Do you think this make sense? Or what do you think?

**Comment by rdblue** [comment]
@yittg, I'm skeptical that this is the right approach. The dynamic class loader allows you to specify the classloader to use. It is generally better to specify the correct one instead of relying on the context loader.

In this case, it looks like the [reader used to load the file's key-value metadata](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestReader.java#L100-L102) doesn't have the class loader set like the [reader used to scan the manifest](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestReader.java#L207). I would first try setting the class loader the same way.

**Comment by yittg** [comment]
> In this case, it looks like the [reader used to load the file's key-value metadata](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestReader.java#L100-L102) doesn't have the class loader set like the [reader used to scan the manifest](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestReader.java#L207). I would first try setting the class loader the same way.

@rdblue  It's also my first choice, FYI https://github.com/apache/iceberg/issues/3776#issuecomment-998502908, but it's not enough, as described in my comment, you can not pass the correct one to all cases in the dependencies.

> For example, the follow code snippet in [java.xml](https://github.com/openjdk/jdk/blob/jdk-11%2B12/src/java.xml/share/classes/javax/xml/parsers/FactoryFinder.java#L285)
> ```
> final ServiceLoader<T> serviceLoader = ServiceLoader.load(type);
> ```

IMO, the right way is not to use the static shared thread pool. But it's hard to fix here, the shared pool is involved in too many places.

So i choose this quick fix to walk around it.

**Comment by yittg** [comment]
@rdblue I think it's also ok to set the correct placeholder in iceberg, i can open another PR to address it, then the issue can be fixed in those scenarios not touching the same issue in third-party dependencies.

Then we can think about how to fix it thoroughly.

What do you think?

**Comment by rdblue** [comment]
@yittg, let's get the fix for manifest file reading in and then address the next issue. I think that we should not be relying on the context classloader when loading dynamically.

**Comment by yittg** [comment]
> let's get the fix for manifest file reading in and then address the next issue.

@rdblue I've open #3906 for this.

**Comment by yittg** [comment]
@rdblue i updated changes with fixed context class loader.

looks like ci failed accidentally,
retest ?

**Comment by yittg** [comment]
close this one due to prefer #4177

**Pull request closed without merging**
