### PR TITLE
Flink: Backport flaky, order-dependent test for limit 1 query in TestFlinkTableSource

### PR DESCRIPTION
**Pull request by kbendick**
This backports https://github.com/apache/iceberg/pull/4697 to Flink 1.14 and 1.13.

Let me know if we'd prefer to use 2 PRs instead.

### CODE REVIEW

**Comment by kbendick** [comment]
cc @hililiwei @yittg @stevenzwu if you get a chance.

**Review by yittg — APPROVED** [review]
LGTM

**Review by hililiwei — APPROVED** [review]
LGTM. +1 for one pr.

**Comment by rdblue** [comment]
Thanks, @kbendick!

**Pull request merged**
