### PR TITLE
Reference a specific snapshot using a custom id

### PR DESCRIPTION
**Pull request by thomaschow**
Allow iceberg reads to target a specific snapshot of a table given an externally specified id. This makes use of https://github.com/apache/iceberg/issues/1500 to retrieve the iceberg internal snapshot-id. The API is similar to that of https://github.com/apache/iceberg/blob/master/site/docs/configuration.md#read-options `snapshot-id`. 

cc? @rdblue

### CODE REVIEW

**Comment by rdblue** [comment]
We've been talking internally about a similar feature. I've been calling it "tagged snapshots" as it is similar to git version tagging. Our users would like to be able to tag a particular snapshot and use that tag for processing.

For example, a tag like "2020q1" could be used for a financial reporting table to label the version that was used for Q1 reporting. Our users want to keep these tags forever.

Is your use case similar? I'm interested because I think we might want to have first-class support for named snapshots, instead of having a property that selects by equality. What do you think?

**Comment by thomaschow** [comment]
> Is your use case similar? I'm interested because I think we might want to have first-class support for named snapshots, instead of having a property that selects by equality. What do you think?

Yep I think that would satisfy our use case. Do you have a pointer to a PR/issue/doc I can read? How far along is this feature?

**Comment by rdblue** [comment]
We've just talked about it internally. I don't think anyone has written up a doc or opened an issue.

**Comment by jacques-n** [comment]
I have some ideas I've been noodling on this. I hope to share them with the community soon!

**Comment by thomaschow** [comment]
we have probably a specific use case of this in that we effectively have a different "snapshot-id" that's exposed to users. Every time we query for a particular snapshot, we do not use the native iceberg snapshot-id rather this externally set one. So in a sense it is not "tagging", but abstracting away iceberg's internal snapshot-id. This behavior _could_ be implemented using tagging, but it sounds like it might not be the optimal way to do it.

We have considered implementing a different snapshot-id scheme but wanted to keep the iceberg internals in tact.

**Comment by thomaschow** [comment]
@rdblue @jacques-n  I will close this and we will fork the behavior internally for now, given tagged snapshots will be a thing in the future.

**Pull request closed without merging**
