### PR TITLE
AWS: Replace FileOutputStream/InputStream constructor with NIO Files APIs in S3OutputStream

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
Currently, in S3FileIO, we use new FileOutputStream for initialization when creating the current staging file. This kind of initialization means that even when explicitly calling close() on these streams, they'll only be really closed when a garbage collection is done. Same applies for the input stream

### CODE REVIEW

**Comment by amogh-jahagirdar** [comment]
I'll need to run AWS integration tests before merging

**Review by Fokko — APPROVED** [review]
Nice! This was also lighting up in my IDEA

**Review by nastra — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
S3 Multipart uplkoad integration tests + S3FileIO tests pass. Glue + LakeFormation tests are failing though, but it's unrelated to this change:

```
org.apache.iceberg.aws.glue.TestGlueCatalogTable > testCommitTableSkipArchive FAILED
    org.apache.iceberg.exceptions.ValidationException at TestGlueCatalogTable.java:410

org.apache.iceberg.aws.glue.TestGlueCatalogTable > testCreateAndLoadTableWithoutWarehouseLocation FAILED
    java.lang.RuntimeException at TestGlueCatalogTable.java:154
        Caused by: org.apache.iceberg.exceptions.ValidationException at TestGlueCatalogTable.java:151

org.apache.iceberg.aws.glue.TestGlueCatalogTable > testListTables FAILED
    org.apache.iceberg.exceptions.ValidationException at TestGlueCatalogTable.java:165

org.apache.iceberg.aws.glue.TestGlueCatalogTable > testRenameTableFailsToDeleteOldTable FAILED
    java.lang.AssertionError at TestGlueCatalogTable.java:272

org.apache.iceberg.aws.lakeformation.TestLakeFormationDataOperations > testUpdateTableWithNoInsertAccess FAILED
    software.amazon.awssdk.core.exception.SdkClientException at TestLakeFormationDataOperations.java:74
        Caused by: javax.net.ssl.SSLHandshakeException at TestLakeFormationDataOperations.java:74
            Caused by: java.security.cert.CertificateException at TestLakeFormationDataOperations.java:74

org.apache.iceberg.aws.lakeformation.TestLakeFormationDataOperations > testDeleteSuccess FAILED
    software.amazon.awssdk.core.exception.SdkClientException at TestLakeFormationDataOperations.java:130
        Caused by: javax.net.ssl.SSLHandshakeException at TestLakeFormationDataOperations.java:130
            Caused by: java.security.cert.CertificateException at TestLakeFormationDataOperations.java:130

org.apache.iceberg.aws.lakeformation.TestLakeFormationDataOperations > testUpdateTableSuccess FAILED
    software.amazon.awssdk.core.exception.SdkClientException at TestLakeFormationDataOperations.java:93
        Caused by: javax.net.ssl.SSLHandshakeException at TestLakeFormationDataOperations.java:93
            Caused by: java.security.cert.CertificateException at TestLakeFormationDataOperations.java:93
```

**Comment by amogh-jahagirdar** [comment]
Ah nvm, I was just missing some environment variables for the Glue tests :) .  Those are passing now.

**Comment by amogh-jahagirdar** [comment]
Thanks for reviews @Fokko @singhpk234 @nastra

**Pull request merged**
