### PR TITLE
Python: Loosen dependency on typing-extensions

### LINKED ISSUE #7746: pyiceberg pydantic failed with new typing-extension package
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

I have typing-extensions 4.6.1, and this version caused pydantic to failed when importing BooleanExpression from pyiceberg. Downgrading to typing-extension 4.5.0 is the workaround

To reproduce:
`
from pyiceberg.expressions import BooleanExpression
`

## Exception generated:
```
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO - Traceback (most recent call last):
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/local/bin/iceberg_converter", line 5, in <module>
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     from tasks.iceberg_converter.app import main
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/local/lib/python3.8/dist-packages/tasks/iceberg_converter/app.py", line 18, in <module>
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     from pyiceberg.expressions import BooleanExpression
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/local/lib/python3.8/dist-packages/pyiceberg/expressions/__init__.py", line 32, in <module>
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     from pyiceberg.expressions.literals import (
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/local/lib/python3.8/dist-packages/pyiceberg/expressions/literals.py", line 33, in <module>
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     from pyiceberg.types import (
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/local/lib/python3.8/dist-packages/pyiceberg/types.py", line 251, in <module>
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     class StructType(IcebergType):
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -   File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO -     return issubclass(cls, self.__origin__)
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO - TypeError: issubclass() arg 1 must be a class
[2023-05-31, 20:10:31 UTC] {pod_manager.py:410} ERROR - Error parsing timestamp (no timestamp in message ''). Will continue execution but won't update timestamp
[2023-05-31, 20:10:31 UTC] {pod_manager.py:342} INFO - 

```

### PR DESCRIPTION
**Pull request by Fokko**
In the CI we pin the `typing-extensions` dependency on `4.5.0`, but it looks like some bug has been introduced in `4.6.1`. This PR bumps `typing-extensions` to `4.6.2`.

By loosening this requirement, we install the same version as when someone would when they don't install the dev requirements.

This was broken in Pydantic `1.10.7`, and fixed in `1.10.8`: https://github.com/pydantic/pydantic/pull/5826

Resolves #7746

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks for the quick review @nastra

**Comment by rajaie-sg** [comment]
Does a new version need to be released to PyPI? https://pypi.org/project/pyiceberg/#history

I tried 0.3.0 but it still suffers from the issue in https://github.com/apache/iceberg/issues/7746

**Comment by Fokko** [comment]
@rajaie-sg A new version is incoming. The issue should only happen if you also install the dev dependency. Otherwise, you can run `pip3 install --upgrade typing-extensions.`

**Comment by rajaie-sg** [comment]
Ah I see, I was running `pip3 install "pyiceberg[glue,s3fs,hive]"`

**Comment by rajaie-sg** [comment]
Actually, it looks like the issue here is with pydantic, which is fixed to version 1.10.4 here https://github.com/apache/iceberg/blob/pyiceberg-0.3.0/python/pyproject.toml#LL58C1-L58C9

Even when I run `pip3 install --upgrade typing-extensions`, I still run into the problem. 

It's only when I run `pip3 install --upgrade pydantic ` does the problem get resolved, but this isn't a solution since we are using Poetry and it prevents us from specifying a version of Pydantic other than 1.10.4 in the pyproject.toml file.

pydantic gets installed by default with pyiceberg

**Pull request merged**
