### PR TITLE
Docs: Add ORC to table and writer format configs

### PR DESCRIPTION
**Pull request by shardulm94**

### CODE REVIEW

**Review by RussellSpitzer — APPROVED** [review]
Not sure if Iceberg has an opinion on Oxford commas. Looks good to me

**Comment by shardulm94** [comment]
@RussellSpitzer I saw some other places in the doc using it, so I updated the PR to use it too. Thanks for the suggestion!

**Comment by RussellSpitzer** [comment]
I don't have a strong opinion :) either way is fine with me. I just end up
singing the Vampire Weekend song of the same name every time I see one
missing

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
I appreciate the Oxford commas.

**Pull request merged**
