### PR TITLE
Flink: update deprecated code in flink

### PR DESCRIPTION
**Pull request by hunter-cloud09**
update deprecated code in [FLIP-164](https://cwiki.apache.org/confluence/display/FLINK/FLIP-164%3A+Improve+Schema+Handling+in+Catalogs)

### CODE REVIEW

**Comment by hunter-cloud09** [comment]
If there is no problem with this, I will push the test module in another pr

**Comment by hililiwei** [comment]
There have been some PRs doing something like this before. You can search in the PR list.

**Comment by rdblue** [comment]
@stevenzwu, can you take a look?

**Comment by hunter-cloud09** [comment]
> There have been some PRs doing something like this before. You can search in the PR list.

thx for your response, but I can't find the relevant PRs, can you post it?

**Comment by hililiwei** [comment]
https://github.com/apache/iceberg/pull/4246
Just to list the one I had before. I remember someone else mentioning one or two similar ones.

**Pull request closed without merging**
