### PR TITLE
Docs: Add Javadoc for 0.11.1

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds Javadoc for 0.11.1 that is already deployed.

### CODE REVIEW

**Comment by openinx** [comment]
Do we have to use git to manage javadoc? Each release will generate a large number of html files, which brings some additional burden to our git repo. Can we directly remove these doc files from git and automatically generate doc files when we build the release package ?

**Comment by aokolnychyi** [comment]
I'd support finding a better way to track this. Maybe, we can even move site-related things to another repo?

**Comment by aokolnychyi** [comment]
Indexing all these files will eventually be a problem in IDEs.

**Comment by aokolnychyi** [comment]
@openinx, how does Flink handle this? I think Spark has its own repo for docs.

**Comment by openinx** [comment]
I'm still not quite sure how does flink handle this, but I am sure that apache hbase has created a separate github repo for docs (https://github.com/apache/hbase-site),  each released version has a separate directory to maintain its java docs. The RM will generate all the docs and copy those files into the `hbase-site` repo for deploying (https://github.com/apache/hbase-site/pull/7#issuecomment-776991616)

**Comment by aokolnychyi** [comment]
Thanks for confirming, @openinx. I think that matches Spark and that's what we should probably switch to.

@rdblue, thoughts?

**Comment by rdblue** [comment]
+1 for a separate repo. We'll have to get everything moved over, but it shouldn't be too difficult.

**Comment by aokolnychyi** [comment]
I won't have time in the following days to do that. Two questions: what do we do now and is there anybody who can do the transition?

**Comment by rdblue** [comment]
I'm sure we can find the time to do this later. For now, we can just continue tracking the docs in this repo.

**Comment by aokolnychyi** [comment]
I've created an issue to move everything. Shall we merge this PR to keep track of what is already deployed?

**Review by rdblue — APPROVED** [review]

**Pull request merged**
