### PR TITLE
1.7.1rc0 cherry picks

### PR DESCRIPTION
**Pull request by bryanck**
This PR picks the following PRs to the 1.7.x branch, in preparation for the 1.7.1 release:

https://github.com/apache/iceberg/pull/11516
https://github.com/apache/iceberg/pull/11395
https://github.com/apache/iceberg/pull/11504
https://github.com/apache/iceberg/pull/11574

### CODE REVIEW

**Review by Fokko — APPROVED** [review]

**Review by nastra — APPROVED** [review]

**Comment by bryanck** [comment]
Thanks for the review @nastra and @Fokko !

**Review by RussellSpitzer — COMMENTED** [review]
LGTM :)

**Comment by RussellSpitzer** [comment]
@bryanck Could you revert this and merge it again as a series of commits? Rather than squashing?

**Comment by bryanck** [comment]
Sure

**Comment by bryanck** [comment]
New PR is here: https://github.com/apache/iceberg/pull/11603

**Pull request merged**
