### PR TITLE
Spark 3.4, 3.5: Use ProcedureInput for RewriteDataFiles

### LINKED ISSUE #8582: Switch to using ProcedureInput for rewriteDataFiles
### Feature Request / Improvement

Based on comment in https://github.com/apache/iceberg/pull/8560#discussion_r1325961435

### Query engine

None

### PR DESCRIPTION
**Pull request by dramaticlly**
close #8582

CC @aokolnychyi @ConeyLiu @RussellSpitzer

### CODE REVIEW

**Review by ConeyLiu — APPROVED** [review]
Thanks @dramaticlly, LGTM

**Comment by dramaticlly** [comment]
Rebased latest upstream and added corresponding change in spark 3.5 as well

**Comment by dramaticlly** [comment]
@aokolnychyi if you can take a look!

**Review by RussellSpitzer — APPROVED** [review]
Looks like a clean refactor to me. Good to go

**Review by szehon-ho — APPROVED** [review]

**Comment by szehon-ho** [comment]
Merged, thanks @dramaticlly , and thanks all for additional reviews.

**Pull request merged**
