### PR TITLE
Build: Update NOTICE to include copyright for 2024

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by szehon-ho** [comment]
While we are here, let's do the other ones, like azure-bundle NOTICE as well?

**Review by szehon-ho — COMMENTED** [review]
While we are here, let's do the other ones, like azure-bundle NOTICE as well?

**Review by jbonofre — APPROVED** [review]
For the record, here's the details about `NOTICE` content: https://www.apache.org/legal/src-headers.html

IImho, we should have the `NOTICE` only at root level (no need to have `NOTICE` in all folders).

The version range should match the year of the current version, so 2024 is correct.

I will propose another PR to cleanup the subfolder `NOTICE` files.

**Comment by caicancai** [comment]
> For the record, here's the details about `NOTICE` content: https://www.apache.org/legal/src-headers.html
> 
> IImho, we should have the `NOTICE` only at root level (no need to have `NOTICE` in all folders).
> 
> The version range should match the year of the current version, so 2024 is correct.
> 
> I will propose another PR to cleanup the subfolder `NOTICE` files.

Thanks

**Comment by caicancai** [comment]
> While we are here, let's do the other ones, like azure-bundle NOTICE as well?

Sorry, I don't seem to understand what you mean. Is there anything you need me to do?

**Comment by szehon-ho** [comment]
> > While we are here, let's do the other ones, like azure-bundle NOTICE as well?
> 
> Sorry, I don't seem to understand what you mean. Is there anything you need me to do?

I mean , there's some missing NOTICE that need update like https://github.com/apache/iceberg/blob/main/azure-bundle/NOTICE  

> For the record, here's the details about `NOTICE` content: https://www.apache.org/legal/src-headers.html
> 
> IImho, we should have the `NOTICE` only at root level (no need to have `NOTICE` in all folders).
> 
> The version range should match the year of the current version, so 2024 is correct.
> 
> I will propose another PR to cleanup the subfolder `NOTICE` files.

Yea if we can combine them somehow, that'd be nice..

**Comment by caicancai** [comment]
> > > While we are here, let's do the other ones, like azure-bundle NOTICE as well?
> > 
> > 
> > Sorry, I don't seem to understand what you mean. Is there anything you need me to do?
> 
> I mean , there's some missing NOTICE that need update like https://github.com/apache/iceberg/blob/main/azure-bundle/NOTICE
> 
> > For the record, here's the details about `NOTICE` content: https://www.apache.org/legal/src-headers.html
> > IImho, we should have the `NOTICE` only at root level (no need to have `NOTICE` in all folders).
> > The version range should match the year of the current version, so 2024 is correct.
> > I will propose another PR to cleanup the subfolder `NOTICE` files.
> 
> Yea if we can combine them somehow, that'd be nice..

Thanks for the reminder, fix

**Review by nastra — COMMENTED** [review]
Can you also please update the file in `aws-bundle` and `gcp-bundle`?

**Comment by caicancai** [comment]
> Can you also please update the file in `aws-bundle` and `gcp-bundle`?

Fix

**Review by nastra — APPROVED** [review]

**Review by szehon-ho — APPROVED** [review]

**Comment by szehon-ho** [comment]
Merged, thanks @caicancai , and @nastra , @jbonofre for additional review

**Pull request merged**
