### PR TITLE
Spark: Support passing specific list of snapshot id for ExpireSnapshots procedure

### PR DESCRIPTION
**Pull request by ajantha-bhat**
ExpireSnapshot Action supports setting specific snapshots ids to expire, but it is missing in call procedure. Hence this PR.

### CODE REVIEW

**Comment by rdblue** [comment]
@ajantha-bhat, what is the use case for exposing this?

Expiring individual snapshots by ID is not a recommended operation because it can break certain operations that use table history. Unless there's a reason to expose this to SQL users, I would rather not.

**Comment by ajantha-bhat** [comment]
> @ajantha-bhat, what is the use case for exposing this?

> Expiring individual snapshots by ID is not a recommended operation because it can break certain operations that use table history. Unless there's a reason to expose this to SQL users, I would rather not.

@rdblue 
a) I am not newly exposing this feature to the user, it was already exposed in the Spark Actions. I am just supporting from SQL also to be in sync.
b) I see the code to handle snapshot history log file also present in expireSnapshots. So, can you elaborate what operations it can break ? If it is really issue, do we need to handle this for spark actions also ?

**Comment by rdblue** [comment]
I realize that this is already exposed through the API. But is there a need for SQL users to call this? Do you have people that need to do this or are you adding it because it is something exposed in Actions that is not present in the stored procedure?

**Comment by ajantha-bhat** [comment]
@rdblue : Nessie is planning to use expireSnapshots action with specific expire snapshot id as if we don't set list of expire snapshot id, action will expire table's snapshots that are referred in other branches also.

We don't have any plans for using SQL yet, but it is just my own initiative to make SQL procedure same as Actions. So, that user can use it with all functionalities. I think these changes will help users.
@rymurr , @RussellSpitzer , @jackye1995 : What is your opinion on this PR changes ?

**Comment by RussellSpitzer** [comment]
I think i'm the side of less options exposed the better. Since SQL is the "easy" first use api I would try to hide features which may cause undesired effects. I'm not sure it really hinders anyone who specifically ones to expire certain snapshots since they already would need to be very careful. 

For example I assume Nessie would use the underlying api with a separate interface for Nessie users since actually determining the list of Snapshots that can be removed will be non-trivial.

**Comment by rdblue** [comment]
> Since SQL is the "easy" first use api I would try to hide features which may cause undesired effects.

Well said. That captures my reservations about this.

**Comment by rdblue** [comment]
Oops, I didn't intend to close this. I clicked the wrong button.

**Comment by jackye1995** [comment]
> Since SQL is the "easy" first use api I would try to hide features which may cause undesired effects.

+1, especially as we are adding branching feature, expiring a specific snapshot by ID should be strongly discouraged.

**Comment by ajantha-bhat** [comment]
@jackye1995 , @RussellSpitzer , @rdblue : Thanks for your inputs. As majority of you (I think all of you) are not in favour of it, So, I am closing this PR.

**Pull request closed without merging**
