### PR TITLE
Flink: Replace Flink Tableschema To Resolvedschema 

### PR DESCRIPTION
**Pull request by slfan1989**
### Background

Flink1.16 `TableSchema` is Deprecated

```
This class has been deprecated as part of FLIP-164.
It has been replaced by two more dedicated classes `Schema` and `ResolvedSchema`.
Use Schema for declaration in APIs. 
ResolvedSchema is offered by the framework after resolution and validation.
```

Some methods have been marked by `Flink` as methods to be deleted, We should implement our code according to the method recommended by `Flink`.

TypeConversions#fromDataTypeToLegacyInfo

```
 /**
   * @deprecated Please don't use this method anymore. It will be removed soon and we should not
   *     make the removal more painful. Sources and sinks should use the method available in
   *     context to convert, within the planner you should use either {@code InternalTypeInfo} or
   *     {@code ExternalTypeInfo} depending on the use case.
   */
@Deprecated
public static TypeInformation<?>[] fromDataTypeToLegacyInfo(DataType[] dataType) {
    return Stream.of(dataType)
           .map(TypeConversions::fromDataTypeToLegacyInfo)
           .toArray(TypeInformation[]::new);
}
```

In This PR,  I will use `ResolvedSchema` to replace `TableSchema`.
Modifications Include:
1. Contains the method of tableSchema.
2. Junit Test.
3. Comment.
4. Link references.

### CODE REVIEW

**Comment by rdblue** [comment]
@slfan1989, in the past we haven't added these changes because it is unclear whether Iceberg should produce a resolved schema or an unresolved schema. Can you explain the purpose of both classes, what you plan to use in this PR, and why you've made that choice?

**Comment by stevenzwu** [comment]
some of previous attempts: PR #4246 and PR #5938

**Comment by slfan1989** [comment]
> in the past we haven't added these changes because it is unclear whether Iceberg should produce a resolved schema or an unresolved schema. Can you explain the purpose of both classes, what you plan to use in this PR, and why you've made that choice?

Thank you very much for your question.

We can refer to this document:
https://cwiki.apache.org/confluence/display/FLINK/FLIP-164%3A+Improve+Schema+Handling+in+Catalogs

`FLIP-164` explains that `Schema` should distinguish between `unresolved` and `resolved` variant, while `TableSchema` is a hybrid between `resolved` and `unresolved` schema.

`TableSchema` is split into 2 parts, `Schema` and `ResolvedSchema`.

1. Schema
```
Contains Unresolved fields, These fields may not be validated, for example, 
there may be duplicate primary keys.
 Offers convenient methods to adopt columns etc. 

Schema {
    static Schema.Builder newBuilder();
    List<UnresolvedColumn> getColumns();
    List<UnresolvedWatermarkSpec> getWatermarkSpecs();
    Optional<UnresolvedPrimaryKey> getPrimaryKey();
    ResolvedSchema resolve(SchemaResolver);
}
```

2. ResolvedSchema
```
Class that is exposed by the framework at different locations for validated and complete schema.
It replaces TableSchema

ResolvedSchema {
    int getColumnCount();
    List<Column> getColumns();
    Optional<Column> getColumn(int);
    Optional<Column> getColumn(String);
    List<WatermarkSpec> getWatermarkSpecs();
    Optional<UniqueConstraint> getPrimaryKey();
    DataType toRowDataType();
    DataType toPhysicalRowDataType();
    DataType toPersistedRowDataType();
.....
}
```

**Comment by slfan1989** [comment]
> some of previous attempts: PR #4246 and PR #5938

@stevenzwu  Thank you for the information!

I think my PR has the following advantages:

1. Completely replace `TableSchema` with `ResolvedSchema` based on the latest code.
2. Pass all unit tests.
3. The code changes are small and do not affect other codes.

Can I continue this work based on this PR?

**Pull request closed without merging**
