### PR TITLE
Build: Add note about running tests/itests on MacOS

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by nastra — APPROVED** [review]
LGTM, but would be great if somebody with OSX could confirm this

**Comment by ajantha-bhat** [comment]
> LGTM, but would be great if somebody with OSX could confirm this

I can confirm. I use MAC. Not just for Iceberg project, any project that uses `TestContainers` on MAC will throw an error for running tests that "Could not find a valid Docker environment."

I used to google and use the command from below answer. Which matches the doc update. 
https://stackoverflow.com/questions/61108655/test-container-test-cases-are-failing-due-to-could-not-find-a-valid-docker-envi

**Review by ajantha-bhat — APPROVED** [review]

**Comment by jbonofre** [comment]
@nastra actually it's the workaround I have to do on my Mac :) I'm using MacOS (tested both on 13 & 14 with Docker Desktop) on M1.

**Comment by jbonofre** [comment]
@ajantha-bhat I bet we can have questions for any MacOS user trying to build iceberg (it was my case). Even people on Linux should know that Docker is required for the tests. So, this note will help people (including us to answer the same question again and again :) ).

**Comment by jbonofre** [comment]
@nastra are you OK to merge this one ?

**Comment by nastra** [comment]
@Fokko could you review and confirm this one please?

**Comment by Fokko** [comment]
For me it looks like the file was created by the daemon:
```
➜  ls -lah /var/run/docker.sock
lrwxr-xr-x  1 root  daemon    46B Oct 16 16:32 /var/run/docker.sock -> /Users/fokkodriesprong/.docker/run/docker.sock
➜  last reboot                         
reboot time                                Mon Oct 16 16:29
```

**Review by Fokko — APPROVED** [review]
I don't mind adding this, but it looks like that it isn't the same for everyone on Mac

**Comment by jbonofre** [comment]
@Fokko I think anyone using docker-desktop on Mac will have the same issue. So it applies for 99% of the MacOS users.

**Comment by Fokko** [comment]
@jbonofre  I'm running docker desktop as well

**Comment by jbonofre** [comment]
@Fokko and you don't have the symbolic link ? Did you install docker-desktop from homebrew cask ?

**Pull request merged**
