### PR TITLE
Core: fix NPE in manifests table for contains_nan column, update spec

### LINKED ISSUE #2405: NPE when reading metadata for manifests.
When using Spark3SQL to read manifests, it throws NPE exception. The stack is：
Caused by: java.lang.NullPointerException
	at org.apache.iceberg.spark.source.StructInternalRow.getBoolean(StructInternalRow.java:109)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invokeChecked(DynMethods.java:65)
	at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:77)
	at org.apache.iceberg.common.DynMethods$BoundMethod.invoke(DynMethods.java:180)
	at org.apache.iceberg.spark.source.RowDataReader.lambda$newDataIterable$3(RowDataReader.java:197)
	at org.apache.iceberg.io.CloseableIterable$4$1.next(CloseableIterable.java:114)
	at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:66)
	at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:50)
	at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:87)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:79)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:112)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1371)
	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1298)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1362)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1186)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:360)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:311)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1391)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	... 3 more

### PR DESCRIPTION
**Pull request by yyanyy**
- fix #2405 which is caused by NPE brought in by #1872. When I changed `containsNaN` field within partition field summary from primitive to boxed boolean within #1872, I forgot to change other places that refers to the primitive boolean, causing #2405 and #2495 (thanks @RussellSpitzer again for the fix!)
- in #2405 we also investigated the other approach that can prevent this issue - to make `containsNaN` a primitive to avoid potential NPE. This may have the following implication:
  - we generally want to assign `true` to this column so that we don't falsely skip it; but in this case non-floating-point columns will also have `containsNaN=true` in memory which doesn't make sense. This field isn't used anywhere for non-floating-point columns so it won't have correctness concern. However when displaying manifests table, this default value will be used, and for any files written before `containsNaN` getting populated in field summary, `containsNaN` will be displayed as `true` which may not be correct. 
  - there is [a case within manifest evaluator](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java#L164) that will produce less accurate result if we don't differentiate `true` between actually having NaN and default value
  - [public facing interface](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L209-L211) may need to change but it's minor since it is not part of any release

In addition to fixing the NPE problem, this PR attempts to follow the current approach (of nullable `containsNaN`) to update spec with the current state. We can continue the discussion of how to handle it here and I'll make sure to reflect it in the actual spec before merge.

### CODE REVIEW

**Review by RussellSpitzer — APPROVED** [review]
I think this is the right approach for this fix, one of the Spec changes seems unrelated to this issues (field field) but I have no problem with fixing typos in the same pr.

**Comment by chenjunjiedada** [comment]
Should we add a unit test to read a v1 manifest file?

**Comment by RussellSpitzer** [comment]
> Should we add a unit test to read a v1 manifest file?

I would also like to see this, but I think we probably need a dedicated backwards compatibility suite somewhere

**Comment by jackye1995** [comment]
> we probably need a dedicated backwards compatibility suite somewhere

+1. As we are thinking about v3 now, I am trying to implement this in a way that can be flexible for future spec versions, will send a PR about this soon.

**Comment by yyanyy** [comment]
Thank you for the quick review and feedback everyone!

Regarding backward compatibility tests for reading manifest files, I think there are a few things worth mentioning:
1) Iceberg does have dedicated tests on verifying backwards compatibility for both [manifest file](https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java) and [manifest list](https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/TestManifestListVersions.java).
2) even with these backward compatible tests, this issue can still occur (I did update the [test](https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/TestManifestListVersions.java#L221-L222) in the original PR). The reason is I think these are two separate issues:
    - My understanding of the problem that's fixed by this specific PR is not related to generally reading of the manifest files/manifest list itself, but rather the display of a metadata table `manifests table` which is a separate logic. 
    -  The problem before the fix was that the schema we specified for this manifest table is [wrong](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestsTable.java#L41) comparing to the correct specification we have for the actual requirement of manifest files [here](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L58), and this mismatch caused the NPE problem since we require an originally nullable field to be not null. 
    - If we reused the schema construct we defined from `ManifestFile` (which is the source of truth in persisting manifest list file) in `ManifestsTable` we can avoid this problem completely, but currently `ManifestFile` doesn't want to expose them out, and has to specifically define the ID to ensure there's no duplication. I think we can still reuse them if we want, but that requires some code changes, and the current approach of duplicating definition of the same concepts in multiple places seems like a more widely adopted approach across Iceberg project. 
    - I think the ultimate way of preventing this specific problem is to create tests around metadata tables, and for this specific problem, we create v1 and v2 normal table, write data to them, and then query the manifest table and ensure output meets expected. However I think we don't have any test around metadata tables today. 

I think the follow up item after this PR should be to create an issue to add metadata tables tests to make sure they don't break when reading different versions of tables. Any comment/feedback/suggestions?

**Review by chenjunjiedada — APPROVED** [review]
Agree to follow up with a separated PR.

**Comment by RussellSpitzer** [comment]
I was wondering about the other NPE in #2495, i was hoping that would have been caught by some backwards compatibility tests. I also have no problem with doing more testing and such in another pr

**Review by RussellSpitzer — APPROVED** [review]

**Review by jackye1995 — APPROVED** [review]

**Comment by yyanyy** [comment]
> I was wondering about the other NPE in #2495, i was hoping that would have been caught by some backwards compatibility tests. I also have no problem with doing more testing and such in another pr

I think the hard part is that this specific change (and some other spec changes) is adding a field regardless of table versions, and to ensure backward compatibility which means to test on a table before this logic is introduced, we need to have a fine grain control of creating these metadata files to mimic the old behavior when creating the table, so that we can drop things introduced in the new logic. And this basically means to create the table from scratch. 
 - Tests like `TestManifestListVersions` covers part of that but it only test the basic interaction, no the end to end table operation exists in such tests that could catch problem in `ManifestFileUtil` which is used during table commit. 
 - Some tests extending `TableTestBase` in core package try to test backward compatibility by running tests with table v1 and v2 format, but again they won't capture logic introduced in all versions of the spec. 

I think a way of achieving it could be to add resource files (including data file and all metadata files all the way to the json file) with all optional/later introduced fields missing, and these resource files could be readily readable as an existing table (instead of creating tables via code as those tests currently do). And then we let tests that extend `TableTestBase` to interact with this table. 

---
I'm merging in this change to unblock bug fixes, but please feel free to continue the discussion here or ping me directly on slack. Thank you again @chenjunjiedada @RussellSpitzer @jackye1995 for the review and quick response! And thanks Jack for creating the issue!

**Pull request merged**
