### PR TITLE
Checkstyle: Add checkstyle rule for %d in Preconditions.checkArgument

### LINKED ISSUE #4618: Add checkstyle rule for %d in Preconditions.checkArgument
Reference: https://github.com/apache/iceberg/pull/4558, Preconditions.checkArgument only works with %s, as %d does not parse and returns a bad error message.

We can make a checkstyle rule to prevent this, example of a checkstyle rule:  https://github.com/apache/iceberg/blob/master/.baseline/checkstyle/checkstyle.xml#L54-L57

It should probably use multi-line regex rule as some of these are across multiple lines:  https://checkstyle.sourceforge.io/config_regexp.html#RegexpMultiline (thanks @RussellSpitzer for pointer)

### PR DESCRIPTION
**Pull request by xrl1**
Closes #4618 

From the issue:
`Preconditions.checkArgument` only works with %s, as %d does not parse and returns a bad error message.

Created a multiline regex to prevent this.

The regex is as follows:
```regex
Preconditions\.checkArgument\([^;]+%d[^;]+\);
```
The logic behind it: Find the function call, then any characters (except `;`) until `%d`, and finally search until the function closes and a ';'.
* Used `[^;]*` instead of `.*`, because this is a multiline search and the dotall regex param (enabled by `matchAcrossLines` config) is aggressive and this is the best way to break its search.

Also, fixed %d usages that the Checkstyle rule found

### CODE REVIEW

**Review by szehon-ho — APPROVED** [review]

**Comment by szehon-ho** [comment]
Looks like some violation in Spark 3.0?  Also fyi , @kbendick

**Comment by xrl1** [comment]
@szehon-ho I committed a fixup to the violation (missed it while running the checkstyle locally in the IDE for some reason)

**Comment by xrl1** [comment]
Updated the PR again, and now also tested the build locally to pass, sorry for that.

**Comment by szehon-ho** [comment]
@xrl1 thanks for the explanation for those points.  How about the last point:

> Added the quote and comma to avoid matching the first argument, but I can simplify the regex and not handle the edge cases where there is "%d" in the first argument

Do you think we should simplify this?  I don't see much possibility of %d in the first argument of Precondition (which is evaluating a boolean), other than a modulo operation but in that case there is a space after %.  Or let me know if I missed what you mean.

**Comment by xrl1** [comment]
@szehon-ho Yeah you are right, it is really unlikely to encounter `%d` in the first argument;
 simplified it to:
```regex
Preconditions\.checkArgument\([^;]+%d[^;]+\);
```

**Review by kbendick — APPROVED** [review]
LGTM! Thank you!

**Comment by kbendick** [comment]
> @szehon-ho Yeah you are right, it is really unlikely to encounter `%d` in the first argument I simplified it to:
> 
> ```regexp
> Preconditions\.checkArgument\([^;]+%d[^;]+\);
> ```

Could you update the PR description with the explanation of this regex (so we don't have to look it up in the conversation) @xrl1? I believe the original regex is still there.

**Comment by xrl1** [comment]
@kbendick Yeah sure, updated.

**Comment by szehon-ho** [comment]
Thanks @xrl1  and @kbendick for additional review

**Pull request merged**
