### PR TITLE
Arrow: Bump to Apache Arrow 5.0

### PR DESCRIPTION
**Pull request by nastra**
Note that the benchmarks were run via GH actions, so the numbers are quite high compared to when running these benchmarks locally.

# Results on the `bump-arrow` branch (full run [here](https://github.com/nastra/iceberg/actions/runs/1367849140))
## VectorizedReadFlatParquetDataBenchmark

```
Benchmark                                                                 Mode  Cnt   Score   Error  Units
VectorizedReadFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5   2.825 ± 0.223   s/op
VectorizedReadFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5   2.444 ± 0.359   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  12.984 ± 0.624   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  11.915 ± 1.092   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5   5.146 ± 0.278   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5   4.199 ± 0.572   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5   5.034 ± 0.247   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5   4.633 ± 0.359   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5   3.617 ± 0.310   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5   4.123 ± 0.238   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5   3.809 ± 0.478   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5   3.594 ± 0.352   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5   6.325 ± 0.749   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5   7.017 ± 0.738   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5   2.383 ± 0.227   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5   2.434 ± 0.146   s/op
```

## VectorizedReadDictionaryEncodedFlatParquetDataBenchmark

```
Benchmark                                                                                  Mode  Cnt   Score   Error  Units
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5   6.787 ± 0.540   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5   6.935 ± 0.437   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  22.997 ± 0.359   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  21.877 ± 0.623   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5   6.855 ± 0.068   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5   6.000 ± 0.259   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5   6.509 ± 0.377   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5   6.318 ± 0.946   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5   6.687 ± 0.400   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5   6.144 ± 0.139   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5   6.171 ± 0.346   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5   6.816 ± 0.352   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5   9.311 ± 0.510   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5  12.845 ± 0.268   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5   8.647 ± 0.363   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5   6.196 ± 0.560   s/op
```

# Results on the `master` branch (full run [here](https://github.com/nastra/iceberg/actions/runs/1366744441))
## VectorizedReadFlatParquetDataBenchmark

```
Benchmark                                                                 Mode  Cnt   Score   Error  Units
VectorizedReadFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5   3.194 ± 0.309   s/op
VectorizedReadFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5   3.232 ± 0.189   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  16.414 ± 1.536   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  13.482 ± 1.011   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5   4.278 ± 0.205   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5   5.379 ± 0.363   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5   4.998 ± 0.261   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5   4.629 ± 0.367   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5   5.547 ± 0.369   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5   4.651 ± 0.394   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5   4.818 ± 0.329   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5   4.539 ± 0.218   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5   8.695 ± 0.689   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5   7.767 ± 0.385   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5   2.787 ± 0.195   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5   2.835 ± 0.354   s/op
```

## VectorizedReadDictionaryEncodedFlatParquetDataBenchmark

```
Benchmark                                                                                  Mode  Cnt   Score   Error  Units
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5   6.997 ± 0.843   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5   6.737 ± 0.832   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  26.559 ± 1.274   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  20.092 ± 1.980   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5   7.343 ± 0.106   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5   4.836 ± 0.149   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5   5.361 ± 0.209   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5   6.039 ± 0.527   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5   6.410 ± 0.664   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5   5.581 ± 0.689   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5   8.000 ± 0.613   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5   5.954 ± 0.250   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5  10.450 ± 0.699   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5  12.724 ± 0.773   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5   8.279 ± 0.761   s/op
VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5   6.674 ± 0.348   s/op
```

### CODE REVIEW

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
@nastra, can you verify that the benchmarks still look good after the upgrade?

**Comment by nastra** [comment]
> @nastra, can you verify that the benchmarks still look good after the upgrade?

sure thing. Will run benchmarks and update results here.

**Comment by nastra** [comment]
@rdblue benchmark results seem to be fine. 


# Results on this branch
```
Benchmark                                                                 Mode  Cnt  Score   Error  Units
VectorizedReadFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5  2.045 ± 0.041   s/op
VectorizedReadFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5  1.529 ± 0.052   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  9.216 ± 0.174   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  8.018 ± 0.305   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5  2.585 ± 0.132   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5  2.764 ± 0.339   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5  2.808 ± 0.263   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5  2.304 ± 0.157   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5  2.733 ± 0.109   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5  2.588 ± 0.155   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5  2.479 ± 0.042   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5  2.621 ± 0.182   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5  4.674 ± 0.137   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5  4.041 ± 0.249   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5  1.945 ± 0.079   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5  1.572 ± 0.075   s/op
```

# Results on `master` (copied from https://github.com/apache/iceberg/pull/3023)
```
Benchmark                                                                 Mode  Cnt  Score   Error  Units
VectorizedReadFlatParquetDataBenchmark.readDatesIcebergVectorized5k         ss    5  1.587 ± 0.106   s/op
VectorizedReadFlatParquetDataBenchmark.readDatesSparkVectorized5k           ss    5  1.515 ± 0.061   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsIcebergVectorized5k      ss    5  9.324 ± 0.511   s/op
VectorizedReadFlatParquetDataBenchmark.readDecimalsSparkVectorized5k        ss    5  7.987 ± 0.164   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesIcebergVectorized5k       ss    5  2.829 ± 0.239   s/op
VectorizedReadFlatParquetDataBenchmark.readDoublesSparkVectorized5k         ss    5  2.381 ± 0.142   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsIcebergVectorized5k        ss    5  2.399 ± 0.088   s/op
VectorizedReadFlatParquetDataBenchmark.readFloatsSparkVectorized5k          ss    5  2.584 ± 0.230   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersIcebergVectorized5k      ss    5  2.664 ± 0.083   s/op
VectorizedReadFlatParquetDataBenchmark.readIntegersSparkVectorized5k        ss    5  2.535 ± 0.090   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsIcebergVectorized5k         ss    5  2.740 ± 0.171   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsSparkVectorized5k           ss    5  2.255 ± 0.128   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsIcebergVectorized5k       ss    5  4.803 ± 0.142   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsSparkVectorized5k         ss    5  4.326 ± 0.286   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsIcebergVectorized5k    ss    5  1.946 ± 0.152   s/op
VectorizedReadFlatParquetDataBenchmark.readTimestampsSparkVectorized5k      ss    5  1.551 ± 0.042   s/op
```

**Comment by rdblue** [comment]
It looks like `readDatesIcebergVectorized5k` takes 30% longer? And it looks like the difference between `readFloatsIcebergVectorized5k` is just outside where the error ranges overlap.

Also, what about `VectorizedReadDictionaryEncodedFlatParquetDataBenchmark`? Is that the one you were having trouble running?

**Comment by nastra** [comment]
> Also, what about `VectorizedReadDictionaryEncodedFlatParquetDataBenchmark`? Is that the one you were having trouble running?

`VectorizedReadDictionaryEncodedFlatParquetDataBenchmark` is currently not working and is being investigated in https://github.com/apache/iceberg/issues/3157

**Comment by nastra** [comment]
> It looks like `readDatesIcebergVectorized5k` takes 30% longer? And it looks like the difference between `readFloatsIcebergVectorized5k` is just outside where the error ranges overlap.

The variability in the timings come from the fact because I was doing dev work while running those tests on my local machine. The other thing is that with `Mode.SingleShotTime` benchmarks we're effectively measuring the **cold** performance (we do 3 warmup iterations and 5 measurement iterations). Below is an excerpt from the Javadoc taken from [here](http://javadox.com/org.openjdk.jmh/jmh-core/0.8/org/openjdk/jmh/annotations/Mode.html#SingleShotTime):

> Single shot time: measures the time for a single operation.

> Runs by calling {@link Benchmark} once and measuring its time. This mode is useful to estimate the "cold" performance when > you don't want to hide the warmup invocations, or if you want to see the progress from call to call, or you want to record every > single sample. This mode is work-based, and will run only for a single invocation of {@link Benchmark} method.

> Caveats for this mode include:

> More warmup/measurement iterations are generally required.
> Timers overhead might be significant if benchmarks are small; switch to {@link #SampleTime} mode if that is a problem.

I also did another run on this branch and below are the new results:

```
```

**Comment by RussellSpitzer** [comment]
Merged Thanks @nastra! Also thanks for getting benchmark's action working!

**Pull request merged**
