### PR TITLE
Hive: Use timezone of the object inspector while constructing primitive Java objects for timestamp with local time zone

### PR DESCRIPTION
**Pull request by SourabhBadhya**
Solves #8112

### CODE REVIEW

**Comment by SourabhBadhya** [comment]
Can someone please provide the approval for the workflow and help review this patch.
cc @pvary @Fokko @RussellSpitzer @szehon-ho

**Review by Fokko — APPROVED** [review]
@SourabhBadhya Sorry for the long wait. I'm not super familiar with the code. Looking at it, your change makes sense to me:

In the `IcebergTimestampObjectInspectorHive3.java`:

```java
  @Override
  public Timestamp getPrimitiveJavaObject(Object o) {
    if (o == null) {
      return null;
    }
    LocalDateTime time = (LocalDateTime) o;
    Timestamp timestamp = Timestamp.ofEpochMilli(time.toInstant(ZoneOffset.UTC).toEpochMilli());
    timestamp.setNanos(time.getNano());
    return timestamp;
  }
```

And in `Timestamptz`:

```java
  @Override
  public TimestampTZ getPrimitiveJavaObject(Object o) {
    if (o == null) {
      return null;
    }
    OffsetDateTime odt = (OffsetDateTime) o;
    ZonedDateTime zdt = odt.atZoneSameInstant(((TimestampLocalTZTypeInfo) typeInfo).getTimeZone());
    return new TimestampTZ(zdt);
  }
```

**Comment by rdblue** [comment]
I don't think we can merge this.

This is modifying the `TIMESTAMP WITH TIME ZONE` reader, not the `TIMESTAMP WITH LOCAL TIME ZONE` reader. I don't think we should change the behavior of that existing type unless it is incorrect, and we should use the type-specific logic.

Also, it isn't clear that the zone of the object inspector is the SQL session time zone, or whether there is something in Hive that translates later to the session time zone. There are just a lot of unknowns here that we need to confirm before moving ahead:

1. How do we handle `TIMESTAMP WITH LOCAL TIME ZONE`? Do we need a specific reader for it?
2. What is the behavior with respect to the session time zone of that type? What is responsible for conversion?
3. What is the session time zone?

**Comment by Fokko** [comment]
What confuses me, is in the [HIVE-27513](https://cwiki.apache.org/confluence/display/Hive/Different+TIMESTAMP+types) the `with local time zone` should result in an `Instant`, but in the PR we have a `OffsetDateTime`. So I think we're also affecting the behavior here on `with time zone`.

**Comment by SourabhBadhya** [comment]
Thanks @Fokko , @rdblue for the reviews.

Currently, Hive supports only `TIMESTAMP WITH LOCAL TIME ZONE`. There is no `TIMESTAMP WITH TIME ZONE` type in Hive. Please refer [HIVE-16614](https://issues.apache.org/jira/browse/HIVE-16614) especially this [comment](https://issues.apache.org/jira/browse/HIVE-16614?focusedCommentId=16140755&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16140755). I also checked the current Hive implementation and was able to verify the same.

Answering the questions raised - 
> How do we handle TIMESTAMP WITH LOCAL TIME ZONE? Do we need a specific reader for it?

`IcebergTimestampWithZoneObjectInspectorHive3.java` is the reader for `TIMESTAMP WITH LOCAL TIME ZONE` since it extends `TimestampLocalTZObjectInspector` interface and there is no `TIMESTAMP WITH TIME ZONE` type currently supported by Hive.

> What is the behavior with respect to the session time zone of that type? What is responsible for conversion?

`TIMESTAMP WITH LOCAL TIME ZONE` type is supposed to return the timestamp data in the timezone of the session. 
Currently, the time zone of a session is fetched here as follows - 
```
  /**
   * A TimestampTZTypeInfo with system default time zone.
   */
  public static final TimestampLocalTZTypeInfo timestampLocalTZTypeInfo = new TimestampLocalTZTypeInfo(
      ZoneId.systemDefault().getId());
```
Source - https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoFactory.java#L72-L73

This `timestampLocalTZTypeInfo` object is used by the constructor of `IcebergTimestampWithZoneObjectInspectorHive3.java` -
```
  private IcebergTimestampWithZoneObjectInspectorHive3() {
    super(TypeInfoFactory.timestampLocalTZTypeInfo);
  }
```
So essentially the timezone picked is the session timezone.

**This PR make use of session timezone while constructing primitive Java objects**.

> What is the session time zone?
```
  /**
   * A TimestampTZTypeInfo with system default time zone.
   */
  public static final TimestampLocalTZTypeInfo timestampLocalTZTypeInfo = new TimestampLocalTZTypeInfo(
      ZoneId.systemDefault().getId());
```
The session time zone is the system default time zone where the cluster is running.

**Comment by SourabhBadhya** [comment]
@Fokko , @rdblue did you have a chance to check this. Please review.

**Comment by rdblue** [comment]
If the zone is determined by `ZoneId.systemDefault().getId()`, how is that correct? That is Java's default time zone, not the time zone of the SQL session as required by the type. Is that how Hive keeps track of the session time zone? If so, how does that work when there are multiple sessions?

**Comment by SourabhBadhya** [comment]
@rdblue AFAIK, Hive uses JVM default time zone as the timezone of the session. For `TIMESTAMP WITH LOCAL TIME ZONE` type, if multiple sessions are present running on different timezones, then each session will return the data corresponding to the timezone where the session is currently running. The underlying data can be written in any timezone, however, Hive must convert such values to the time zone of that session which is consistent with the behaviour of the `TIMESTAMP WITH LOCAL TIME ZONE` type.

**Comment by SourabhBadhya** [comment]
@rdblue @Fokko Please check this and review.

**Comment by rdblue** [comment]
@wypoon, is there someone from Hive that could help answer some of the questions in this PR? For example, how does Hive track the SQL session time zone?

**Comment by wypoon** [comment]
@rdblue I think @pvary should be able to help, even though he may not be working on Hive now.

**Comment by deniskuzZ** [comment]
[HIVE-16614](https://issues.apache.org/jira/browse/HIVE-16614): Support "set local time zone" statement 
````
ZoneId timeZone = SessionState.get() == null ? 
    new HiveConf().getLocalTimeZone() :
    SessionState.get().getConf().getLocalTimeZone();

public ZoneId getLocalTimeZone() {
  String timeZoneStr = getVar(ConfVars.HIVE_LOCAL_TIME_ZONE);
  return TimestampTZUtil.parseTimeZone(timeZoneStr);
}
public static ZoneId parseTimeZone(String timeZoneStr) {
    if (timeZoneStr == null || timeZoneStr.trim().isEmpty() ||
        timeZoneStr.trim().toLowerCase().equals("local")) {
      // default
      return ZoneId.systemDefault();
    }
    try {
      return ZoneId.of(timeZoneStr);
    } catch (DateTimeException e1) {
      // default
      throw new RuntimeException("Invalid time zone displacement value", e1);
    }
  }
````

**Comment by SourabhBadhya** [comment]
@rdblue @Fokko Can you please check again and review. From @deniskuzZ comment (thanks Denys for the information), we can see that by default the session timezone used by Hive is the JVM timezone.

**Comment by SourabhBadhya** [comment]
@rdblue @Fokko Please check this and review.

**Comment by pvary** [comment]
> @pvary would you have any spare cycles to look into this?

I will be out of office in the next week, but I can take a look after that.

@SourabhBadhya, in the meantime, could you please make sure that Hive 3 works in the same way as Hive 4? I remember that there were a big overhaul of timestamps in Hive 3, and there were some issues there what we were able to fix only in Hive 4. Since Iceberg only supports Hive 3 ATM, we should make sure, that this fix works with it too.

**Comment by pvary** [comment]
@SourabhBadhya: Have you been able to check the changes against Hive3?

**Comment by rdblue** [comment]
> From @deniskuzZ comment (thanks Denys for the information), we can see that by default the session timezone used by Hive is the JVM timezone.

The question isn't how the default is determined. What we need to know is how the session time zone is passed. This uses the default JVM timezone not the session timezone, which seems incorrect to me.

**Comment by deniskuzZ** [comment]
> > From @deniskuzZ comment (thanks Denys for the information), we can see that by default the session timezone used by Hive is the JVM timezone.
> 
> The question isn't how the default is determined. What we need to know is how the session time zone is passed. This uses the default JVM timezone not the session timezone, which seems incorrect to me.

I've shared the code above:
set hive.local.time.zone=Europe/London;

    HIVE_LOCAL_TIME_ZONE("hive.local.time.zone", "LOCAL",
        "Sets the time-zone for displaying and interpreting time stamps. If this property value is set to\n" +
        "LOCAL, it is not specified, or it is not a correct time-zone, the system default time-zone will be\n " +
        "used instead. Time-zone IDs can be specified as region-based zone IDs (based on IANA time-zone data),\n" +
        "abbreviated zone IDs, or offset IDs."),

````
public ZoneId getLocalTimeZone() {
  String timeZoneStr = getVar(ConfVars.HIVE_LOCAL_TIME_ZONE);
  return TimestampTZUtil.parseTimeZone(timeZoneStr);
}
SessionState.get().getConf().getLocalTimeZone()
````

**Pull request closed without merging**
