### PR TITLE
Dell: Package dell module into runtime JARs.

### PR DESCRIPTION
**Pull request by wang-x-xia**

### CODE REVIEW

**Comment by rdblue** [comment]
@wang-x-xia, we will need to update the LICENSE and NOTICE file for all of the additional files that are brought in by this change. Can you paste a copy of the module's dependency tree and all of the new files that this adds to the Iceberg Spark 3.2 runtime Jar?

**Comment by wang-x-xia** [comment]
@rdblue 
The dell module has no external **runtime** dependencies now.
Should I prepare the LICENSE of **compile-only** dependencies, that won't be in the runtime Jar?

**Comment by rdblue** [comment]
@wang-x-xia, if there are no additional runtime dependencies, that's great. We may not need to update anything.

Still, can you paste a copy of the module's dependency tree and all of the new files that this adds to the Iceberg Spark 3.2 runtime Jar?

**Comment by wang-x-xia** [comment]
Module dependency:
```
:iceberg-core
:iceberg-common
:iceberg-bundled-guava
```
Full dependencies tree:
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.slf4j:slf4j-api -> 1.7.30
+--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
+--- project :iceberg-core
|    +--- project :iceberg-api
|    |    +--- org.slf4j:slf4j-api -> 1.7.30
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    \--- project :iceberg-bundled-guava
|    +--- org.slf4j:slf4j-api -> 1.7.30
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-common
|    |    +--- org.slf4j:slf4j-api -> 1.7.30
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    \--- project :iceberg-bundled-guava
|    +--- project :iceberg-bundled-guava
|    +--- org.apache.avro:avro -> 1.10.1
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.3 -> 2.11.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.3 -> 2.11.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.4
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.11.4
|    |    +--- org.apache.commons:commons-compress:1.20
|    |    \--- org.slf4j:slf4j-api:1.7.30
|    +--- org.apache.httpcomponents.client5:httpclient5 -> 5.1
|    |    +--- org.apache.httpcomponents.core5:httpcore5:5.1.1
|    |    +--- org.apache.httpcomponents.core5:httpcore5-h2:5.1.1
|    |    |    \--- org.apache.httpcomponents.core5:httpcore5:5.1.1
|    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
|    |    \--- commons-codec:commons-codec:1.15
|    +--- com.fasterxml.jackson.core:jackson-databind -> 2.11.4 (*)
|    +--- com.fasterxml.jackson.core:jackson-core -> 2.11.4
|    +--- com.github.ben-manes.caffeine:caffeine -> 2.9.3
|    |    +--- org.checkerframework:checker-qual:3.19.0
|    |    \--- com.google.errorprone:error_prone_annotations:2.10.0
|    \--- org.roaringbitmap:RoaringBitmap -> 0.9.22
|         \--- org.roaringbitmap:shims:0.9.22
+--- project :iceberg-common (*)
\--- project :iceberg-bundled-guava
```
Added files:

```
org/apache/iceberg/dell:
'DellClientFactories$DefaultDellClientFactory.class'
DellClientFactories.class
DellClientFactory.class
DellProperties.class
ecs

org/apache/iceberg/dell/ecs:
BaseEcsFile.class
EcsAppendOutputStream.class
'EcsCatalog$Properties.class'
EcsCatalog.class
EcsFileIO.class
EcsInputFile.class
EcsOutputFile.class
EcsSeekableInputStream.class
EcsTableOperations.class
EcsURI.class
PropertiesSerDesUtil.class
```

**Comment by wang-x-xia** [comment]
@rdblue I'm not familiar with these things. If you have examples, I can re-check these dependencies and files.

**Comment by rdblue** [comment]
@wang-x-xia, I don't see iceberg-dell in that dependency tree. We need to see the specific dependencies of the iceberg-dell module that are now transitive dependencies of other modules after this PR.

**Comment by wang-x-xia** [comment]
```
------------------------------------------------------------
Project ':iceberg-spark:iceberg-spark-runtime-3.2_2.12'
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
+--- project :iceberg-api
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    \--- project :iceberg-bundled-guava
+--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
+--- project :iceberg-spark:iceberg-spark-3.2_2.12
|    +--- project :iceberg-api (*)
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-bundled-guava
|    +--- project :iceberg-common
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    \--- project :iceberg-bundled-guava
|    +--- project :iceberg-core
|    |    +--- project :iceberg-api (*)
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    +--- project :iceberg-common (*)
|    |    +--- project :iceberg-bundled-guava
|    |    +--- org.apache.avro:avro -> 1.10.1
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.3 -> 2.11.4
|    |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.11.3 -> 2.11.4
|    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.11.4
|    |    |         \--- com.fasterxml.jackson.core:jackson-core:2.11.4
|    |    +--- org.apache.httpcomponents.client5:httpclient5 -> 5.1
|    |    |    +--- org.apache.httpcomponents.core5:httpcore5:5.1.1
|    |    |    \--- org.apache.httpcomponents.core5:httpcore5-h2:5.1.1
|    |    |         \--- org.apache.httpcomponents.core5:httpcore5:5.1.1
|    |    +--- com.fasterxml.jackson.core:jackson-databind -> 2.11.4 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core -> 2.11.4
|    |    +--- com.github.ben-manes.caffeine:caffeine -> 2.9.3
|    |    |    +--- org.checkerframework:checker-qual:3.19.0
|    |    |    \--- com.google.errorprone:error_prone_annotations:2.10.0
|    |    \--- org.roaringbitmap:RoaringBitmap -> 0.9.22
|    |         \--- org.roaringbitmap:shims:0.9.22
|    +--- project :iceberg-data
|    |    +--- project :iceberg-api (*)
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    +--- project :iceberg-bundled-guava
|    |    +--- project :iceberg-core (*)
|    |    +--- org.apache.orc:orc-core -> 1.7.4
|    |    |    +--- org.apache.orc:orc-shims:1.7.4
|    |    |    +--- io.airlift:aircompressor:0.21
|    |    |    +--- org.jetbrains:annotations:17.0.0
|    |    |    \--- org.threeten:threeten-extra:1.5.0
|    |    \--- org.apache.parquet:parquet-avro -> 1.12.2
|    |         +--- org.apache.parquet:parquet-column:1.12.2
|    |         |    +--- org.apache.parquet:parquet-common:1.12.2
|    |         |    |    +--- org.apache.parquet:parquet-format-structures:1.12.2
|    |         |    |    \--- org.apache.yetus:audience-annotations:0.12.0
|    |         |    \--- org.apache.parquet:parquet-encoding:1.12.2
|    |         |         \--- org.apache.parquet:parquet-common:1.12.2 (*)
|    |         +--- org.apache.parquet:parquet-hadoop:1.12.2
|    |         |    +--- org.apache.parquet:parquet-column:1.12.2 (*)
|    |         |    +--- org.apache.parquet:parquet-format-structures:1.12.2
|    |         |    \--- org.apache.parquet:parquet-jackson:1.12.2
|    |         \--- org.apache.parquet:parquet-format-structures:1.12.2
|    +--- project :iceberg-orc
|    |    +--- project :iceberg-api (*)
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    +--- project :iceberg-bundled-guava
|    |    +--- project :iceberg-common (*)
|    |    +--- project :iceberg-core (*)
|    |    +--- org.apache.avro:avro -> 1.10.1 (*)
|    |    \--- org.apache.orc:orc-core -> 1.7.4 (*)
|    +--- project :iceberg-parquet
|    |    +--- project :iceberg-api (*)
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    +--- project :iceberg-bundled-guava
|    |    +--- project :iceberg-core (*)
|    |    +--- project :iceberg-common (*)
|    |    \--- org.apache.parquet:parquet-avro -> 1.12.2 (*)
|    +--- project :iceberg-arrow
|    |    +--- project :iceberg-api (*)
|    |    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    |    +--- project :iceberg-bundled-guava
|    |    +--- project :iceberg-core (*)
|    |    +--- project :iceberg-parquet (*)
|    |    +--- org.apache.arrow:arrow-vector -> 7.0.0
|    |    |    +--- org.apache.arrow:arrow-format:7.0.0
|    |    |    |    \--- com.google.flatbuffers:flatbuffers-java:1.12.0
|    |    |    +--- org.apache.arrow:arrow-memory-core:7.0.0
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.11.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.11.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.11.4 (*)
|    |    |    \--- com.google.flatbuffers:flatbuffers-java:1.12.0
|    |    +--- org.apache.arrow:arrow-memory-netty -> 7.0.0
|    |    |    \--- org.apache.arrow:arrow-memory-core:7.0.0
|    |    +--- org.apache.parquet:parquet-avro -> 1.12.2 (*)
|    |    \--- io.netty:netty-buffer -> 4.1.68.Final
|    |         \--- io.netty:netty-common:4.1.68.Final
|    +--- org.scala-lang.modules:scala-collection-compat_2.12 -> 2.6.0
|    |    \--- org.scala-lang:scala-library:2.12.15
|    +--- org.apache.parquet:parquet-column -> 1.12.2 (*)
|    +--- org.apache.parquet:parquet-hadoop -> 1.12.2 (*)
|    +--- org.apache.orc:orc-core -> 1.7.4 (*)
|    \--- org.apache.arrow:arrow-vector -> 7.0.0 (*)
+--- project :iceberg-spark:iceberg-spark-extensions-3.2_2.12
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    \--- org.scala-lang.modules:scala-collection-compat_2.12 -> 2.6.0 (*)
+--- project :iceberg-aws
|    +--- project :iceberg-api (*)
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-bundled-guava
|    +--- project :iceberg-common (*)
|    \--- project :iceberg-core (*)
+--- project :iceberg-aliyun
|    +--- project :iceberg-api (*)
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-bundled-guava
|    +--- project :iceberg-core (*)
|    \--- project :iceberg-common (*)
+--- project :iceberg-hive-metastore
|    +--- project :iceberg-api (*)
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-bundled-guava
|    +--- project :iceberg-core (*)
|    +--- project :iceberg-common (*)
|    \--- com.github.ben-manes.caffeine:caffeine -> 2.9.3 (*)
+--- project :iceberg-dell
|    +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
|    +--- project :iceberg-core (*)
|    +--- project :iceberg-common (*)
|    \--- project :iceberg-bundled-guava
\--- project :iceberg-nessie
     +--- project :iceberg-api (*)
     +--- com.github.stephenc.findbugs:findbugs-annotations -> 1.3.9-1
     +--- project :iceberg-common (*)
     +--- project :iceberg-core (*)
     +--- project :iceberg-bundled-guava
     +--- org.projectnessie:nessie-client -> 0.29.0
     |    \--- org.projectnessie:nessie-model:0.29.0
     +--- com.fasterxml.jackson.core:jackson-databind -> 2.11.4 (*)
     \--- com.fasterxml.jackson.core:jackson-core -> 2.11.4
```

**Comment by wang-x-xia** [comment]
@rdblue 
Sorry to mention you late. Should I update some other things?

**Pull request closed without merging**
