### PR TITLE
Spark 3.5: Fix specific field values treated as unequal while comparing rows for carry-over removal

### PR DESCRIPTION
**Pull request by mkluo8787**
This change fixes a bug that a carry-over row might be mistaken as change, due to the changelog iterators perform comparison based on Java object equality instead of row equality in Spark.

- Add test cases that unveil the bug (Binary field; also add Float/Double NaN to ensure Spark row equality is respected).
- Only covers Spark 3.5 for now; will port to 3.3 & 3.4 after approval.
- An performance implication of this change is that all the fields to be compared have to be materialized into a new GenericRow at once (instead of being checked 1-by-1).

### CODE REVIEW

**Comment by mkluo8787** [comment]
@flyrain Would you mind having a look at it?

**Comment by flyrain** [comment]
I will take a look.

**Review by flyrain — COMMENTED** [review]
Hi @mkluo8787,  thanks for catching this. LGTM overall. Using the `Row.equal()` seems a good option overall. Another option is to implement the same logic here, which may be a bit faster. 
There are two perf concerns
1.  Materializing all columns needed as you mentioned.
2. Creating a new Spark Generic Row
Can we benchmark it a bit? We can do that in a unit test by timing two methods, and compare the results.
```
startTime = System.currentTimeMillis()
method1()
delta = System.currentTimeMillis() - startTime

startTime = System.currentTimeMillis()
method2()
delta = System.currentTimeMillis() - startTime
```

**Comment by flyrain** [comment]
cc @aokolnychyi  @RussellSpitzer

**Comment by rdblue** [comment]
What's the argument for including this in 1.4.1? It seems like a behavior change that isn't fixing a regression.

**Comment by flyrain** [comment]
Hi @rdblue, yes, we don't have to include it in 1.4.1 if it is behavior change. I'd consider it more a bug fix though. But open for ideas.

**Comment by mkluo8787** [comment]
@flyrain Thanks for the review. I will provide some benchmark soon.
As for the alternative option to implementing the same logic here, I'm afraid that it poses a risk of logic duplication which could possibly lead to bugs that are harder to detect in the future.

On the other hand, I'm +1 on considering this PR a bug fix, 
as the carried-over rows are not expected in changelog views by default, which is a documented behavior.

**Comment by flyrain** [comment]
> As for the alternative option to implementing the same logic here, I'm afraid that it poses a risk of logic duplication which could possibly lead to bugs that are harder to detect in the future.

Agreed. Hopefully, we don't need to go that direction.

It is a bug fix, but not necessarily blocks 1.4.1, I'm OK to put it in a future release.

**Pull request closed without merging**
