### PR TITLE
relativePath [wip]

### PR DESCRIPTION
**Pull request by mohitgargk**
**Basic changes**

- [x] Capitalise on `LocationProvider` to relativeize by adding new behavior `LocationRelativizer`
- [x] No changes in spec
- [x] No changes in the value of the metadata objects. 

**File Path Changes**
Only their read and write parsers are passed with location-provider

- [ ] `metadata-log` in `***-metadata.json`: Changes around `TableMetadataParser`
- [ ] `manifest-list` in `***-metadata.json`: Changes around `SnapshotParser` 
- [ ] `manifest_path` in `snap-*.avro` file :  Changes around TBF
- [ ] `data_file.file_path loc` in `*-mx.avro` file : Changes around TBF
- [ ] `StatisticsFile.path`
- [ ] `table_location` ??
- [ ] datafile path in delete-file ??

**Ops support**

- [ ] `HadoopTableOperation`
- [ ] `BaseMetastoreTableOperations`
- [ ] Other ??

**Engines Covered**
- [ ] Iceberg API
- [ ] Spark
- [ ] Trino
- [ ] Flink
- [ ] Others

**Design Spec**
[Iceberg Table Portability](https://docs.google.com/document/d/1q-pWhI8A8_T_zbxKoZ7Lg02ybz87kHrNP9zbm9p0RQk/edit#heading=h.scxi2ozdex3)

### CODE REVIEW

**Comment by manuzhang** [comment]
Do we have a design doc for this feature?

**Comment by mohitgargk** [comment]
> Do we have a design doc for this feature?

Should be ready by this week. Will provide link in this thread.

**Comment by zinking** [comment]
does it handle the case where we pointed the data directory somewhere else ?

**Comment by mohitgargk** [comment]
> does it handle the case where we pointed the data directory somewhere else ?

Yes.

@manuzhang added the design in the description

**Comment by manuzhang** [comment]
@mohitgargk you may send the design doc to dev list for review.

**Comment by rustyconover** [comment]
Hi All, I love the idea of this spec, I'm especially interested in using Iceberg with S3 replication for disaster recovery with S3 replication. 

There will be challenges with the Glue catalog specifically. But I have ideas how to over come them.  Additionally with S3 replication there can be time where all of the contents of a table snapshot are not yet replicated, so it would be useful to track which "snapshot" is available at each location where the table is replicated.  Again, this is possible to do for S3 but I'm unsure of other storage systems.

From reading the google doc, it is not especially clear what is proposed.  There are many "alternatives" proposed and I couldn't divine the actual proposal's TL;DR action points.

Personally, I was thinking of solving this challenge with a map of a "location" string to a regular expression to apply to all table URIs.  Each catalog instance could specify their "location" using a URI parameter added to the `metadata.json` current_metadata.  An example could be for a table in us-east-2 replicated from us-east-1.

`s3://bucket-us-east-2/database/table_name/data/[uuid].metadata.json?location=aws:us-east-2`

The Iceberg table's metadata would have a property called "location_replacements" which would be a JSON string of a serialized map from each "location" to a regular expression to perform on all URI references.

```
metadata.table.location_replacements = {
  "aws:us-east-2": "s/^s3:\/\/bucket-us-east-1\//s3:\/\/bucket-us-east-2/"
}
```

The regular expression substitution would mean paths that normally reference `bucket-us-east-1` would reference `bucket-us-east-2` when reading the catalog from that "location".

The location replacements map would contain a "stringified" regular expression that can be applied all URIs that are contained in the table.  The use of regular expressions would allow a lot of flexibility, but bring a moderate amount of complexity.  Regular expressions could allow tables to be at different relative paths depending on storage media.

Since this will change almost every client of Iceberg this spec should likely have more eyes on it.

@fokko your thoughts from the Python perspective?

**Comment by ajantha-bhat** [comment]
Are we still working on it? Looks like there are some interest from the community also.

**Pull request closed without merging**
