### PR TITLE
Hive: Flaky test testScanTable org.apache.iceberg.mr.hive.TestHiveIcebergStorageHandlerWithCustomCatalog (#1817)

### PR DESCRIPTION
**Pull request by pvary**
Test out repro

### CODE REVIEW

**Comment by shardulm94** [comment]
@pvary There was a failure in https://github.com/apache/iceberg/pull/1827/checks?check_run_id=1454358891, not sure if it's the same one you are trying to repro.

**Comment by pvary** [comment]
> @pvary There was a failure in https://github.com/apache/iceberg/pull/1827/checks?check_run_id=1454358891, not sure if it's the same one you are trying to repro.

Yes, this is the one

**Comment by pvary** [comment]
@rdblue or @shardulm94: Could you please review? Without the patch we had 2/4 failures, with the patch we have 4 straight green runs. I think this fixes the flakiness, and it is a test only failure where multiple Metrics server is instantiated in a single JVM. HBase used the same fix in some of their tests, so I think it is safe to do here as well.

Thanks,
Peter

**Comment by rdblue** [comment]
Thanks @pvary! Looks good to me. Nice work tracking this down.

**Pull request merged**
