### PR TITLE
Bump to Apache Spark 2.4.6

### PR DESCRIPTION
**Pull request by Fokko**
Bump to the latest minor version of Apache Spark

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Spark 2.4.7 release process is already in progress - there has been correctness issues which delay the process, but I expect that won't hold months. Given we bump the Spark version, would we like to pick 2.4.7 instead once it is available?

**Comment by rdblue** [comment]
@HeartSaVioR, yes. I think we should continue to update to patch releases for our dependencies.

**Comment by rdblue** [comment]
Merged! Thanks @Fokko!

**Comment by Fokko** [comment]
https://github.com/apache/iceberg/pull/1646

**Pull request merged**
