### PR TITLE
Upgrade ORC dependency to 1.7.0

### PR DESCRIPTION
**Pull request by williamhyun**
This PR aims to bump ORC to version 1.7.0.

[Apache ORC 1.7.0](https://orc.apache.org/news/2021/09/15/ORC-1.7.0/) is a new release with the following new features and improvements.

ORC-377 Support Snappy compression in C++ Writer
ORC-577 Support row-level filtering
ORC-716 Build and test on Java 17-EA
ORC-731 Improve Java Tools
ORC-742 LazyIO of non-filter columns
ORC-751 Implement Predicate Pushdown in C++ Reader
ORC-755 Introduce OrcFilterContext
ORC-757 Add Hashtable implementation for dictionary
ORC-780 Support LZ4 Compression in C++ Writer
ORC-797 Allow writers to get the stripe information
ORC-818 Build and test in Apple Silicon
ORC-861 Bump CMake minimum requirement to 2.8.12
ORC-867 Upgrade hive-storage-api to 2.8.1
ORC-984 Save the software version that wrote each ORC file

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

cc @aokolnychyi , @RussellSpitzer , @kbendick

**Comment by RussellSpitzer** [comment]
All tests pass, looks good to merge. Thanks @williamhyun + @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you so much, @RussellSpitzer .

**Comment by williamhyun** [comment]
Thank you @RussellSpitzer and @dongjoon-hyun !

**Pull request merged**
