### PR TITLE
Spark: Use Awaitility instead of Thread.sleep

### PR DESCRIPTION
**Pull request by yyy1000**
From the comment, https://github.com/apache/iceberg/issues/7154#issuecomment-1785003366
There're some places can be replaced with Awaitlity.
Here I only change TestCopyOnWriteDelete.java, because I don't know whether I'm in the correct path.
After reviewing, I can inspect other places.
Part of #7154 
:)

### CODE REVIEW

**Review by nk1506 — CHANGES_REQUESTED** [review]
Please change for other spark version too like 3.2,3.3,3.4.

**Comment by yyy1000** [comment]
> Please change for other spark version too like 3.2,3.3,3.4.

Sure, I just change a single version for review to verify I'm doing right. :)

**Comment by yyy1000** [comment]
Hi, @nk1506
It seems that my code can't pass the unit tests.
Is it because of the default waiting time is not enough? Do you have any ideas?

**Comment by yyy1000** [comment]
> > Hi, @nk1506 It seems that my code can't pass the unit tests. Is it because of the default waiting time is not enough? Do you have any ideas?
> 
> Please refer [here](https://github.com/apache/iceberg/blob/6a9d3c77977baff4295ee2dde0150d73c8c46af1/aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogLock.java#L146) . Also it is advisable to set the `atMost` too.

Oh, got it. I should use condition 'or' but not 'and'. :) Now the unit test can run in my local env.
Awaitliity use default timeout of 10 seconds, and I think it is enough in this case. https://github.com/awaitility/awaitility/wiki/Usage#defaults
So adding a 'atMost' seems not necessary here. What do you think?

**Comment by yyy1000** [comment]
Hi, I want to make an update of this PR:
The CI failed indicated that : 
```
Caused by:
            org.apache.iceberg.exceptions.CommitFailedException: Base metadata location  
'file:/tmp/hive436356614419280460/table/metadata/00034-1cf322a5-e28e-4bbe-a4b1-aa2d3dad3d00.metadata.json' 
is not same as the current table metadata location 'file:/tmp/hive436356614419280460/table/metadata/00035-ed8bc810-ddbf-4b41-b38d-9bb2efdbdc4a.metadata.json' for default.table 
```

However, if I fall back to the old version using 'sleep()', it still shows the same error after `WARN Tasks: Retrying task after failure: Base metadata location  is not the same`.
So I'm thinking the error is not not because I change 'sleep' to 'await'

**Comment by nastra** [comment]
@yyy1000 sorry I completely missed that this PR exists. Could you please rebase and fix the merge conflicts? It would be great to get this in. Also Let's first only focus on Spark 3.5 changes. We can open a separate PR later to backport to changes to earlier Spark versions

**Comment by yyy1000** [comment]
> @yyy1000 sorry I completely missed that this PR exists. Could you please rebase and fix the merge conflicts? It would be great to get this in. Also Let's first only focus on Spark 3.5 changes. We can open a separate PR later to backport to changes to earlier Spark versions

@nastra Cool, could do it next few days!

**Pull request closed without merging**
