### PR TITLE
Flink: Delete the data when UPDATE_BEFORE

### PR DESCRIPTION
**Pull request by linfey90**
Usually when we update data, we have an -U and +U in Changelog.But When we add a condition in CDC synchronization, such as rate>10, we insert a data greater than 10 in the source, such as mysql, and the condition will be met. When we modify the data less than 10, the condition will not be met, and only a -U will be transmitted. If does not delete the data when UPDATE_BEFORE, our results will be incorrect,so I think UPDATE_BEFORE is also necessary for UPSERT, when there have not UPDATE_AFTER.
the sql like: insert into hive_catalog.dm_ods.basic_ods select * from dm_mapping.default_catalog.basic_source where rate > 20;

### CODE REVIEW

**Comment by pvary** [comment]
@linfey90: Could you please add a test case which fails before the fix, and successful after the fix, so we can prevent a possible later regression?

Thanks, Peter

**Comment by stevenzwu** [comment]
Is this a problem with the CDC source? should CDC source generate a `DELETE` in this case?

Looking at the Flink Javadoc, it seems that UPDATE_BEFORE should go with  UPDATE_AFTER hand-to-hand.
```
    /**
     * Update operation with the previous content of the updated row.
     *
     * <p>This kind SHOULD occur together with {@link #UPDATE_AFTER} for modelling an update that
     * needs to retract the previous row first. It is useful in cases of a non-idempotent update,
     * i.e., an update of a row that is not uniquely identifiable by a key.
     */
    UPDATE_BEFORE("-U", (byte) 1),
```

**Comment by linfey90** [comment]
> 

I don't think this is a CDC problem. UPDATE_BEFORE and UPDATE_AFTER were also generated together, but UPDATE_AFTER was filtered out because it did not meet the conditions.

**Comment by linfey90** [comment]
> @linfey90: Could you please add a test case which fails before the fix, and successful after the fix, so we can prevent a possible later regression?
> 
> Thanks, Peter

test added, but the two cases cannot occur at the same time.Please take a look again,thanks!

**Pull request closed without merging**
