### PR TITLE
Build: Remove links checker

### PR DESCRIPTION
**Pull request by Fokko**
I introduced this Github Actions workflow a while ago, but it turned out to be a mistake. Running the links checker from the CI turns out the be very flaky: https://github.com/apache/iceberg/pull/10397 Let's remove it for now.

cc @manuzhang @pvary

### CODE REVIEW

**Review by manuzhang — APPROVED** [review]

**Comment by manuzhang** [comment]
@Fokko we need to remove the config file as well.

**Comment by Fokko** [comment]
@manuzhang I was thinking of leaving in the link checker, but just removing it from the CI for now. You could still run it locally: https://github.com/apache/iceberg/tree/main/site#validate-links WDYT?

**Review by manuzhang — APPROVED** [review]

**Review by pvary — APPROVED** [review]

**Comment by manuzhang** [comment]
@Fokko I'm good with leaving in the link checker, but we need to update the README which refers to another [python linkchecker](https://github.com/linkchecker/linkchecker).

**Comment by Fokko** [comment]
@manuzhang Good catch, that one was originally added by @bitsondatadev. Let's keep that one in, it works pretty well:

```
Downloaded: 345.3MB.
Content types: 96 image, 19112 text, 0 video, 0 audio, 30 application, 10 mail and 1108 other.
URL lengths: min=16, max=899, avg=95.

That's it. 20356 links in 20363 URLs checked. 10 warnings found. 92 errors found.
Stopped checking at 2024-06-03 23:33:07+002 (1 hour, 59 minutes)
```

Current broken links:

```
➜  Desktop cat link_warnings.csv 
# created by LinkChecker at 2024-06-03 21:33:16+002
# Read the documentation at https://linkchecker.github.io/linkchecker/
# Write comments and bugs to https://github.com/linkchecker/linkchecker/issues
urlname;parentname;base;result;warningstring;infostring;valid;url;line;column;name;dltime;size;checktime;cached;level;modified
./spark-quickstart;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/spark-quickstart/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/spark-quickstart/;532;17;Learn More;0.004957914352416992;264986;3.3083157539367676;0;1;
javadoc/nightly;https://iceberg.apache.org/;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/nightly;2194;7;Javadoc;-1;173;3.467215061187744;0;1;
javadoc/latest;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/javadoc/latest/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/javadoc/latest/;3461;7;Javadoc;0.0008671283721923828;21105;3.9953861236572266;0;1;
javadoc/1.4.3;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/javadoc/1.4.3/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/javadoc/1.4.3/;8571;7;Javadoc;4.38690185546875e-05;2879;2.7433459758758545;0;1;
javadoc/1.4.2;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/javadoc/1.4.2/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/javadoc/1.4.2/;9859;7;Javadoc;7.605552673339844e-05;2879;2.712697744369507;0;1;
/hive-quickstart;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/hive-quickstart/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/hive-quickstart/;13172;15;Hive Quickstart;0.0016748905181884766;224452;3.2236311435699463;0;1;
/docs/latest;https://iceberg.apache.org/;;200 OK;Redirected to `https://iceberg.apache.org/docs/latest/' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/docs/latest/;13174;15;Docs;0.0069789886474609375;212188;3.4555227756500244;0;1;
docs/latest/configuration.md#catalog-properties;https://iceberg.apache.org/concepts/catalog/;;404 Not Found;;;False;https://iceberg.apache.org/concepts/catalog/docs/latest/configuration.md#catalog-properties;12858;268;Iceberg documentation;-1;173;4.389556884765625;0;2;
../spark-configuration.md;https://iceberg.apache.org/docs/latest/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-configuration.md;13181;45;Spark catalogs;-1;173;4.4612250328063965;0;2;
../branching.md;https://iceberg.apache.org/docs/latest/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/branching.md;13337;50;branches;-1;173;4.511567831039429;0;2;
../configuration.md#write-properties;https://iceberg.apache.org/docs/latest/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/configuration.md#write-properties;13478;18;write.target-file-size-bytes;-1;173;4.392493009567261;0;2;
../../javadoc/1.5.2/org/apache/iceberg/rest/RESTMetricsReporter.html;https://iceberg.apache.org/docs/nightly/metrics-reporting/;;404 Not Found;;;False;https://iceberg.apache.org/docs/javadoc/1.5.2/org/apache/iceberg/rest/RESTMetricsReporter.html;13110;30;RESTMetricsReporter;-1;173;3.383600950241089;0;2;
../metrics-reporting.md;https://iceberg.apache.org/docs/latest/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/metrics-reporting.md;13443;85;Metrics reporting;-1;173;4.443686246871948;0;2;
../spark-ddl.md#create-table;https://iceberg.apache.org/docs/latest/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-ddl.md#create-table;13019;126;CREATE TABLE;-1;173;4.3034961223602295;0;2;
../spark-writes.md#insert-into;https://iceberg.apache.org/docs/latest/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-writes.md#insert-into;13031;50;INSERT INTO;-1;173;4.069953918457031;0;2;
../spark-queries.md#inspecting-tables;https://iceberg.apache.org/docs/latest/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-queries.md#inspecting-tables;13051;39;inspect tables;-1;173;4.056831121444702;0;2;
../spark-procedures.md;https://iceberg.apache.org/docs/latest/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-procedures.md;13285;5;Maintaining tables;-1;173;4.3212127685546875;0;2;
../api.md#table-metadata;https://iceberg.apache.org/docs/latest/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/api.md#table-metadata;13267;189;Table API;-1;173;4.063881874084473;0;2;
../spark-getting-started.md#spark-type-to-iceberg-type;https://iceberg.apache.org/docs/latest/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/spark-getting-started.md#spark-type-to-iceberg-type;13573;109;type compatibility on creating table;-1;173;3.992018938064575;0;2;
../partitioning.md;https://iceberg.apache.org/docs/latest/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/partitioning.md;13592;84;hidden partitions;-1;173;4.2015769481658936;0;2;
../maintenance.md#expire-snapshots;https://iceberg.apache.org/docs/latest/spark-structured-streaming/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/maintenance.md#expire-snapshots;13039;251;regularly maintained;-1;173;4.194529056549072;0;2;
../flink-ddl.md#create-catalog;https://iceberg.apache.org/docs/latest/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-ddl.md#create-catalog;13090;5;SQL create catalog;-1;173;4.015231132507324;0;2;
../flink-queries.md#reading-with-sql;https://iceberg.apache.org/docs/latest/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-queries.md#reading-with-sql;13120;5;SQL select;-1;173;3.652297019958496;0;2;
../flink-writes.md#insert-into;https://iceberg.apache.org/docs/latest/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-writes.md#insert-into;13125;5;SQL insert into;-1;173;3.872192859649658;0;2;
../flink-actions.md#rewrite-files-action;https://iceberg.apache.org/docs/latest/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-actions.md#rewrite-files-action;13155;5;Rewrite files action;-1;173;4.149808883666992;0;2;
../flink.md#adding-catalogs;https://iceberg.apache.org/docs/latest/flink-connector/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink.md#adding-catalogs;12889;159;custom catalog;-1;173;4.142039060592651;0;2;
../flink-configuration.md#read-options;https://iceberg.apache.org/docs/latest/flink-queries/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-configuration.md#read-options;13404;10;Flink Configuration;-1;173;3.9485859870910645;0;2;
../flink-ddl.md/#primary-key;https://iceberg.apache.org/docs/latest/flink-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/latest/flink-ddl.md/#primary-key;13127;239;primary key;-1;173;3.8337440490722656;0;2;
../metrics-reporting.md;https://iceberg.apache.org/docs/1.5.2/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/metrics-reporting.md;13443;85;Metrics reporting;-1;173;3.573773145675659;0;2;
../spark-configuration.md#catalogs;https://iceberg.apache.org/docs/1.5.2/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-configuration.md#catalogs;13008;23;catalogs;-1;173;3.591926097869873;0;2;
../spark-ddl.md#create-table;https://iceberg.apache.org/docs/1.5.2/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-ddl.md#create-table;13019;126;CREATE TABLE;-1;173;3.4036130905151367;0;2;
../spark-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.2/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-writes.md#insert-into;13031;50;INSERT INTO;-1;173;3.554180145263672;0;2;
../spark-queries.md#inspecting-tables;https://iceberg.apache.org/docs/1.5.2/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-queries.md#inspecting-tables;13051;39;inspect tables;-1;173;3.625243902206421;0;2;
../spark-procedures.md;https://iceberg.apache.org/docs/1.5.2/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-procedures.md;13285;5;Maintaining tables;-1;173;3.5263307094573975;0;2;
../configuration.md#catalog-properties;https://iceberg.apache.org/docs/1.5.2/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/configuration.md#catalog-properties;13109;49;catalog configuration;-1;173;3.5710368156433105;0;2;
../api.md#table-metadata;https://iceberg.apache.org/docs/1.5.2/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/api.md#table-metadata;13267;189;Table API;-1;173;3.326488971710205;0;2;
../spark-getting-started.md#spark-type-to-iceberg-type;https://iceberg.apache.org/docs/1.5.2/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/spark-getting-started.md#spark-type-to-iceberg-type;13573;109;type compatibility on creating table;-1;173;3.6624789237976074;0;2;
../partitioning.md;https://iceberg.apache.org/docs/1.5.2/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/partitioning.md;13592;84;hidden partitions;-1;173;3.8140249252319336;0;2;
../maintenance.md#expire-snapshots;https://iceberg.apache.org/docs/1.5.2/spark-structured-streaming/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/maintenance.md#expire-snapshots;13039;251;regularly maintained;-1;173;3.6379241943359375;0;2;
../branching.md;https://iceberg.apache.org/docs/1.5.2/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/branching.md;13337;50;branches;-1;173;4.055494785308838;0;2;
../flink-ddl.md#create-catalog;https://iceberg.apache.org/docs/1.5.2/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-ddl.md#create-catalog;13090;5;SQL create catalog;-1;173;4.196954011917114;0;2;
../flink-queries.md#reading-with-sql;https://iceberg.apache.org/docs/1.5.2/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-queries.md#reading-with-sql;13120;5;SQL select;-1;173;4.121365070343018;0;2;
../flink-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.2/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-writes.md#insert-into;13125;5;SQL insert into;-1;173;3.9867007732391357;0;2;
../flink-actions.md#rewrite-files-action;https://iceberg.apache.org/docs/1.5.2/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-actions.md#rewrite-files-action;13155;5;Rewrite files action;-1;173;4.1884379386901855;0;2;
../flink.md#adding-catalogs;https://iceberg.apache.org/docs/1.5.2/flink-connector/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink.md#adding-catalogs;12889;159;custom catalog;-1;173;4.282183885574341;0;2;
../flink-configuration.md#read-options;https://iceberg.apache.org/docs/1.5.2/flink-queries/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-configuration.md#read-options;13404;10;Flink Configuration;-1;173;4.273524045944214;0;2;
../flink-ddl.md/#primary-key;https://iceberg.apache.org/docs/1.5.2/flink-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.2/flink-ddl.md/#primary-key;13127;239;primary key;-1;173;4.188436031341553;0;2;
../metrics-reporting.md;https://iceberg.apache.org/docs/1.5.1/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/metrics-reporting.md;13443;85;Metrics reporting;-1;173;3.906481981277466;0;2;
../spark-configuration.md#catalogs;https://iceberg.apache.org/docs/1.5.1/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-configuration.md#catalogs;13008;23;catalogs;-1;173;3.593703031539917;0;2;
../spark-ddl.md#create-table;https://iceberg.apache.org/docs/1.5.1/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-ddl.md#create-table;13019;126;CREATE TABLE;-1;173;3.7813990116119385;0;2;
../spark-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.1/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-writes.md#insert-into;13031;50;INSERT INTO;-1;173;3.7339160442352295;0;2;
../spark-queries.md#inspecting-tables;https://iceberg.apache.org/docs/1.5.1/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-queries.md#inspecting-tables;13051;39;inspect tables;-1;173;3.58073091506958;0;2;
../spark-procedures.md;https://iceberg.apache.org/docs/1.5.1/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-procedures.md;13285;5;Maintaining tables;-1;173;3.5297908782958984;0;2;
../configuration.md#catalog-properties;https://iceberg.apache.org/docs/1.5.1/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/configuration.md#catalog-properties;13109;49;catalog configuration;-1;173;3.35971999168396;0;2;
../api.md#table-metadata;https://iceberg.apache.org/docs/1.5.1/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/api.md#table-metadata;13267;189;Table API;-1;173;3.4883170127868652;0;2;
../spark-getting-started.md#spark-type-to-iceberg-type;https://iceberg.apache.org/docs/1.5.1/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/spark-getting-started.md#spark-type-to-iceberg-type;13573;109;type compatibility on creating table;-1;173;3.0756449699401855;0;2;
../partitioning.md;https://iceberg.apache.org/docs/1.5.1/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/partitioning.md;13592;84;hidden partitions;-1;173;3.0790209770202637;0;2;
../maintenance.md#expire-snapshots;https://iceberg.apache.org/docs/1.5.1/spark-structured-streaming/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/maintenance.md#expire-snapshots;13039;251;regularly maintained;-1;173;3.30810284614563;0;2;
../branching.md;https://iceberg.apache.org/docs/1.5.1/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/branching.md;13337;50;branches;-1;173;3.040060043334961;0;2;
../flink-ddl.md#create-catalog;https://iceberg.apache.org/docs/1.5.1/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-ddl.md#create-catalog;13090;5;SQL create catalog;-1;173;3.1597089767456055;0;2;
../flink-queries.md#reading-with-sql;https://iceberg.apache.org/docs/1.5.1/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-queries.md#reading-with-sql;13120;5;SQL select;-1;173;3.3232619762420654;0;2;
../flink-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.1/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-writes.md#insert-into;13125;5;SQL insert into;-1;173;3.7047553062438965;0;2;
../flink-actions.md#rewrite-files-action;https://iceberg.apache.org/docs/1.5.1/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-actions.md#rewrite-files-action;13155;5;Rewrite files action;-1;173;3.860170841217041;0;2;
../flink.md#adding-catalogs;https://iceberg.apache.org/docs/1.5.1/flink-connector/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink.md#adding-catalogs;12889;159;custom catalog;-1;173;4.1952290534973145;0;2;
../flink-configuration.md#read-options;https://iceberg.apache.org/docs/1.5.1/flink-queries/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-configuration.md#read-options;13404;10;Flink Configuration;-1;173;4.0902931690216064;0;2;
../flink-ddl.md/#primary-key;https://iceberg.apache.org/docs/1.5.1/flink-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.1/flink-ddl.md/#primary-key;13127;239;primary key;-1;173;4.214739799499512;0;2;
../metrics-reporting.md;https://iceberg.apache.org/docs/1.5.0/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/metrics-reporting.md;13443;85;Metrics reporting;-1;173;3.878434896469116;0;2;
../spark-configuration.md#catalogs;https://iceberg.apache.org/docs/1.5.0/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-configuration.md#catalogs;13008;23;catalogs;-1;173;3.62050199508667;0;2;
../spark-ddl.md#create-table;https://iceberg.apache.org/docs/1.5.0/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-ddl.md#create-table;13019;126;CREATE TABLE;-1;173;3.3467109203338623;0;2;
../spark-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.0/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-writes.md#insert-into;13031;50;INSERT INTO;-1;173;3.2581722736358643;0;2;
../spark-queries.md#inspecting-tables;https://iceberg.apache.org/docs/1.5.0/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-queries.md#inspecting-tables;13051;39;inspect tables;-1;173;2.8438777923583984;0;2;
../spark-procedures.md;https://iceberg.apache.org/docs/1.5.0/spark-getting-started/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-procedures.md;13285;5;Maintaining tables;-1;173;2.800053119659424;0;2;
../configuration.md#catalog-properties;https://iceberg.apache.org/docs/1.5.0/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/configuration.md#catalog-properties;13109;49;catalog configuration;-1;173;2.8418149948120117;0;2;
../api.md#table-metadata;https://iceberg.apache.org/docs/1.5.0/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/api.md#table-metadata;13267;189;Table API;-1;173;2.8765859603881836;0;2;
../spark-getting-started.md#spark-type-to-iceberg-type;https://iceberg.apache.org/docs/1.5.0/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/spark-getting-started.md#spark-type-to-iceberg-type;13573;109;type compatibility on creating table;-1;173;3.1545488834381104;0;2;
../partitioning.md;https://iceberg.apache.org/docs/1.5.0/spark-ddl/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/partitioning.md;13592;84;hidden partitions;-1;173;3.1592800617218018;0;2;
../maintenance.md#expire-snapshots;https://iceberg.apache.org/docs/1.5.0/spark-structured-streaming/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/maintenance.md#expire-snapshots;13039;251;regularly maintained;-1;173;3.036151170730591;0;2;
../branching.md;https://iceberg.apache.org/docs/1.5.0/spark-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/branching.md;13337;50;branches;-1;173;3.4628398418426514;0;2;
../flink-ddl.md#create-catalog;https://iceberg.apache.org/docs/1.5.0/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-ddl.md#create-catalog;13090;5;SQL create catalog;-1;173;3.7762222290039062;0;2;
../flink-queries.md#reading-with-sql;https://iceberg.apache.org/docs/1.5.0/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-queries.md#reading-with-sql;13120;5;SQL select;-1;173;4.0090107917785645;0;2;
../flink-writes.md#insert-into;https://iceberg.apache.org/docs/1.5.0/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-writes.md#insert-into;13125;5;SQL insert into;-1;173;4.15201997756958;0;2;
../flink-actions.md#rewrite-files-action;https://iceberg.apache.org/docs/1.5.0/flink/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-actions.md#rewrite-files-action;13155;5;Rewrite files action;-1;173;3.906412124633789;0;2;
../flink.md#adding-catalogs;https://iceberg.apache.org/docs/1.5.0/flink-connector/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink.md#adding-catalogs;12889;159;custom catalog;-1;173;4.021159887313843;0;2;
../flink-configuration.md#read-options;https://iceberg.apache.org/docs/1.5.0/flink-queries/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-configuration.md#read-options;13404;10;Flink Configuration;-1;173;3.9678540229797363;0;2;
../flink-ddl.md/#primary-key;https://iceberg.apache.org/docs/1.5.0/flink-writes/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.5.0/flink-ddl.md/#primary-key;13127;239;primary key;-1;173;3.7273380756378174;0;2;
metrics-reporting;https://iceberg.apache.org/docs/1.4.3/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.4.3/configuration/metrics-reporting;13443;85;Metrics reporting;-1;173;3.2602179050445557;0;2;
../../api#table-metadata;https://iceberg.apache.org/docs/1.4.3/spark-configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/api#table-metadata;13267;189;Table API;-1;173;3.1188650131225586;0;2;
../spark-queries#snapshots;https://iceberg.apache.org/docs/1.4.3/spark-configuration/;;200 OK;Redirected to `https://iceberg.apache.org/docs/1.4.3/spark-queries/#snapshots' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/docs/1.4.3/spark-queries/#snapshots;13267;241;Snapshots table;0.003628969192504883;275164;3.105419874191284;0;2;
metrics-reporting;https://iceberg.apache.org/docs/1.4.2/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.4.2/configuration/metrics-reporting;13443;85;Metrics reporting;-1;173;4.322829008102417;0;2;
../spark-queries#snapshots;https://iceberg.apache.org/docs/1.4.2/spark-configuration/;;200 OK;Redirected to `https://iceberg.apache.org/docs/1.4.2/spark-queries/#snapshots' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/docs/1.4.2/spark-queries/#snapshots;13267;241;Snapshots table;0.012463092803955078;275164;4.69311785697937;0;2;
metrics-reporting;https://iceberg.apache.org/docs/1.4.1/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.4.1/configuration/metrics-reporting;13443;85;Metrics reporting;-1;173;3.1225779056549072;0;2;
../spark-queries#snapshots;https://iceberg.apache.org/docs/1.4.1/spark-configuration/;;200 OK;Redirected to `https://iceberg.apache.org/docs/1.4.1/spark-queries/#snapshots' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/docs/1.4.1/spark-queries/#snapshots;13267;241;Snapshots table;0.0020170211791992188;275164;3.5179481506347656;0;2;
metrics-reporting;https://iceberg.apache.org/docs/1.4.0/configuration/;;404 Not Found;;;False;https://iceberg.apache.org/docs/1.4.0/configuration/metrics-reporting;13443;85;Metrics reporting;-1;173;3.4534871578216553;0;2;
../spark-queries#snapshots;https://iceberg.apache.org/docs/1.4.0/spark-configuration/;;200 OK;Redirected to `https://iceberg.apache.org/docs/1.4.0/spark-queries/#snapshots' status: 301 Moved Permanently.;;True;https://iceberg.apache.org/docs/1.4.0/spark-queries/#snapshots;13267;241;Snapshots table;0.0008158683776855469;275164;3.6289029121398926;0;2;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/latest/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/latest/resources/fonts/dejavu.css;3;12;;-1;173;3.0413029193878174;0;3;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.5.0/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.5.0/resources/fonts/dejavu.css;3;12;;-1;173;3.0220091342926025;0;3;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.4.1/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.4.1/resources/fonts/dejavu.css;3;12;;-1;173;3.3549370765686035;0;3;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.4.0/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.4.0/resources/fonts/dejavu.css;3;12;;-1;173;3.6468400955200195;0;3;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.5.2/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.5.2/resources/fonts/dejavu.css;4;12;;-1;173;2.946544885635376;0;4;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.5.1/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.5.1/resources/fonts/dejavu.css;4;12;;-1;173;2.818729877471924;0;4;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.4.3/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.4.3/resources/fonts/dejavu.css;4;12;;-1;173;3.0868747234344482;0;4;
resources/fonts/dejavu.css;https://iceberg.apache.org/javadoc/1.4.2/stylesheet.css;;404 Not Found;;;False;https://iceberg.apache.org/javadoc/1.4.2/resources/fonts/dejavu.css;4;12;;-1;173;3.7833821773529053;0;4;
# Stopped checking at 2024-06-03 23:33:07+002 (1 hour, 59 minutes)
```

It only checks internal links by default.

**Comment by manuzhang** [comment]
@Fokko Do you plan to merge this?

**Comment by Fokko** [comment]
@manuzhang Yes, I was out the last few days, thanks for pinging me 👍

**Pull request merged**
