### PR TITLE
Spark 3.1: Relocate all Netty classes

### PR DESCRIPTION
**Pull request by hililiwei**
Spark 3.1: Relocate all Netty classes 
 #6107

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by hililiwei** [comment]
cc @Fokko could you please take a look?

**Comment by aokolnychyi** [comment]
I think newer versions also have excludes for `org.apache.hadoop:hadoop-minicluster`.
@hililiwei, could you check if it is relevant for 3.1?

**Comment by hililiwei** [comment]
Thanks for review @aokolnychyi 
Added.

**Comment by hililiwei** [comment]
ping @nastra @aokolnychyi 😄

**Review by nastra — APPROVED** [review]
LGTM, and seems like a clean backport. Thanks @hililiwei

**Pull request merged**
