### PR TITLE
1.7.1 rc0 cherry picks

### PR DESCRIPTION
**Pull request by bryanck**
This PR picks the following PRs to the 1.7.x branch, in preparation for the 1.7.1 release:

https://github.com/apache/iceberg/pull/11516
https://github.com/apache/iceberg/pull/11504
https://github.com/apache/iceberg/pull/11574

### CODE REVIEW

**Comment by manuzhang** [comment]
It would be better to be decomposed into three commits.

**Comment by bryanck** [comment]
OK I can do that, I was just following this example: https://github.com/apache/iceberg/pull/11466

**Comment by manuzhang** [comment]
There are [two commits in one PR](https://github.com/apache/iceberg/pull/11466/commits)

**Comment by RussellSpitzer** [comment]
+1, I would try to keep the commits separate. 1 Pr but you can cherry pick all the things you like

**Comment by bryanck** [comment]
OK, let me try this again!

**Pull request closed without merging**
