### PR TITLE
ORC: Upgrade to 1.6.5

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to Upgrade Apache ORC from 1.6.3 to 1.6.5 to bring the latest bug fixes.

Note that Apache Iceberg UTs are used during Apache ORC vote.

### CODE REVIEW

**Review by aokolnychyi — APPROVED** [review]
Thanks, @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you for review and approval, @aokolnychyi !

**Comment by rdblue** [comment]
Thank you, @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you for reviewing and merging, @rdblue !

**Pull request merged**
