### PR TITLE
Build: Revert Parquet to 1.13.1

### PR DESCRIPTION
**Pull request by RussellSpitzer**
https://github.com/apache/parquet-java/issues/3040 - 
Was discovered by @pan3793  in Parquet 1.14.(0,1,2,3). This is considered a critical data loss issue so we will pull back parquet to avoid the vulnerability.

### CODE REVIEW

**Review by amogh-jahagirdar — APPROVED** [review]

**Review by Fokko — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Some Flink Tests Broken, Rerunning

**Review by danielcweeks — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Also fails locally

**Comment by Fokko** [comment]
@RussellSpitzer Easiest is probably to revert this commit: https://github.com/apache/iceberg/commit/b8c2b20237bc9309d34dc96c473e9941d1b2ad58

**Comment by RussellSpitzer** [comment]
Thanks @Fokko ! Note that we should probably fix these tests so that they don't hardwire expected values irrelevant fields

**Comment by RussellSpitzer** [comment]
Please review the 1.7.0 RC1 CherryPicks
https://github.com/apache/iceberg/pull/11466

**Pull request merged**
