### PR TITLE
Described as Hive 4.0.0

### PR DESCRIPTION
**Pull request by 911432**
Described as Hive 4.0.0

### CODE REVIEW

**Review by 911432 — COMMENTED** [review]
Described as Hive 4.0.0

**Review by Fokko — APPROVED** [review]
LGTM, thanks @911432 

WDYT @SourabhBadhya?

**Review by SourabhBadhya — APPROVED** [review]
LGTM +1
cc @Fokko

**Comment by Fokko** [comment]
Thanks @911432 for raising this PR, and thanks @SourabhBadhya for the review 🎉

**Pull request merged**
