### PR TITLE
[DRAFT] potential direction for custom registration of procedures

### PR DESCRIPTION
**Pull request by rymurr**
## Motivation for this change
The use cases are as follows:
1. add more iceberg specific procedures to the existing catalog. This is when we are actually operating on iceberg tables (not "to expose custom stored procedures for non-Iceberg systems")
2. modify existing OSS iceberg procedures. eg custom versions of compaction or a migrate table procedure that also re-writes the data
3. disable existing OSS iceberg procedures. eg maybe regular users shouldn't be running the snapshot or migrate action. Or ensuring that regular users with write permissions can't also execute potentially destructive actions (eg expire)

## Suggestion

This is one of several options to have the ability to register new procedures. This simply adds an overlay `Map` which takes priority over the existing `static Map`. This has the advantage of being small and simple but the disadvantage of being a bit hacky and unintuitive.

## Other options
Other potential options:
1) make the map in `SparkProcedures` mutable and register procedures at the `SparkProcedures` level - I am not a fan of this as it creates mutable static state
2) add a register method to `ProcedureCatalog` - this makes the `ProcedureCatalog` a bit more complete in that it would have 'read' and 'write' methods however its not immediately clear how to get stateless procedures (currently we use `ProcedureBuilder`). Perhaps `register(name, Supplier<Procedure>)`?
3) dynamically register procedures.  There is precedence for doing this in Spark with other spark components but I am not sure how disabling or overloading procedures would work. This also has the advantage that it would get rid of the manual accounting in `SparkProcedures`

I am not sure which option is best but I feel that having an unmodifiable set of procedures shipped with Iceberg is a bit challenging for administrators or operators. Looking forward to peoples thoughts @nastra @ajantha-bhat @RussellSpitzer @aokolnychyi @karuppayya @rdblue

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
@rymurr : This looks like a right direction to me. But I have some doubts.
a) How user can register their procedures without extending base catalog ? Now looks like still we need to extend catalog to gain access to these methods.

b) And regarding disable of existing procedures, we have not removed look up `SparkProcedures.newBuilder(name)` in the PR, so I would assume we need to disable by adding dummy procedure for them. Is my assumption is correct ?

**Comment by rymurr** [comment]
> @rymurr : This looks like a right direction to me. But I have some doubts. a) How user can register their procedures without extending base catalog ? Now looks like still we need to extend catalog to gain access to these methods.

thats correct. This isn't a great approach at the moment. We could make the method I added `static` or take one of the approaches I outlined above. Definitely interested in where other people think it could go.
> 
> b) And regarding disable of existing procedures, we have not removed look up `SparkProcedures.newBuilder(name)` in the PR, so I would assume we need to disable by adding dummy procedure for them. Is my assumption is correct ?

yes by adding a `null` to the new map we could 'override' an existing procedure. Again, not the cleanest thing int he world but it requires access to the immutable static map if we want to remove a procedure properly.

**Comment by rdblue** [comment]
What about getting these procedures from the Iceberg catalog? Are they always specific to Spark?

**Comment by rymurr** [comment]
I like the idea of getting them from the iceberg catalog. I am trying to do that now but I am not sure how to cleanly. `Procedure` and associated classes all rely explicitly on Spark so the Iceberg `Catalog` can't extend `ProcedureCatalog` directly. I am wondering about adding a method something like `Class procedureCatalog(String executionEngine)` to `Catalog` via a new interface. This could return the class for a custom procedure catalog that `SparkCatalog` or equivalent for other engines could use to instantiate new procedures. Thoughts?

**Comment by ajantha-bhat** [comment]
> I am wondering about adding a method something like `Class procedureCatalog(String executionEngine)` to Catalog via a new interface.

As all of the current procedures are dependent on spark, I am guessing other engines cannot make use of them. But it opens up an opportunity for registering new procedures for other engines also. So, I think it is good suggestion.

@rdblue , @rymurr : can we conclude on this ?

**Comment by rdblue** [comment]
Since this hasn't been moving for a while, I'm going to close it. I think the right way to do this is to register directly with Spark.

**Pull request closed without merging**
