### PR TITLE
Flink: Backport PR #10179  to Flink 1.20 for v2 sink

### PR DESCRIPTION
**Pull request by rodmeneses**
Steps:
```bash
git diff HEAD^ HEAD > /tmp/v1.19.patch
cat /tmp/v1.19.patch | sed "s/v1.19/v1.20/g" > /tmp/v1.20.patch
git apply -3 /tmp/v1.20.patch
```
all files came out `cleanly`

### CODE REVIEW

**Comment by stevenzwu** [comment]
> Steps:
> 
> ```shell
> git diff HEAD^ HEAD > /tmp/v1.19.patch
> cat /tmp/v1.19.patch | sed "s/v1.19/v1.20/g" > /tmp/v1.20.patch
> git apply -3 /tmp/v1.20.patch
> ```
> 
> all files came out `cleanly`

That is a smart way to port the change. didn't know this before

**Comment by rodmeneses** [comment]
> > Steps:
> > ```shell
> > git diff HEAD^ HEAD > /tmp/v1.19.patch
> > cat /tmp/v1.19.patch | sed "s/v1.19/v1.20/g" > /tmp/v1.20.patch
> > git apply -3 /tmp/v1.20.patch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > all files came out `cleanly`
> 
> That is a smart way to port the change. didn't know this before

Credits to @pvary who taught me this

**Comment by stevenzwu** [comment]
`apply` cmd used three-way merge for conflict. 

just to be safe, can you also run the diff and make sure diffs are not related to your change?
```
git diff --no-index flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink

git diff --no-index flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink
```

**Comment by rodmeneses** [comment]
> `apply` cmd used three-way merge for conflict.
> 
> just to be safe, can you also run the diff and make sure diffs are not related to your change?
> 
> ```
> git diff --no-index flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink
> 
> git diff --no-index flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink
> ```

I did the diff and I can confirm that the difference are due to https://github.com/apache/iceberg/pull/10526/files being merged today and the changes are not ported to 1.20
The most common diff was that there's a new `FlinkWriteResult` class that is now being used instead of `WriteResult`

**Review by stevenzwu — APPROVED** [review]

**Pull request merged**
