### PR TITLE
[AWS] S3FileIO - Add Cross-Region Bucket Access

### PR DESCRIPTION
**Pull request by munendrasn**
This PR is on top of the changes in PR https://github.com/apache/iceberg/pull/9804 from @ebelgasmi12 .
Additionally, The PR contains integration test for cross region changes.

cc  @elmehdibelgasmi @singhpk234

### CODE REVIEW

**Review by singhpk234 — APPROVED** [review]
Looks good to me ! would request to mark original author of PR as co-author in the pr description

cc @flyrain @RussellSpitzer 
you might also wanna take a look as because of this one had to create [PolarisS3FileIOClientFactory](https://github.com/apache/polaris/blob/main/polaris-core/src/main/java/org/apache/polaris/core/storage/aws/PolarisS3FileIOClientFactory.java#L32)

**Review by flyrain — APPROVED** [review]
LGTM. Wondering if the aws client can allow missing the `client.region` config now. cc @jackye1995

**Comment by munendrasn** [comment]
Thank you @singhpk234 @flyrain for the review.
As suggested,  I have updated the PR description to include the original PR and author. Please let me know if it looks good.

I would wait at least for couple of days for @ebelgasmi12 to respond. Maybe, we can cherry pick commits and add it to original PR, so that original PR can be merged

**Comment by munendrasn** [comment]
@flyrain @singhpk234 @jackye1995 @RussellSpitzer 
If the changes looks good, would it be possible merge the changes? It would great if this can make it to 1.7 release FYI @ebelgasmi12

**Review by jackye1995 — APPROVED** [review]
Looks good to me!

**Comment by jackye1995** [comment]
>  Wondering if the aws client can allow missing the client.region config now

@flyrain what do you mean by this? I think that config has been optional? And it will try to resolve the region using the default region chain https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html#automatically-determine-the-aws-region-from-the-environment

**Comment by flyrain** [comment]
@jackye1995, I meant the `AwsClientProperties` `client.region`. I believe it is still mandatory, no? To be clear, it is not related to this PR. I was wondering it since s3 basically can allow client to not set region now.

**Comment by flyrain** [comment]
Thanks @munendrasn for the PR. Thanks all for the review.

**Comment by jackye1995** [comment]
> I meant the AwsClientProperties client.region. I believe it is still mandatory, no?

No I don't think it is mandatory, I never set this in my sessions at least. If you find it otherwise, we should probably fix it.

**Comment by munendrasn** [comment]
Thanks @ebelgasmi12 for the original changes, Thank you all for the review

**Pull request merged**
