### PR TITLE
Demonstrate bug for issue #11253

### PR DESCRIPTION
**Pull request by jkolash**
Show that we do not bound the number of column statistics if the nested struct had 200 columns we would end up with over 200 statistics.

### CODE REVIEW

**Review by singhpk234 — COMMENTED** [review]
@jkolash this is a known behaviour,
The limit is enforced at top level columns 
please ref this discussion: https://github.com/apache/iceberg/pull/5215#discussion_r915475413

**Comment by jkolash** [comment]
Hmm the purpose of this property is to bound the number of metrics that get created for tables with wide schemas. the fact that it doesn't work with all types of wide schemas seems to be a fundamental flaw. I see the comment 

>> Yes, but this is the current behavior. We use the top-level columns for the current check.
https://github.com/apache/iceberg/pull/5215#discussion_r916006986

but I don't see an explanation beyond that why it shuold be limited to top level columns.

**Comment by jkolash** [comment]
I can close this and open a feature request instead or keep discussion on the issue instead. https://github.com/apache/iceberg/issues/11253

let me know

**Comment by singhpk234** [comment]
I think both works, i would recommend raising this in iceberg slack channel for `#dev` as well to open up to wider forum !

**Comment by jkolash** [comment]
Ok I started a slack thread and mailing list discussion I will close this issue for now.

**Pull request closed without merging**
