### PR TITLE
Remove unused GlueCatalog.fileIO field

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Review by nastra — APPROVED** [review]
LGTM, @jackye1995 could you also take a look please?

**Comment by findepi** [comment]
@nastra @jackye1995 what are preconditions for merging this PR?
i hope it is just a trivial cleanup

**Comment by nastra** [comment]
I was mainly waiting for the original author of the code (@jackye1995) to double-check this before merging

**Comment by findepi** [comment]
is there anything i can do to help move this presumably trivial PR forward?

**Comment by findepi** [comment]
thanks for the merge!

**Pull request merged**
