### PR TITLE
raise open-pull-requests-limit to 50

### PR DESCRIPTION
**Pull request by MaxNevermind**

### CODE REVIEW

**Comment by MaxNevermind** [comment]
opened by mistake

**Comment by Fokko** [comment]
@MaxNevermind No problem. I'm open to raise this limit though

**Comment by Fokko** [comment]
Or we could run it daily

**Comment by MaxNevermind** [comment]
@Fokko 
I opened this PR by mistake, actually wanted to do that for my cloned repo so I can see all the PRs dependabot forms not just 5
It does form [a couple of dozens of PRs](https://github.com/MaxNevermind/iceberg/pulls) if not limited as you can see in my cloned repo after similar PR merged to master there 
not sure if we want to make it a default behaivour

**Comment by MaxNevermind** [comment]
fyi
this is related to this [PR](https://github.com/apache/iceberg/pull/7694) and this [comment](https://github.com/apache/iceberg/pull/7694#issuecomment-1645508546) in particular.

**Pull request closed without merging**
