### PR TITLE
Spark 3.4: Switch to built-in DELETE implementation

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR migrates our DELETE commands to use the built-in implementation, which should be fully compatible now.

### CODE REVIEW

**Review by singhpk234 — APPROVED** [review]
LGTM, Thanks @aokolnychyi !

**Comment by dramaticlly** [comment]
thank you Anton, for my own curiosity, is this coming from feature released in [spark 3.4](https://spark.apache.org/releases/spark-release-3-4-0.html)?

**Review by amogh-jahagirdar — APPROVED** [review]
This looks good to me, thanks @aokolnychyi

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @singhpk234 @amogh-jahagirdar!

**Pull request merged**
