### PR TITLE
[ICEBERG-FLINK]support read hive configuration from HIVE_HOME&HIVE_CONF_DIR env

### PR DESCRIPTION
**Pull request by hehuiyuan**
Add load hive configuration from HIVE_CONF_DIR or HIVE_HOME.

The order of loading hive configuration:
(1)if `hive-conf-dir` parmeter is configured for catalog， the hive-site.xml will  be loaded form the path
(2) if `hive-conf-dir` parmeter is not configured  for catalog, the hive-site.xml will be load from  classpath.
if both way don't exist , it will throw exception for hivecatalog.

The purpose of this pr  is to add loading hive configuraiton from the environment vairables  `HIVE_HOME` or `HIVE_CONF_DIR`:
The order of loading hive configuration:
(1) if `hive-conf-dir` parmeter is configured for catalog， the hive-site.xml will  be loaded from the path
(2) if `hive-conf-dir`parmeter  is not configured  for catalog, the hive-site.xml will be load :
>     (2.1) if `HIVE_HOME` environment variable  exists, the hive-site.xml will  be loaded from the path
>     (2.2) if `HIVE_CONF_DIR` environment variable  exists, the hive-site.xml will  be loaded from the path
>     (2.3) if the hive configuration file exists in the classpath, it will be loaded from here.

Why load hive configuration  from environment variable?
For example:
(1) For Flink  or Spark on yarn, the `HIVE_HOME` or `HIVE_CONF_DIR` environment variables exist generally, it is convinent.
(2) For Flink or Spark platform, users don't need to care about the hive configuration file path . We don't  make  users to  set hive-conf-dir parameter. So we can add  `HIVE_HOME` or `HIVE_CONF_DIR` env to  point the configuration file path.

### CODE REVIEW

**Comment by hehuiyuan** [comment]
Hi @kbendick , thanks.
Update.

**Comment by kbendick** [comment]
> Hi @kbendick , thanks.
> Update.

Hi @hehuiyuan, thanks for clarifying the reasoning for this. I'd have one suggestion. The `mergeHiveConf` method is getting a little large. Could you possibly create a method like `hiveConfFromEnvVariables` or something and then call that in `mergeHiveConf`?

I know the current `mergeHiveConf` also isn't a strict merging, but now that it's getting more complicated, that would be ideal. So at least for this PR, if you could update your additions to be coming from their own function or functions, that would be helpful in working towards that goal.

If you want to wait until there's feedback from the more Flink-focused committers though (like openinx and Jingsong Li), then feel free. Wouldn't want to have my style request change be for nothing 🙂. But if these environment variables are commonly provided as you mentioned, I think that makes sense.

**Comment by hehuiyuan** [comment]
Hi  @kbendick , is that what you mean?

**Comment by hehuiyuan** [comment]
Hi @JingsongLi @openinx , do you have any suggestions for this issue？

**Pull request closed without merging**
