### PR TITLE
Slightly reduce logging verbosity

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by findepi** [comment]
cc @hashhar @losipiuk

**Comment by rdblue** [comment]
I've found these particular log messages to be really helpful when trying to track down errors. It helps to know what happened when an unexpected event comes up. I think that turning these down should be done by log4j configuration, not by changing the log level.

**Comment by jackye1995** [comment]
+1 for what @rdblue says, I think just for backwards compatibility it's better to not change existing log levels. Users can always configure to ignore this in the log4j config.

**Comment by kbendick** [comment]
> +1 for what @rdblue says, I think just for backwards compatibility it's better to not change existing log levels. Users can always configure to ignore this in the log4j config.

+1 to what both Ryan and Jack said. These are very often the logs that people quote when reporting issues. And relative to the frequency with which frameworks log (Spark, etc), the logging amount here is pretty minimal. If it's not possible to suppress these specific log lines via the Log4j configuration, possibly we could move them to come from their own class that could then be suppressed... but I think lowering their level globally is probably not the best approach.

**Pull request closed without merging**
