### PR TITLE
Flink: support write watermark in snapshot

### PR DESCRIPTION
**Pull request by liubo1022126**
thanks @dixingxing0 @stevenzwu @rdblue 

As https://github.com/apache/iceberg/pull/2109 (issue https://github.com/apache/iceberg/issues/2108) said, we need to have the timestamp of the data advancement in the snapshot, and also need historical detailed information of watermark for trend analysis, so this PR support write watermark in snapshot.

Design is as follows: 
image

1. Specify a field in the table as a timestamp field: "write.watermark.field", field type is Long.
2. In  IcebergStreamWriter, advance the max("write.watermark.field") to the next operation.
3. In IcebergFilesCommitter, get N(number of parallelism) advance information sent from step2, then choose the min of them.
     a. if the current min ts is greater than the last ts, then write the current ts to the snapshot as watermark.
     b. if the current min ts is not greater than the last ts, Keep the last ts to the snapshot as watermark.

Users must be aware of some specifications:
1. If there is no data for some parallelism writers, then watermark will not advance further.
2. Watermark will only advance backward, not forward.

### CODE REVIEW

**Comment by rdblue** [comment]
@liubo1022126 can you remove the version.txt commit? Looks like you're accidentally based on the 0.12.0 tag instead of master.

**Comment by stevenzwu** [comment]
@liubo1022126 Instead of carrying over watermark info into `WriteResult`, I am wondering if we should have `IcebergFilesCommitter` override this method from `AbstractStreamOperator` to intercept watermark advancement.
```
    public void processWatermark(Watermark mark) throws Exception 
```

Also maybe revert unrelated formatting change,

**Comment by liubo1022126** [comment]
> @liubo1022126 can you remove the version.txt commit? Looks like you're accidentally based on the 0.12.0 tag instead of master.



> @liubo1022126 can you remove the version.txt commit? Looks like you're accidentally based on the 0.12.0 tag instead of master.

thanks @rdblue , I will resubmit a pr, from master. After discussing the implementation of watermark with @stevenzwu .

**Comment by liubo1022126** [comment]
> @liubo1022126 can you remove the version.txt commit? Looks like you're accidentally based on the 0.12.0 tag instead of master.

thanks @rdblue , I will resubmit a pr, from master. After discussing the implementation of watermark with @stevenzwu .

**Comment by liubo1022126** [comment]
> @liubo1022126 Instead of carrying over watermark info into `WriteResult`, I am wondering if we should have `IcebergFilesCommitter` override this method from `AbstractStreamOperator` to intercept watermark advancement.
> 
> ```
>     public void processWatermark(Watermark mark) throws Exception 
> ```
> 
> Also maybe revert unrelated formatting change,

thanks @stevenzwu , I have also considered using flink's watermark to design iceberg's data advancement information, but why I rejected it later, mainly the following points: 

1. what is flink watermark: Flink watermark is mainly used to solve the out-of-order problem of delayed data arrival, out-of-order data is very common in real-time streams, and reordering is necessary.
2. what is iceberg watermark: In iceberg, watermark is used when writing data, save the time progress of writing data, it has nothing to do with the reordering of out-of-order data. It is different from the design intention of flink watermark.

So, Although we can use the ability of flink watermark to implement iceberg watermark, but if we need to support the reordering of out-of-order data in iceberg in the future, flink iceberg and iceberg watermark will cause confusion.
So, For the expression of [watermark] in iceberg watermark, I am also suspicious, It might be called data advancement better？

**Pull request closed without merging**
