### PR TITLE
Infra - Add flag to the release candidate generation script for a "test" mode

### PR DESCRIPTION
**Pull request by kbendick**
Allows users to run the release candidate generation script in a test mode, which won't make local modifications (or will revert them).

Open to removing anything people might find to be unsafe for future refactors etc.

**Output when run in test mode** - Notice that the git tree is returned to the same state and the tarball and release announcement e-mail are in the project directory:
```
$ dev/source-release.sh -k 7882F1FD96BA2103 -g origin -v 0.12.1 -r 9934 -t
In test mode: will revert to 7a4c9dcfc99647415da34975f45a274d3e3c5d7f when done
Preparing source for apache-iceberg-0.12.1-rc9934
Adding version.txt and tagging release...
[add-flag-to-dev-release 5236ed59] Add version.txt for release 0.12.1
 1 file changed, 1 insertion(+)
 create mode 100644 version.txt
Tagging the release candidate
In test mode: Not pushing the tagged release candidate to origin. A tarball will be available at the end
Creating tarball  using commit 5236ed593bf5a5276b197276ae8a84aa41a77eed from tag apache-iceberg-0.12.1-rc9934
Signing the tarball...
Checking out Iceberg RC subversion repo...
Checked out revision 50523.
Finalizing components for the tarball to the Iceberg distribution Subversion repo...
In test mode: skipping sending tarball to the Iceberg distribution Subversion repo...
Creating release-announcement-email.txt...
In test mode: Skipped committing a release candidate to the Apache artifacts repository
In test mode: The generated tarball and release email should be located in /Users/kylebendickson/repos/iceberg-kyle
Test mode cleanup: Removing git tag generated in test mode and temporary files
Deleted tag 'apache-iceberg-0.12.1-rc9934' (was 38a6f749)
HEAD is now at 7a4c9dcf Add note that we will revert to the original version hash as it outputs at the end
➜  iceberg-kyle git:(add-flag-to-dev-release) ✗ git status
On branch add-flag-to-dev-release
Your branch is up to date with 'origin/add-flag-to-dev-release'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	apache-iceberg-0.12.1.tar.gz
	apache-iceberg-0.12.1.tar.gz.asc
	apache-iceberg-0.12.1.tar.gz.sha512
	release-announcement-email.txt

nothing added to commit but untracked files present (use "git add" to track)
```

**Output run outside of test mode** (Note that I exited before entering my password, but the flow should work otherwise as I've tested it by commenting that part out).
```
dev/source-release.sh -k 7882F1FD96BA2103 -g origin -v 0.12.1 -r 9934
Preparing source for apache-iceberg-0.12.1-rc9934
Adding version.txt and tagging release...
[add-flag-to-dev-release ab4f67f2] Add version.txt for release 0.12.1
 1 file changed, 1 insertion(+)
 create mode 100644 version.txt
Tagging the release candidate
Pushing apache-iceberg-0.12.1-rc9934 to origin...
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 442 bytes | 442.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:kbendick/iceberg.git
 * [new tag]           apache-iceberg-0.12.1-rc9934 -> apache-iceberg-0.12.1-rc9934
Creating tarball  using commit ab4f67f2c5062dc1b17acfe79bd26d78a25d2fb0 from tag apache-iceberg-0.12.1-rc9934
Signing the tarball...
Checking out Iceberg RC subversion repo...
Checked out revision 50523.
Finalizing components for the tarball to the Iceberg distribution Subversion repo...
A         tmp/apache-iceberg-0.12.1-rc9934
A  (bin)  tmp/apache-iceberg-0.12.1-rc9934/apache-iceberg-0.12.1.tar.gz
A         tmp/apache-iceberg-0.12.1-rc9934/apache-iceberg-0.12.1.tar.gz.sha512
A         tmp/apache-iceberg-0.12.1-rc9934/apache-iceberg-0.12.1.tar.gz.asc
Authentication realm: <https://dist.apache.org:443> ASF Committers
Password for 'iceberg-user': ^C
svn: E200015: Commit failed (details follow):
svn: E200015: The operation was interrupted
```

### CODE REVIEW

**Comment by kbendick** [comment]
> not strictly related to this PR and is rather meant for the shell scripts in general, but just an fyi that I think it would be good to check shell scripts with https://www.shellcheck.net/

Yeah I agree. I actually had some changes in here originally that came from my local `shellcheck` via intellij. I decided to keep them out of this PR, but I'll likely make a new PR that does update the ones that exist at least.

**Comment by kbendick** [comment]
Closing this as I can't run this script to completion, so Ryan has graciously volunteered to run it for me for the 0.12.1 RC.

**Comment by rdblue** [comment]
Thanks for working on this! Sorry that it isn't as useful as I thought it would be since the script requires you to have a signing key and all of the ASF accounts.

**Comment by kbendick** [comment]
> Thanks for working on this! Sorry that it isn't as useful as I thought it would be since the script requires you to have a signing key and all of the ASF accounts.

No worries! It actually was a good exercise for me as I got keys set up locally for signing and generally have a much better understanding now of the process.

**Pull request closed without merging**
