### PR TITLE
Hive: Bug when runing SQL with multiple table join.

### PR DESCRIPTION
**Pull request by openinx**
Please don't merge this PR, because it was designed to reproduce this bug: https://github.com/apache/iceberg/issues/3393

### CODE REVIEW

**Comment by pvary** [comment]
@openinx: Seems more like a Hive bug to me. Working with Hive master BTW.
Simplified your use-case to this (no partitions):
```
  @Test
  public void testBug() {
    shell.setHiveSessionValue("hive.cbo.enable", true);
    String engine_config = "CREATE TABLE engine_config (\n" +
            "   application_id STRING,\n" +
            "   config STRING\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(engine_config);
    shell.executeStatement("INSERT INTO engine_config VALUES ('APP-1', 'c0')");

    String process_info = "CREATE TABLE process_info (\n" +
            "   application_id STRING,\n" +
            "   engine STRING,\n" +
            "   node_type STRING,\n" +
            "   bytes_read BIGINT,\n" +
            "   bytes_write BIGINT,\n" +
            "   fd_count_avg BIGINT,\n" +
            "   thread_count_avg INT\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(process_info);
    shell.executeStatement(
            "INSERT INTO process_info VALUES('APP-1','map', 'MR', 0, 0, 0, 0)");

    String mr_job_info = "CREATE TABLE mr_job_info (\n" +
            "   application_id STRING,\n" +
            "   queue STRING,\n" +
            "   user_name STRING\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(mr_job_info);
    shell.executeStatement("INSERT INTO mr_job_info VALUES ('APP-1','QUEUE-1', 'openinx')");

    String mr_task_info = "CREATE TABLE mr_task_info (\n" +
            "   application_id STRING,\n" +
            "   elapse_time STRING\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(mr_task_info);
    shell.executeStatement("INSERT INTO mr_task_info VALUES ('APP-1','NaN')");

    String query = "SELECT\n" +
            "    j.user_name,\n" +
            "    r.bytes_read\n" +
            "FROM\n" +
            "    process_info r\n" +
            "    JOIN engine_config c ON \n" +
            "        r.application_id = c.application_id\n" +
            "    JOIN mr_job_info j ON \n" +
            "        j.application_id = c.application_id\n";
    shell.executeStatement(query);
  }
```
Seems like when reading the `SelectOperator` only tires to read the `application_id` column. When I was debugging the code, I have found that when we calculate the columns at #2052 the values are correct. We lose the data somewhere later.

I will need some more time to find the problem.

Thanks for the good repro case!

**Comment by openinx** [comment]
@pvary  thanks for your time to debug this.

**Comment by pvary** [comment]
The issue is reproducible with this:
```
  @Test
  public void testBug() {
    shell.setHiveSessionValue("hive.cbo.enable", true);

    String process_info = "CREATE TABLE process_info (\n" +
            "   application_id STRING,\n" +
            "   engine STRING,\n" +
            "   node_type STRING,\n" +
            "   bytes_read BIGINT,\n" +
            "   bytes_write BIGINT,\n" +
            "   fd_count_avg BIGINT,\n" +
            "   thread_count_avg INT\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(process_info);
    shell.executeStatement(
            "INSERT INTO process_info VALUES('APP-1','map', 'MR', 0, 0, 0, 0)");

    String mr_job_info = "CREATE TABLE mr_job_info (\n" +
            "   application_id STRING,\n" +
            "   queue STRING,\n" +
            "   user_name STRING\n" +
            " )\n" +
            " STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'";
    shell.executeStatement(mr_job_info);
    shell.executeStatement("INSERT INTO mr_job_info VALUES ('APP-1','QUEUE-1', 'openinx')");

    String query = "SELECT\n" +
            "    j.user_name\n" +
            "FROM\n" +
            "    process_info r\n" +
            "    JOIN mr_job_info j ON \n" +
            "        j.application_id = r.application_id\n";
    shell.executeStatement(query);
  }
```

The explain plan is this:
```

STAGE DEPENDENCIES:
  Stage-1 is a root stage
  Stage-0 depends on stages: Stage-1

STAGE PLANS:
  Stage: Stage-1
    Map Reduce
      Map Operator Tree:
          TableScan
            alias: r
            filterExpr: application_id is not null (type: boolean)
            Statistics: Num rows: 1 Data size: 2055 Basic stats: COMPLETE Column stats: NONE
            Filter Operator
              predicate: application_id is not null (type: boolean)
              Statistics: Num rows: 1 Data size: 2055 Basic stats: COMPLETE Column stats: NONE
              Select Operator
                expressions: application_id (type: string)
                outputColumnNames: _col0
                Statistics: Num rows: 1 Data size: 2055 Basic stats: COMPLETE Column stats: NONE
                Reduce Output Operator
                  key expressions: _col0 (type: string)
                  sort order: +
                  Map-reduce partition columns: _col0 (type: string)
                  Statistics: Num rows: 1 Data size: 2055 Basic stats: COMPLETE Column stats: NONE
          TableScan
            alias: j
            filterExpr: application_id is not null (type: boolean)
            Statistics: Num rows: 1 Data size: 1014 Basic stats: COMPLETE Column stats: NONE
            Filter Operator
              predicate: application_id is not null (type: boolean)
              Statistics: Num rows: 1 Data size: 1014 Basic stats: COMPLETE Column stats: NONE
              Select Operator
                expressions: application_id (type: string), user_name (type: string)
                outputColumnNames: _col0, _col1
                Statistics: Num rows: 1 Data size: 1014 Basic stats: COMPLETE Column stats: NONE
                Reduce Output Operator
                  key expressions: _col0 (type: string)
                  sort order: +
                  Map-reduce partition columns: _col0 (type: string)
                  Statistics: Num rows: 1 Data size: 1014 Basic stats: COMPLETE Column stats: NONE
                  value expressions: _col1 (type: string)
      Reduce Operator Tree:
        Join Operator
          condition map:
               Inner Join 0 to 1
          keys:
            0 _col0 (type: string)
            1 _col0 (type: string)
          outputColumnNames: _col2
          Statistics: Num rows: 1 Data size: 2260 Basic stats: COMPLETE Column stats: NONE
          Select Operator
            expressions: _col2 (type: string)
            outputColumnNames: _col0
            Statistics: Num rows: 1 Data size: 2260 Basic stats: COMPLETE Column stats: NONE
            File Output Operator
              compressed: false
              Statistics: Num rows: 1 Data size: 2260 Basic stats: COMPLETE Column stats: NONE
              table:
                  input format: org.apache.hadoop.mapred.SequenceFileInputFormat
                  output format: org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat
                  serde: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe

  Stage: Stage-0
    Fetch Operator
      limit: -1
      Processor Tree:
        ListSink
```

The issue is that 2 `TableScanOperator`s are running in the same `Map` and they are using the same HiveConf (which contains the column pruning information). This is the fix for Hive:
```
diff --git a/ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java b/ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
index ea8e634484..c921cf68e1 100644
--- a/ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
+++ b/ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
@@ -369,10 +369,13 @@ else if (partRawRowObjectInspector.equals(tblRawRowObjectInspector)) {
         if (!tableNameToConf.containsKey(tableName)) {
           Configuration clonedConf = new Configuration(hconf);
           clonedConf.unset(ColumnProjectionUtils.READ_NESTED_COLUMN_PATH_CONF_STR);
+          clonedConf.unset(ColumnProjectionUtils.READ_COLUMN_NAMES_CONF_STR);
+          clonedConf.unset(ColumnProjectionUtils.READ_COLUMN_IDS_CONF_STR);
           tableNameToConf.put(tableName, clonedConf);
         }
         Configuration newConf = tableNameToConf.get(tableName);
-        ColumnProjectionUtils.appendNestedColumnPaths(newConf, nestedColumnPaths);
+        ColumnProjectionUtils.appendReadColumns(newConf, tableScanDesc.getNeededColumnIDs(),
+            tableScanDesc.getOutputColumnNames(), tableScanDesc.getNeededNestedColumnPaths());
       }
     }
```

Have to think about how to push the fix to Hive, as MR is deprecated there and the problem does not occur with Tez.

**Comment by pvary** [comment]
Proposed fix for Hive: https://github.com/apache/hive/pull/2765

**Comment by pvary** [comment]
Pushed the fix for Hive master.

**Pull request closed without merging**
