### PR TITLE
Add clock to SnapshotProducer

### PR DESCRIPTION
**Pull request by jzhuge**
Enable unit tests to use the new TestClock, a mutable manual clock.
Switch TestRemoveSnapshots to use TestClock.

### CODE REVIEW

**Comment by rdblue** [comment]
What's the motivation for this change?

**Comment by jzhuge** [comment]
The PR is to enhance the testability of Snapshot, a feature sensitive to timings, especially when expiring snapshots. It injects a clock that can be either system clock in production or a test clock in testing. The PR adds a test clock implementation that is fixed and can be reset or advanced. Please note default Java 8 concrete clock classes like `Clock.fixed` are immutable.

Unit tests no longer have to perform busy wait or sleep like the following:
```
  // t1: append and commit
  // busy wait or sleep
  // t2: append and commit
  // busy wait or sleep
  // expire snapshot before current time
```
Instead the tests will look like:
```
  // t1: append and commit
  // advance test clock by 1ms
  // t1+1: append and commit
  // advance test clock by 1ms
  // expire snapshot before current time (t1+2)
```
or
```
  // set the test clock to t1
  // t1: append and commit
  // set the test clock to t2
  // t2: append and commit
  // expire snapshot before t2+1
```
The unit tests can simulate running in the future, in the past, or in any arbitrary point in time. The tests will run faster. And they will be slightly more reliable as they don't rely on system clock.

**Comment by rdblue** [comment]
Thanks, @jzhuge! I think the current implementation is fairly clean and I like how it injects the clock through `TableOperations`. That is a good place to inject table customization and this alters a lot fewer classes now.

I'm not sure that this solution is needed, though. I don't know of any use cases that would use a clock to inject custom timestamp logic, so adding this through `TableOperations` adds unnecessary complexity to an interface that is extended by external libraries. I am also not sure that this is the best option for tests because it isn't obvious what relationship the clock has to the other operations because it is passed in at table creation time through the superclass. The logic isn't very obvious, compared to the approach of calling `waitUntilAfter(snapshot.timestampMillis())`.

**Comment by jzhuge** [comment]
Agree that passing the clock through `TableOperations` to `SnapshotProducer.apply` does not make sense.

**Comment by jzhuge** [comment]
If there is production use case for a manual clock ingested into table operations, I can rename `TestClock` to `ManualClock` and move it from test to prod.

**Comment by rdblue** [comment]
We discussed this last night since there was a thread on the mailing list about using timestamps for incremental table consumption. What we concluded was that even with an easy way to inject timestamps like this, it would still be unreliable. That makes me less inclined to add a `Clock` to `TableOperations` because people may start to use it to inject timestamps, even though there are still commit issues.

**Comment by HeartSaVioR** [comment]
In general, manual clock like this is widely used for testing and I see it very helpful, but according to the changeset it looks to affect just a couple of tests which looks to be very minor, compared to the impact of the change performed to the source side. Places I see using manual clocks are testing timeout functionality, which would add multi-seconds or minutes which aren't what we really want to actually sleep to wait. Here the test just busy-waits for 1 ms per each, which is trivial to just wait.

**Comment by jzhuge** [comment]
Yes @HeartSaVioR, this change has a very limited scope. Unfortunately there is no clean way to ingest the clock other than going through table operations or a bunch of constructors.

Close the PR.

**Pull request closed without merging**
