### PR TITLE
Core: Use the latest RoaringBitmap version 0.9.22

### PR DESCRIPTION
**Pull request by flyrain**
A followup of #3287. We should use the latest version of RoaringBitmap.
cc @aokolnychyi @RussellSpitzer @karuppayya @szehon-ho

### CODE REVIEW

**Review by RussellSpitzer — APPROVED** [review]
Lgtm

**Review by kbendick — APPROVED** [review]
+1. Thanks @flyrain!

We might consider not moving too far ahead of Spark with this dependency in general in the future. This is the present master Spark version, so seems good to me. I know we shade it, I'm just not very familiar with who actually looks after this dependency.

But I know it's used everywhere, so if you told me that the committers were at Apple I wouldn't be surprised in the least. Thanks for taking care of this @flyrain  :)

**Review by aokolnychyi — APPROVED** [review]

**Comment by aokolnychyi** [comment]
@flyrain, could you rebase this one?

**Comment by aokolnychyi** [comment]
Thanks, @flyrain!

**Comment by flyrain** [comment]
Thanks all for the review.

**Pull request merged**
