### PR TITLE
Docs: Update Iceberg Hive documentation

### PR DESCRIPTION
**Pull request by InvisibleProgrammer**
Issue: https://github.com/apache/iceberg/issues/6249

This documentation contains the list of new features introduced in Hive 4.0.0-alpha-2.

The only exception is https://issues.apache.org/jira/browse/HIVE-26077. It seems it was already supported in alpha-1 so I just refreshed the related part of the documentation.

### CODE REVIEW

**Comment by pvary** [comment]
@szlta: Could you please review? You are more familiar with the current/released Hive changes

**Comment by InvisibleProgrammer** [comment]
@pvary , Can I ask for workflow approval? 

Thank you,
Zsolt

**Review by pvary — APPROVED** [review]

**Comment by InvisibleProgrammer** [comment]
Hi, @pvary !

First of all, thank you for the review and approval. 
Unfortunately, I just learned the `Close` button on an approved PR doesn't mean close and merge, it just closes. So I reopened it. 
I assume, as a first-time committer, I have no permission to merge. 

Could you please merge it? 

Thank you,
Zsolt

**Comment by pvary** [comment]
Thanks for the PR @InvisibleProgrammer.
What version does Hive 4.0.0-alpha-2 depend on? Do we want to update the iceberg documentations for the released Iceberg versions as well (https://github.com/apache/iceberg-docs)?

**Comment by InvisibleProgrammer** [comment]
4.0.0-alpha-2 uses 0.14.1: https://github.com/apache/hive/blob/29c6bd9813edd43f6151b025295637858c3869f4/iceberg/pom.xml#L28
4.0.0 uses 1.0.0:  https://github.com/apache/hive/blob/374564f49b345f214ab8845e84244ac4ea4f0668/iceberg/pom.xml#L28

I assume, we should update all the versions since 0.14.1, including that one as well. Am I correct?

**Comment by pvary** [comment]
@InvisibleProgrammer: I am not sure what is the current way of changing the doc. Maybe reading through the `readme` file in the doc repo could help to guide us

**Comment by InvisibleProgrammer** [comment]
Hi, @pvary 

Ports to:
- 1.0.x: https://github.com/apache/iceberg/pull/6379
- 0.14.x: https://github.com/apache/iceberg/pull/6380

**Pull request merged**
