### PR TITLE
Update README in python_legacy module to have renamed folder name

### PR DESCRIPTION
**Pull request by puchengy**
As title.

### CODE REVIEW

**Review by kbendick — APPROVED** [review]
As opposed to just updating the README to reflect the updated folder name, should we possibly elaborate a bit more on the reasoning or the timeline or anything?

This is a good catch, but it does seem like we should possibly be updating the documentation a bit more than simply pointing the directions at the new folder (which is a good start).

**Comment by Terry93** [comment]
@kbendick appreciate for your transparency! However, I might not be the better person to do the follow up per your suggestion. For background, I am new to this project and I made this fix while I am trying to build the python project following the README, so I think I don't have much context about the details of deprecation.

**Comment by TGooch44** [comment]
@jun-he @danielcweeks One of us should take a crack at updating the legacy package docs with some info about where to contact the community and any links that show an updated status on the redesign effort.

**Comment by jackye1995** [comment]
I think the following should be done:
1. add a link to the roadmap section that is currently being added for Python dev effort #3163 
2. separate java and python documentations into 2 separated tabs, and add some explanations there for legacy and new python module
3. in the community section, add a section for different slack channels, google groups, community sync note links, so that people can find python specific contact information.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Running CI, but I think we can merge this. This change is clearly correct. We can document the Python refactor separately.

**Comment by jun-he** [comment]
@kbendick @TGooch44 @jackye1995 Thanks for the comments and suggestions. I will add additional info to the doc. 

Some of info (e.g. why we rename it) is documented in the meeting notes, which is shared with the community and also dev mailing list, but missing in the formal iceberg doc, which I will put some details. Additionally,  more related doc will be added once we are close to finalize the high level design.

**Pull request merged**
