### PR TITLE
Site Docs - Fix Flink batch job incorrectly labeled as streaming

### PR DESCRIPTION
**Pull request by wuwenchi**
modify description for flink streaming job

### CODE REVIEW

**Review by kbendick — APPROVED** [review]
LGTM. Thank you @wuwenchi!

**Comment by kbendick** [comment]
Can you please edit the PR description to say something like the following "Fix Flink job incorrectly labeled as streaming job when it's a batch job"? @wuwenchi?

I had to open the file to see what the issue was, it's not clear from the diff alone. It's helpful for other reviewers to have proper context when reviewing PRs. Again, thanks for this patch! 😀

**Comment by kbendick** [comment]
Also, for PR titles, by convention we tend to use "[Primary Project Component] - Description of what was fixed".

For this PR, you'll get more PR reviewers / the correct PR reviewers if you use a title more like "Site Docs - Fix Flink batch job incorrectly labeled as streaming" or something similar.

Certain people focus more on the docs or on different areas, so that convention helps them prioritize where to review. Thanks again!

**Comment by wuwenchi** [comment]
@kbendick  Sorry for the problem with the PR format ... Thanks for your advice, and I will follow the convention in the future to improve efficiency ~

**Comment by kbendick** [comment]
No worries @wuwenchi! Just thought I'd give you a heads up. Your contribution is greatly appreciated!

cc @samredai for a docs related PR.

**Review by rdblue — APPROVED** [review]

**Pull request merged**
