### PR TITLE
Docs: Sync specs to site via symlinks

### PR DESCRIPTION
**Pull request by manuzhang**
spec files under `site/docs` are not in sync with those under `format` which should be the source of truth. This PR changes them to symlinks.

### CODE REVIEW

**Comment by manuzhang** [comment]
@bitsondatadev @nastra please help review

**Comment by nastra** [comment]
I like that idea, but this doesn't render the Spec site correctly when running the site locally. This is because `{{% icebergVersion %}}` needs to be replaced with `{{ icebergVersion }}` so that the page is rendered correctly.

Also it appears that we don't have a menu entry for the GCM Stream spec. 
Could you please add `- AES GCM Stream spec: gcm-stream-spec.md` item to `nav.yml`?

**Comment by manuzhang** [comment]
@nastra Updated!

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing this

**Comment by bitsondatadev** [comment]
@manuzhang I'm on vacation, away from my computer and can't verify the link changes. I'll look at this when I return.

**Comment by nastra** [comment]
@bitsondatadev I've verified the changes locally when reviewing and things look good and work as expected

**Pull request merged**
