### PR TITLE
Infra - Disable CI for anything in open-api or format folder

### PR DESCRIPTION
**Pull request by kbendick**
Disables running CI workflows for any PR that is opened that only updates the `open-api` folder or the `format` folder.

The `docs` folder is already covered.

### CODE REVIEW

**Comment by kbendick** [comment]
Note that CI ran because the workflow files were changes. A little paradoxical, but not a common situation.

Shouldn't be the case once PRs are submitted that are already based on the latest changes.

**Comment by kbendick** [comment]
cc @rdblue @samredai @snazy

**Comment by samredai** [comment]
LGTM. Thanks @kbendick!

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @kbendick!

**Pull request merged**
