### PR TITLE
Spark: Allow specifying file format in RewriteDataFiles

### LINKED ISSUE #6464: Allow specifying data file format in RewriteDataFiles
### Feature Request / Improvement

A common use case for streaming pipelines is to be able to write small Avro data files in micro-batch fashion, and then periodically compact those into a few Parquet data files.

It'd be great if `RewriteDataFiles` had an [option](https://iceberg.apache.org/javadoc/1.1.0/org/apache/iceberg/actions/RewriteDataFiles.html#field.summary) to rewrite data files in a different data file format from that in the table properties to support such a workflow. This would allow a table configured to write Avro by default, but running compactions actions to Parquet.

A workaround today is to flip this around, by configuring a table with Parquet format, and having writers explicitly request Avro data files (e.g., with Spark, by passing the [`write-format`](https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java#L27) option explicitly). However, it'd be great to have the option to handle this in `RewriteDataFiles` instead to keep the writers agnostic to such details. 

### Query engine

None

### PR DESCRIPTION
**Pull request by hililiwei**
Close #6464

### CODE REVIEW

**Comment by peay** [comment]
The motivation in https://github.com/apache/iceberg/issues/6464 is to allow writing as Avro from a streaming pipeline, where row-based can make sense for small but frequent micro-batches, but then compacting to Parquet for longer-term batch analytics. This can be done today by configuring the table as Parquet, and explicitly setting the streaming writer to write as Avro, but it is a bit less flexible and I think it'd make sense to keep such details in compaction settings instead.

**Comment by 0xNacho** [comment]
+1 @peay . I have the same problem!

**Comment by RussellSpitzer** [comment]
Does the streaming write have the ability to set the file format? Or does that only let you use the table default as well?

**Review by RussellSpitzer — COMMENTED** [review]
This works for me, I am a bit uneasy though leaving the format configuration up to the RewriteStrategy, seems like we basically rely on the current hierarchy where everything descends from BinPack.

Other than that I think we should probably minimize the amount of tests we are adding for this. This is one of the slower test suites and it looks like we have a full test for every strategy, we should be able to confirm this by just rewriting a single file in each test correct?

**Comment by hililiwei** [comment]
> Does the streaming write have the ability to set the file format? Or does that only let you use the table default as well?

Yes, streaming writes can set file format.

> Other than that I think we should probably minimize the amount of tests we are adding for this. This is one of the slower test suites and it looks like we have a full test for every strategy, we should be able to confirm this by just rewriting a single file in each test correct?

Try to reduce the test, PTAL, thx.

**Pull request closed without merging**
