### PR TITLE
Build: Enable more error-prone checks

### PR DESCRIPTION
**Pull request by findepi**
Enable a number of useful error-prone checks.

### CODE REVIEW

**Review by sfc-gh-ygu — APPROVED** [review]
Looks good to me. Thanks for the change, @findepi !

**Comment by findepi** [comment]
thanks @sfc-gh-ygu . also cc @flyrain for potential approve

**Review by flyrain — APPROVED** [review]
Ah, I messed up my google account again.

**Comment by findepi** [comment]
as they saying goes -- two heads are better than one 🙁 

thanks again for review!

**Pull request merged**
