### PR TITLE
Flink source: move convertConstant method from the base DataIterator to RowDataIter…

### PR DESCRIPTION
**Pull request by stevenzwu**
…ator, since it seems to be tied to Flink table row data types (like DecimalData, StringData, TimestampData etc.)

### CODE REVIEW

**Comment by stevenzwu** [comment]
@JingsongLi @openinx can you help take a look at this small refactoring?

**Comment by JingsongLi** [comment]
Why move to `RowDataIter`? If we have `BatchDataIterator`, it may need to rely on this `convertConstant`.

**Comment by stevenzwu** [comment]
@JingsongLi `DataIterator<T>` is for generic type T, which could be an Avro GenericRecord or sth else. Currently, `convertConstant` method deals with Flink data types used by `RowData`  (like DecimalData, StringData, TimestampData etc.).  If there is a new `BatchDataIterator` impl for a different type `T`, I would imagine that we may need a diff impl of `convertConstant `.

**Comment by JingsongLi** [comment]
I see, My previous idea is that it is within the scope of `RowData`. For example, for Spark, `ColumnarBatch` also follows the interface of `InternalRow`. But I am OK to make it more generic.

Can you move this `convertConstant` to a new util class, like `org.apache.iceberg.flink.data.RowDataUtils`?

**Comment by openinx** [comment]
> @JingsongLi DataIterator<T> is for generic type T, which could be an Avro GenericRecord or sth else. 

I guess you are implementing the native avro reader for flink ?  It's right that moving this RowData specific convertion out of `DataIteraotr<T>`.    For me, moving to `RowDataUtils` or `RowDataIterator` , both work for me.

**Comment by stevenzwu** [comment]
@JingsongLi I have moved the convertConstant method to `RowDataUtil` as you suggested. Also updated and rebased the PR.

@openinx yes, internally we have a similar iterator/iterable for Avro GenericRecord type. It is not much code since Iceberg library provided those reader functions already, like `ParquetAvroValueReaders`

**Review by JingsongLi — APPROVED** [review]
+1, Thanks @stevenzwu for the update.

**Pull request merged**
