### PR TITLE
Spark 3.4: Fix system function pushdown in CoW row-level commands

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR cherry-picks PR #9873 to Spark 3.4.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
I forgot 3.4 is a bit different, I may need to make some changes. Let me see.

**Comment by aokolnychyi** [comment]
I excluded the unnecessary branch in `ReplaceStaticInvoke` and adapted the tests.

**Review by szehon-ho — APPROVED** [review]
lgtm, ReplaceData is not available in Spark 3.4?

**Comment by tmnd1991** [comment]
> lgtm, ReplaceData is not available in Spark 3.4?

ReplaceData is there in 3.4 but has 1 less argument (`groupFilterCondition: Option[Expression]`) but I see it's not used at all in ReplaceStaticInvoke logic, so I would say that we could add that branch too in 3.4 but definitely @aokolnychyi had a good reason to remove it 😄

**Review by nastra — APPROVED** [review]

**Comment by aokolnychyi** [comment]
In 3.4, we use custom `ReplaceIcebergData` and rewrite the operations differently. I think that logic is only needed in 3.5.

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @szehon-ho @tmnd1991 @nastra!

**Comment by lurnagao-dahua** [comment]
Hi,Is there a plan to port to Spark 3.3?

**Pull request merged**
