### PR TITLE
[BUILD] Fix the java.net.BindException when testing with Github Action

### PR DESCRIPTION
**Pull request by pan3793**
https://github.com/apache/spark/pull/32096

### CODE REVIEW

**Comment by rymurr** [comment]
Cc @snazy

**Comment by aokolnychyi** [comment]
This makes sense to me.

@RussellSpitzer @rdblue, could you take a look?

**Comment by pan3793** [comment]
Spark switched 127.0.0.1 to localhost, see https://github.com/apache/spark/pull/32102

**Comment by pan3793** [comment]
GA passed, both on JDK8 and JDK11, hope we can get it in ASAP to recover the development progress.

**Comment by RussellSpitzer** [comment]
https://github.com/apache/spark/pull/32096#discussion_r610328558 - Underlying issue is hypothesized to be the dns resolving properties of Inet.getLocalAddress.

**Comment by RussellSpitzer** [comment]
Our Test Hive code already uses localhost, so that should be fine.

**Review by RussellSpitzer — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Thanks @pan3793 !

**Comment by lhotari** [comment]
Root cause: reverse name lookups for the current host name is broken in GitHub Actions Runner VMs: https://github.com/actions/virtual-environments/issues/3185 
builds@apache.org mailing list thread:
https://lists.apache.org/thread.html/r40b2da182952f21a3b94696e6f1bf8594e7ff16e1c5979fe8b2d51c8%40%3Cbuilds.apache.org%3E

**Comment by snazy** [comment]
Interesting, maybe that's also causing the new-ish CI failures (#2475)

**Pull request merged**
