### PR TITLE
Python: Improve Avro read performance

### PR DESCRIPTION
**Pull request by rustyconover**
Utilize __slots__ for various Avro classes.

Memoize the key/value reader functions in MapReader.

### CODE REVIEW

**Comment by Fokko** [comment]
@rustyconover This is great. I'm curious, do you have any numbers on the impact of this change?

**Comment by rustyconover** [comment]
Do you know of a publicly accessible Iceberg table with a large amount of metadata?

**Comment by Fokko** [comment]
I use the [`docker-spark-iceberg` docker-compose setup](https://github.com/tabular-io/docker-spark-iceberg). You can easily point to it in your `cat ~/.pyiceberg.yaml`:

```yaml
default-catalog: local

catalog:
    local:
        uri: http://127.0.0.1:8181
        s3.endpoint: http://127.0.0.1:9000
        py-io-impl: pyiceberg.io.pyarrow.PyArrowFileIO
        s3.access-key-id: admin
        s3.secret-access-key: password
```

The `PyIceberg - Getting Started.ipynb` creates a table of five months of taxi data. You could add more data to it since there is [more](https://github.com/tabular-io/docker-spark-iceberg/blob/main/spark/Dockerfile#L81-L95). Or you could change the daily partitioning to an hourly once, creating a crazy amount of partitions (which Iceberg handles fine but should create large manifest files).

**Comment by rustyconover** [comment]
I'm testing on a single 8mb Avro file that took 40 seconds to load in the profiler.  With these changes time time is now 32 seconds.

**Comment by Fokko** [comment]
Nice, I'm also seeing some speedup:
```
➜  python git:(master) hyperfine --warmup 1 "python3 /tmp/benchamrk.py"
Benchmark 1: python3 /tmp/vo.py
  Time (mean ± σ):      2.689 s ±  0.028 s    [User: 2.799 s, System: 1.945 s]
  Range (min … max):    2.659 s …  2.756 s    10 runs
 
➜  python git:(master) git checkout fix_avro_use_slots
Switched to branch 'fix_avro_use_slots'
Your branch is up to date with 'rustyconover/fix_avro_use_slots'.
➜  python git:(fix_avro_use_slots) hyperfine --warmup 1 "python3 /tmp/benchmark.py"
Benchmark 1: python3 /tmp/vo.py
  Time (mean ± σ):      2.194 s ±  0.013 s    [User: 2.370 s, System: 1.937 s]
  Range (min … max):    2.175 s …  2.217 s    10 runs
```

Where `benchmark.py`:

```python
from pyiceberg.catalog import load_catalog
from pyiceberg.expressions import GreaterThanOrEqual, LessThan, And

catalog = load_catalog('local')

table = catalog.load_table('nyc.taxis')

expected_rows = 63454

df = table.scan(row_filter=And(
        GreaterThanOrEqual("tpep_pickup_datetime", "2022-01-01T00:00:00.000000+00:00"),
        LessThan("tpep_pickup_datetime", "2022-01-02T00:00:00.000000+00:00"),
)).to_arrow()

assert len(df) == expected_rows, f"Got {len(df)} rows, instead of {expected_rows}"
```

This is the taxi dataset with one year of data, and hourly partitioned (~160kb manifest files).

**Review by Fokko — APPROVED** [review]
Thanks for fixing this @rustyconover

**Pull request merged**
