### PR TITLE
Run CI checks on all supported JDKs

### PR DESCRIPTION
**Pull request by findepi**
This guarantees the build will succeed locally.

### CODE REVIEW

**Comment by findepi** [comment]
rebased to resolve conflicts

**Review by nastra — APPROVED** [review]

**Comment by findepi** [comment]
thanks for review and approval @nastra . Do you also want to merge this?

**Comment by nastra** [comment]
I'll leave it open for a bit to give others a chance to review

**Comment by findepi** [comment]
Rebased after https://github.com/apache/iceberg/pull/8486 was merged, to make sure there is no logical merge conflict.
It hopefully might be ready to go.

**Comment by findepi** [comment]
thanks @nastra !

**Pull request merged**
