### PR TITLE
Switch from new HashMap to Maps.newHashMap

### PR DESCRIPTION
**Pull request by findepi**
Per review comments in some other PR, this is project code style policy,
so apply consistently.

### CODE REVIEW

**Comment by findepi** [comment]
Sorry for several pushes here and fixing compilation problems via CI.
It seems that
```
./gradlew -DflinkVersions=1.12,1.13 -DsparkVersions=2.4,3.0,3.1,3.2 -DhiveVersions=2,3 build -x test -x javadoc -x integrationTest
```

as run by CI's `build-checks`, when run locally, doesn't compile all the files.

Thus `build-checks` can be failing even if `./gradlew -DflinkVersions=1.12,1.13 -DsparkVersions=2.4,3.0,3.1,3.2 -DhiveVersions=2,3 build -x test -x javadoc -x integrationTest` succeeds locally.

Can this be related to JDK version? 
`build-checks` runs with Java 8.

**Comment by findepi** [comment]
> Can this be related to JDK version?
> `build-checks` runs with Java 8.

Indeed. I installed JDK 8 and now when using it, the `./gradlew -DflinkVersions=1.12,1.13 -DsparkVersions=2.4,3.0,3.1,3.2 -DhiveVersions=2,3 build -x test -x javadoc -x integrationTest` command started to notice the problems it was not reporting previously.

Opened https://github.com/apache/iceberg/pull/3651. Having that in would save me some time, so maybe it could be helpful for someone else too.

**Review by jackye1995 — APPROVED** [review]
looks good to me, I created #3657 to add the rule to checkstyle. Will merge by end of day if there is no other comments.

**Comment by jackye1995** [comment]
merged, thanks for the work!

**Pull request merged**
