### PR TITLE
Python: Non-Cython fallback Avro parser

### PR DESCRIPTION
**Pull request by Fokko**
I think it would be good to include a pure Python fallback.

@rustyconover I'm seeing some weird errors here: https://github.com/pola-rs/polars/actions/runs/6109489610/job/16580630135?pr=10375

### CODE REVIEW

**Comment by rustyconover** [comment]
Hi @Fokko,

Reading the logs it looks like it's a packaging problem for Windows.

I'm pretty sure Cython works on Windows, but the wheel may not have the necessary module packaged.

Linux packages worked well (no PyIceberg errors), but the Windows build failed.  I don't have access to Windows so I can't really test it for you, but you may want to revisit including the shared library that is built by Cython.  Maybe we need to include *.dll rather than *.so or some other extension on Windows?

Rusty

**Comment by Fokko** [comment]
@rustyconover Yes I agree. It looks like it is pulling the wheel correctly but it is missing the `decoder_fast` module. Maybe still good to just add this fallback anyway.

**Comment by Fokko** [comment]
The Windows wheels are fixed in https://github.com/apache/iceberg/pull/8532, but I think this would be still a nice addition :)

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @Fokko! This looks much better with the fallback.

**Comment by Fokko** [comment]
@rdblue follow-up PR is inbound. While seeing if I could add a test for this, (this is kind of tricky since Python caches the modules), I noticed another import.

**Pull request merged**
