### PR TITLE
Core: Remove compile-time dependency to ResolvingFileIO

### PR DESCRIPTION
**Pull request by nastra**

### CODE REVIEW

**Comment by nastra** [comment]
Closing this as I just realized that it's included in https://github.com/apache/iceberg/pull/7369

**Review by Fokko — APPROVED** [review]
LGTM!

**Comment by nastra** [comment]
CI seems to fail due to `Could not HEAD 'https://repo.maven.apache.org/maven2/io/netty/netty-codec-http/4.1.75.Final/netty-codec-http-4.1.75.Final.pom'. Received status code 502 from server: Gateway Error`

**Review by singhpk234 — APPROVED** [review]
LGTM as well, Thanks @nastra

**Pull request merged**
