### PR TITLE
Spark: Write on a snapshot branch ref

### PR DESCRIPTION
**Pull request by hililiwei**
## What is the purpose of the change

Spark can write data to Branch in the following ways:

spark dataframe:
```java
data.write
    .format("iceberg")
    .mode("append")
    .option("branch","branchName")
    .save("db.table")
```

spark sql:
```sql
INSERT INTO prod.db.table.to_branch_{BranchName}

```

### CODE REVIEW

**Comment by rdblue** [comment]
@hililiwei, I don't think that we will support that syntax in SparkSQL. The option for `DataFrameWriter` looks fine, although we generally prefer to use `DataFrameWriterV2`, because there are so many problems with the original one.

**Comment by hililiwei** [comment]
> @hililiwei, I don't think that we will support that syntax in SparkSQL. The option for `DataFrameWriter` looks fine, although we generally prefer to use `DataFrameWriterV2`, because there are so many problems with the original one.

@rdblue Thanks for your feedback. Is there a more recommended way to write data to the branch in Spark SQL?

Branch\Tag is a very useful feature that we urgently need. Our colleagues use SparkSQL more than Dataframe API. We have tried the `table.to_branch_{branchName}` internally for branch write, could you please briefly show me what the main problems are?

Thanks 
Liwei

**Comment by rdblue** [comment]
@hililiwei, we want to introduce standard syntax for this to avoid divergence across engines:

```sql
-- Read from a branch
SELECT * FROM table BRANCH branch_name
-- Insert into a branch
INSERT INTO table BRANCH branch_name SELECT ...
-- Merge into a branch
MERGE INTO table BRANCH branch_name USING ...
-- Read from a tag
SELECT * FROM table AT TAG tag_name
```

It's very unlikely that other engines will support the multipart identifier syntax. Right now, I think we should focus on getting dataframe operations working and then move on to SQL after that.

**Comment by hililiwei** [comment]
> @hililiwei, we want to introduce standard syntax for this to avoid divergence across engines:
> 
> ```sql
> -- Read from a branch
> SELECT * FROM table BRANCH branch_name
> -- Insert into a branch
> INSERT INTO table BRANCH branch_name SELECT ...
> -- Merge into a branch
> MERGE INTO table BRANCH branch_name USING ...
> -- Read from a tag
> SELECT * FROM table AT TAG tag_name
> ```
> 
> It's very unlikely that other engines will support the multipart identifier syntax. Right now, I think we should focus on getting dataframe operations working and then move on to SQL after that.

Thank you for your answer. This syntax appears to need to wait for engine support. Or rewrite the engine's syntax file in the iceberg, as hudi did in spark 3.2 to support time travel. Otherwise, we don't seem to be able to use it in an earlier version of the engine. Of course, we can customize the engine's code and use it internally, but that's not realistic for a lot of tech teams, who tend to prefer out-of-the-box.

I don't know if that's the case with other teams, but we're more conservative in upgrading engine versions, for example, we're still using Spark 3.1 on a large scale. (That's why I raised a lot of PRs for reverse port of code to Spark3.1) , and use it for a long foreseeable period of time because we made a lot of internal changes to it and the upgrade wasn't that easy. This could cause us to be unavailable for a short period of time even if the engine supports it.

But no matter what, thanks again for your answer, I will remove it from this PR and keep only the option part.

Thank you very much.
Liwei

**Comment by zinking** [comment]
@hililiwei I also agree we should create divergence on sql syntaxes. why bother if we have better choices?

in this case what about using table hints to achieve what you want ?

**Pull request closed without merging**
