### PR TITLE
Docs: fix format-version doc returns 404 not found

### PR DESCRIPTION
**Pull request by polaris6**
This link returns not found

image

image

### CODE REVIEW

**Comment by polaris6** [comment]
cc: @jackye1995 @arminnajafi @singhpk234

**Review by singhpk234 — APPROVED** [review]
Thanks @polaris6, the change looks good to me.

**Comment by polaris6** [comment]
@samredai @singhpk234  I updated the commit, please help me to review it, thanks! The update is referenced here:
https://raw.githubusercontent.com/apache/iceberg/master/docs/tables/partitioning.md
image

**Review by samredai — APPROVED** [review]
LGTM, thanks @polaris6 ! cc: @rdblue

**Review by openinx — APPROVED** [review]

**Comment by openinx** [comment]
Got merged, thanks all for reviewing, and thanks @polaris6 for the contribution !

**Comment by rdblue** [comment]
@samredai, do we need to port this over to iceberg-docs?

**Comment by samredai** [comment]
@rdblue we do: I opened a hotfix PR to the `0.13.1` branch [here](https://github.com/apache/iceberg-docs/pull/70) and to the `latest` branch [here](https://github.com/apache/iceberg-docs/pull/71).

**Pull request merged**
