### PR TITLE
Docs: Add StarRocks to Documentation

### PR DESCRIPTION
**Pull request by caneGuy**
This PR adds a link to the documentation for StarRocks querying for Iceberg tables.

### CODE REVIEW

**Comment by kbendick** [comment]
Thanks for opening this PR and for linking the PR in the docs repo @caneGuy! I have only recently discovered StarRocks but it is very exciting. I look forward to the chance to learn more about it and hopefully use it.

In full transparency, I can't recall if the PR is supposed to be made here or in iceberg-docs, but can point out the person who _will_ be more sure 👍

**Comment by kbendick** [comment]
cc @samredai for visibility on including a link to external documentation for an additional query engine. There's also a PR open in iceberg-docs already linked here 👍

**Comment by caneGuy** [comment]
Thanks too much @kbendick

**Comment by caneGuy** [comment]
@samredai could you help review this pr thanks!

**Review by samredai — APPROVED** [review]
LGTM! We should merge the image in the iceberg-docs repo before this is released (there should be a docs release soon as part of the 0.13.2 release)

**Review by kbendick — COMMENTED** [review]
One thing I don't see is the actual starrocks-logo.png. Possibly that's included elsewhere though? It's a +1 from me otherwise.

**Review by kbendick — APPROVED** [review]
+1 this looks good to me.

My one outstanding question, which isn't a blocker as some similar files don't even seem to have it, is whether or not the ASF license header can be at the top of the file.

But if it passes the rat license check and it does indeed _have_ the license, I think that's sufficient given some similar files don't have it at all.

**Comment by caneGuy** [comment]
Thanks @kbendick @samredai 
if needed, i will add ASF header

**Comment by caneGuy** [comment]
cc @openinx could you help review this thanks

**Comment by caneGuy** [comment]
could you help merge this ? @kbendick thanks

**Review by openinx — APPROVED** [review]
Looks good to me, thanks @caneGuy for the great contribution !

**Comment by caneGuy** [comment]
@rdblue could you help reload the web site? and how can we see this logo and link on iceberg website. thanks too much

**Comment by rdblue** [comment]
@samredai, can you help port this to the iceberg-docs repo?

**Comment by samredai** [comment]
@rdblue this should show up in the 0.13.2 versioned docs site release which includes copying this over with the rest of the `docs` directory content. The logo image has already been merged (PR #[81](https://github.com/apache/iceberg-docs/pull/81))

**Pull request merged**
