### PR TITLE
Spark: Add table properties to control MERGE mode and isolation level

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds table properties to control MERGE mode and isolation level.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
@rdblue @dilipbiswal, could you review, please?

**Comment by dilipbiswal** [comment]
LGTM

**Comment by aokolnychyi** [comment]
Thanks for reviewing, @dilipbiswal! I've merged it so that I can rebase the alignment rule PR.

**Comment by rdblue** [comment]
+1

**Pull request merged**
