### PR TITLE
Build: Bump Arrow from 10.0.1 to 11.0.0

### PR DESCRIPTION
**Pull request by ajantha-bhat**
release notes
https://arrow.apache.org/release/11.0.0.html

python side is already merged
https://github.com/apache/iceberg/pull/6692

Benchmarks:
[With Arrow 10.0.1] https://github.com/ajantha-bhat/iceberg/actions/runs/4061513944
[With Arrow-11.0.0] https://github.com/ajantha-bhat/iceberg/actions/runs/4061518292

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
LGTM

**Review by singhpk234 — APPROVED** [review]
LGTM as well, Thanks @ajantha-bhat !

**Comment by rdblue** [comment]
@ajantha-bhat, can you please run benchmarks to ensure there are no regressions?

**Comment by ajantha-bhat** [comment]
>  @ajantha-bhat, can you please run benchmarks to ensure there are no regressions?


Benchmarks:
[With Arrow 10.0.1] https://github.com/ajantha-bhat/iceberg/actions/runs/4061513944
[With Arrow-11.0.0] https://github.com/ajantha-bhat/iceberg/actions/runs/4061518292

**Review by nastra — APPROVED** [review]

**Comment by nastra** [comment]
@ajantha-bhat could you please copy/paste the actual benchmark numbers from the linked benchmark runs to have an easier comparison of the numbers here?

**Comment by ajantha-bhat** [comment]
[With Arrow 10.0.1]
run-benchmark (SparkParquetWritersNestedDataBenchmark) 5m31s
run-benchmark (SparkParquetWritersFlatDataBenchmark) 5m13s
run-benchmark (SparkParquetReadersNestedDataBenchmark) 4m28s
run-benchmark (SparkParquetReadersFlatDataBenchmark) 5m11s

[With Arrow-11.0.0]
run-benchmark (SparkParquetWritersNestedDataBenchmark) 4m32s
run-benchmark (SparkParquetWritersFlatDataBenchmark) 5m9s
run-benchmark (SparkParquetReadersNestedDataBenchmark) 4m29s
run-benchmark (SparkParquetReadersFlatDataBenchmark) 5m13s

It dumps the JMH outputs into a local file. I am sure whether I can access those files.

**Comment by nastra** [comment]
@ajantha-bhat the results are stored and linked under [benchmark-results](https://github.com/ajantha-bhat/iceberg/suites/10704631127/artifacts/541607117) for each benchmark run.

**Comment by ajantha-bhat** [comment]
```
Benchmark [Arrow-11.0.0]                                          					                                 Mode  Cnt  Score   Error  Units
SparkParquetWritersNestedDataBenchmark.writeUsingIcebergWriter    					 ss    5  4.152 ± 0.123   s/op
SparkParquetWritersNestedDataBenchmark.writeUsingSparkWriter      					 ss    5  4.325 ± 0.089   s/op
SparkParquetWritersFlatDataBenchmark.writeUsingIcebergWriter      					 ss    5  6.411 ± 0.048   s/op
SparkParquetWritersFlatDataBenchmark.writeUsingSparkWriter        					 ss    5  6.725 ± 0.207   s/op
SparkParquetReadersNestedDataBenchmark.readUsingIcebergReader                                       ss    5  0.591 ± 0.079   s/op
SparkParquetReadersNestedDataBenchmark.readUsingIcebergReaderUnsafe                           ss    5  0.679 ± 0.011   s/op
SparkParquetReadersNestedDataBenchmark.readUsingSparkReader                                          ss    5  0.626 ± 0.059   s/op
SparkParquetReadersNestedDataBenchmark.readWithProjectionUsingIcebergReader              ss    5  0.286 ± 0.029   s/op
SparkParquetReadersNestedDataBenchmark.readWithProjectionUsingIcebergReaderUnsafe  ss    5  0.365 ± 0.036   s/op
SparkParquetReadersNestedDataBenchmark.readWithProjectionUsingSparkReader                 ss    5  0.333 ± 0.031   s/op
SparkParquetReadersFlatDataBenchmark.readUsingIcebergReader                                             ss    5  1.012 ± 0.051   s/op
SparkParquetReadersFlatDataBenchmark.readUsingIcebergReaderUnsafe                                 ss    5  1.223 ± 0.046   s/op
SparkParquetReadersFlatDataBenchmark.readUsingSparkReader                                                ss    5  1.128 ± 0.018   s/op
SparkParquetReadersFlatDataBenchmark.readWithProjectionUsingIcebergReader                    ss    5  0.582 ± 0.023   s/op
SparkParquetReadersFlatDataBenchmark.readWithProjectionUsingIcebergReaderUnsafe        ss    5  0.733 ± 0.013   s/op
SparkParquetReadersFlatDataBenchmark.readWithProjectionUsingSparkReader                       ss    5  0.648 ± 0.021   s/op
```

**Comment by ajantha-bhat** [comment]
image

**Comment by Fokko** [comment]
Thanks @ajantha-bhat for bumping Arrow and running the benchmarks.

**Pull request merged**
