### PR TITLE
[Build] Remove redundant spark-hive

### PR DESCRIPTION
**Pull request by pan3793**

### CODE REVIEW

**Comment by pan3793** [comment]
jcenter seems not stable

**Review by aokolnychyi — APPROVED** [review]

**Review by RussellSpitzer — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
Jceneter is shutting down, @rymurr has a PR #2339  to remove the reference and fix the build.

**Comment by pan3793** [comment]
Thanks @RussellSpitzer and @rymurr , once #2339 get merged, I will rebase this PR on master. And I see the latest PR CI passed, is that means JCenter is back to normal now?

**Comment by aokolnychyi** [comment]
I trigger the CI jobs again.

**Comment by aokolnychyi** [comment]
Thanks, @pan3793!

**Pull request merged**
