### PR TITLE
[python] Adding type ignores for dependencies without type support

### PR DESCRIPTION
**Pull request by TGooch44**
Adds mypy ignores for `pytz` and `dateutil`

### CODE REVIEW

**Comment by TGooch44** [comment]
@jun-he @rymurr I opened this PR to add some ignores on pytz and dateutil that are currently throwing linter errors on build.  Let me know if this looks ok, or if you'd prefer to handle it another way.

**Comment by rymurr** [comment]
Hey @TGooch44 any reason to not add `types-python-dateutil` and `types-pytz` to the test env dependencies?

**Comment by TGooch44** [comment]
Sure, my thinking was that since these both have pretty limited usage, I didn't want to add in more deps, but I guess not really a big deal to add in type stubs.

**Review by rymurr — APPROVED** [review]
I personally prefer deps over `# noqa` but im not so bothered.

**Comment by TGooch44** [comment]
> I personally prefer deps over `# noqa` but im not so bothered.

Given that these deps are only for mypy, I think you're right that it is better just to add them in over using ignores.

**Pull request merged**
