### PR TITLE
Rename hive subproject to hive-metastore

### PR DESCRIPTION
**Pull request by massdosage**
See https://lists.apache.org/thread.html/r32d74ad9674f5603884e933868006e13a465d744ce2fa249717742a2%40%3Cdev.iceberg.apache.org%3E for context.

### CODE REVIEW

**Comment by massdosage** [comment]
One question I have, do we want to repackage the Java classes in this module from `org.apache.iceberg.hive` to `org.apache.hive.metastore`? Or something else? Or just leave them?

**Comment by rdblue** [comment]
Thanks @massdosage! Looks great.

**Comment by massdosage** [comment]
@rdblue No problem, so you're happy with not repacking the Java classes?

**Comment by rdblue** [comment]
Yes. Moving the classes would be a breaking API change so I'd prefer to avoid it.

**Pull request merged**
