### PR TITLE
Spark-3.3: Support Zorder option for rewrite_data_files stored procedure

### PR DESCRIPTION
**Pull request by ajantha-bhat**
This is just a port of #4902 (from spark-3.2)

### CODE REVIEW

**Review by singhpk234 — APPROVED** [review]

**Comment by singhpk234** [comment]
should we also add this in Spark Procedures Doc

**Comment by singhpk234** [comment]
nvm I see it's already added in 3.2 pr :) !!!

**Comment by ajantha-bhat** [comment]
> nvm I see it's already added in 3.2 pr :) !!!

Yes, docs are already there and it is common for all the spark versions. Hence, not added again.

**Comment by RussellSpitzer** [comment]
Thanks @ajantha-bhat and @singhpk234 for double checking on the review!

**Pull request merged**
