### PR TITLE
End to end read support for int96 parquet timestamps

### PR DESCRIPTION
**Pull request by gustavoatt**
## Summary

Fixes https://github.com/apache/iceberg/issues/1138#issuecomment-670717050 by making sure that we can convert from `org.apache.parquet.schema.MessageType` to `org.apache.iceberg.types.Type`.

The issue was occurring due to Iceberg not being able to map the `int96` type to an Iceberg Timestamp. Also added an end to end test to verify that we can read through Iceberg API the imported parquet file.

While doing this, I noticed that the Iceberg generic parquet reader was reading the timestamp as timestamp without timezone instead of a timestamp with timezone.

## Testing

Improved our current unit-test to handle this issue

## Reviewers

to: @rdblue 
cc: @thesquelched @aokolnychyi

### CODE REVIEW

**Comment by rdblue** [comment]
+1 when tests are passing.

**Comment by rdblue** [comment]
Merged! Thanks @gustavoatt!

**Comment by gustavoatt** [comment]
Thanks for the fast review Ryan!

**Comment by thesquelched** [comment]
Thanks!

**Pull request merged**
