### PR TITLE
Spark 3.2: Fix names of methods that read all content files in actions

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR fixes the name of the method that reads both data and delete files but claims to read only data files.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @szehon-ho @RussellSpitzer @kbendick @rdblue @flyrain @karuppayya

**Review by RussellSpitzer — APPROVED** [review]

**Review by szehon-ho — APPROVED** [review]
Agree, looks good for internal refactor.  

Grepping for 'data file', there are some comments on top of "BaseDeleteOrphanFilesSparkAction" and "BaseExpireSnapshotsSparkAction" that still refer to 'data file' not sure if they need to change or it's ok as is.  In either case, this change LGTM

**Review by kbendick — APPROVED** [review]
LGTM if all changes are package private etc. This is more coherent. Thanks @aokolnychyi!

**Comment by flyrain** [comment]
Not directly related to this PR. The interface DataFile seems still a bit confusing since it can be a delete file. https://github.com/apache/iceberg/blob/69775c784cd441d225cdaa142a72c0d352b3223e/api/src/main/java/org/apache/iceberg/DataFile.java#L41.

**Comment by aokolnychyi** [comment]
Fixed Javadoc, @szehon-ho.

**Review by flyrain — APPROVED** [review]

**Comment by aokolnychyi** [comment]
Thanks for the reviews, everyone!

**Pull request merged**
