### PR TITLE
Flink: Bump to Flink 1.16.1

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Review by nastra — APPROVED** [review]

**Comment by stevenzwu** [comment]
@Fokko we typically don't need to bump flink version, because they are compile only. The flink-dist is provided by the runtime env (e.g. flink base image). even the `icegerg-flink-runtime` uber doesn't pull in any flink core runtime jars.

**Comment by Fokko** [comment]
@stevenzwu I agree that it isn't super important, however, it is good to check for any breaking changes. For example, 1.15.3 has a change in the public API that will cause issues in production: https://github.com/apache/iceberg/pull/7059

**Comment by stevenzwu** [comment]
>  it is good to check for any breaking changes.

This doesn't solve the problem. We are only saying that `iceberg-flink-1.16` can work with Flink 1.16 regardless of the patch version. But if Flink introduces a breaking change btw 1.16.0 and 1.16.1. it doesn't matter if we upgrade iceberg build to 1.16.1 or not. one way or another, it will break one patch version.

**Comment by Fokko** [comment]
> This doesn't solve the problem.

I agree

> there is nothing Iceberg can do to keep all patch versions happy.

Wouldn't it be better to keep the latest patch version happy?

**Comment by stevenzwu** [comment]
> Wouldn't it be better to keep the latest patch version happy?

I would agree that this is probably the lesser of the evil.

I would like to get a few other folks' input on this topic of whether we want to keep updating the Flink patch version to make sure Iceberg can work with latest patch version release if there is any breaking change.

cc @rdblue @hililiwei @pvary

**Comment by stevenzwu** [comment]
> Wouldn't it be better to keep the latest patch version happy?

I would agree that this is probably the lesser of the evil.

I would like to get a few other folks' input on this topic of whether we want to keep updating the Flink patch version to make sure Iceberg can work with latest patch version release if there is any breaking change.

cc @rdblue @hililiwei @pvary

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
I think it's a good idea to keep up with patch versions so that we know that our tests still pass and can report issues back. In the event a patch version is incompatible, I don't think we can choose to support the later patch version. We didn't break compatibility and we should not make changes that could potentially break people on the older versions. I also don't think it's worth the time to make sure everything is compatible.

**Comment by hililiwei** [comment]
Personally, I think it makes sense to skip incompatible patch versions. However, if we can achieve compatibility with little cost through the use of reflection and other means, then I would also vote for keeping backward compatibility. Of course, for major version, we shouldn't use this way.

**Comment by stevenzwu** [comment]
It seems that we have enough support to bump flink version even though it is a compile-only deps. that is enough for me.

thanks @Fokko

**Pull request merged**
