### PR TITLE
Spark 3.1: Remove module

### PR DESCRIPTION
**Pull request by aokolnychyi**

### CODE REVIEW

**Review by Fokko — COMMENTED** [review]
I think we can remove more:

- https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableProperties.java#L345-L356
- https://github.com/apache/iceberg/blob/master/docs/nessie.md?plain=1#L46
- https://github.com/apache/iceberg/blob/master/docs/spark-writes.md?plain=1#L186

**Comment by aokolnychyi** [comment]
Will fix the docs but let's keep table properties for now. I have recently discovered the cardinality check performance may not be that great, so we may need to add those properties back even for newer Spark versions.

**Review by Fokko — APPROVED** [review]

**Review by singhpk234 — APPROVED** [review]
LGTM as well, Thanks @aokolnychyi !

**Review by dramaticlly — APPROVED** [review]
thank you !

**Review by nastra — APPROVED** [review]

**Pull request closed without merging**
