### PR TITLE
Fixed non-greenway time zone, data loss with day partition

### LINKED ISSUE #1354: Non-greenway time zone, data loss with day partition
My Local time zone is Asia/Shanghai(CTT).
I create an iceberg table and use the `day()` function to use the timestamp column as the partition column.

The code to build the table and write the data is as follows:
```scala
  def createPartitionTable(catalog: HadoopCatalog, tableIdentifier: TableIdentifier): Unit = {
    val columns: List[Types.NestedField] = new ArrayList[Types.NestedField]
    columns.add(Types.NestedField.of(1, true, "id", Types.IntegerType.get, "id doc"))
    columns.add(Types.NestedField.of(2, true, "ts", Types.TimestampType.withZone(), "ts doc"))

    val schema: Schema = new Schema(columns)
    val partition = PartitionSpec.builderFor(schema).day("ts", "day").build()

    val table = catalog.createTable(tableIdentifier, schema, partition)
  }
  // CTT : Asia/Shanghai GMT+8
  // UTC : GMT+0
  def writeData(spark: SparkSession, TimeZoneId: String): Unit = {
    TimeZone.setDefault(TimeZone.getTimeZone(TimeZoneId))
    val seq = Seq(
      Tb(1, Timestamp.valueOf("2020-01-01 04:00:00")),
      Tb(2, Timestamp.valueOf("2020-01-01 11:00:00")))

    val df = spark.createDataFrame(seq).toDF("id", "ts")

    df.writeTo("prod.db.table").overwritePartitions()
  }
```

The test sample: When writing data using a non-Greenway time zone, a day's data is written to both partitions
```scala
    createPartitionTable(catalog, tableIdentifier)
    writeData(spark, "CTT")
```
The directory structure is as follows
```bash
➜  db tree ./table
./table
├── data
│   ├── day=2019-12-31
│   │   └── 00000-0-5a329b00-cbe5-4ea5-977e-9a609589d40a-00001.parquet
│   └── day=2020-01-01
│       └── 00000-0-5a329b00-cbe5-4ea5-977e-9a609589d40a-00002.parquet
└── metadata
    ├── b5299545-2ce0-49e1-b0f1-8bc87cb6562a-m0.avro
    ├── snap-2523494143240605377-1-b5299545-2ce0-49e1-b0f1-8bc87cb6562a.avro
    ├── v1.metadata.json
    ├── v2.metadata.json
    └── version-hint.text
```
This causes the `2019-12-31` data file to overwrite while writing the `2020-01-01` data.

I was wondering if we needed to fix the time zone issue that caused the data exception. This phenomenon also occurs in day/month/year partitions.

### PR DESCRIPTION
**Pull request by zhangdove**
Fix #1354 .

I have made some attempts to fix the data loss caused by the time zone, I don't know if it is feasible.

### CODE REVIEW

**Comment by rdblue** [comment]
@zhangdove, Iceberg does not modify timestamps other than converting between representations (like micros to millis).

Timestamp modification or adjustment to display a value by time zone is done by processing engines, not by Iceberg itself. Iceberg must only store values and return the same values.

Timestamp values are in microseconds and come in two flavors: timestamp is a zoneless date and time represented as microseconds from the Unix epoch in UTC, and timestamptz is an instant in time represented as microseconds from the Unix epoch in UTC.

The report in #1354 uses Spark. Spark only supports timestamptz and it passes values to Iceberg as microseconds from epoch, which Iceberg returns to Spark unmodified. The `day` partition function is not specific to a zone, which is probably the source of the confusion. The daily boundaries used by that function are UTC day boundaries, if I remember correctly.

**Comment by zhangdove** [comment]
@rdblue Thanks for your reply. And I still have some questions about time zones.

>Timestamp modification or adjustment to display a value by time zone is done by processing engines, not by Iceberg itself. Iceberg must only store values and return the same values.

1.I don't think that such an operation changes the value of the time, and Iceberg does not change the real data of the time type, but only changes the value of the time partition directory to meet the user's current time zone.

2.I don't understand why iceberg must use UTC time zone in the time partition directory. The user's time data in other time zones is prone to the problems described in #1354 .

**Comment by RussellSpitzer** [comment]
The real issue here is not that the "Day" has to be in UTC, but that timestamps are in many cases transmitted without any timezone information, assuming that we can add that information back based on the System locale is going to essentially be buggy especially when we don't know where the System's running the code are actually located and this may be different for multiple users of the same table.

One could imagine if you have a system running in both China and in US East you would get different answers with the same timestamps and this to me is the crux of the problem. System locale should not effect data partitioning.

This is one of the (many) reasons that almost all modern apis for calculating Day or Day since Epoch don't represent the underlying time as a timestamp. There is just too much ambiguity in what the "day" should actually be.

**Comment by rdblue** [comment]
> I don't think that such an operation changes the value of the time, and Iceberg does not change the real data of the time type, but only changes the value of the time partition directory to meet the user's current time zone.

Okay, I see that you're just adjusting the time zone in the partition function. That's similar to a solution we may want to use, although I think we would need to do it differently: the partition function must be well-defined and cannot depend on the environment. I think we would want to add either 23 new functions (one for each offset) or add an offset parameter to the function, similar to the bucket width and truncation length.

The reason why the partitioning is UTC is that we just need to break data up into day-sized partitions. The actual partition boundaries would ideally not matter. If you need data split across files at some boundary for deletes, then we would normally recommend hourly partitioning to ensure that you can delete any hour individually.

> I don't understand why iceberg must use UTC time zone in the time partition directory. The user's time data in other time zones is prone to the problems described in #1354 .

The requirement is that Iceberg must be consistent. Whatever one engine uses, all the others must as well. That's why I'm saying that the function would need to be parameterized and we would need to add the offsets to the spec.

Also, I should note that `dynamicOverwrite` is supported, but not considered a best practice. We don't recommend using `dynamicOverwrite` because it can lead to situations like what you hit in #1354. The problem is that the data being overwritten is _implicit_ based on the data written.

If your job had a bug and wrote a single record from another day -- even if the zone problem were fixed -- then that record would overwrite that day worth of data. This is why we added the `overwrite(Expression)` action in `DataFrameWriterV2`. That is explicit about what data is deleted when your job commits. That is a much more reliable pattern.

**Comment by zhangdove** [comment]
>One could imagine if you have a system running in both China and in US East you would get different answers with the same timestamps and this to me is the crux of the problem. System locale should not effect data partitioning.

@RussellSpitzer Thanks for your explanation, maybe I know why the community is using UTC time zone.

**Comment by zhangdove** [comment]
@rdblue Thank you very much for your patience.
After internal consideration of my team and I, we decided to privatize this function locally. At least so far, we have no internal problem of processing data across time zones. 
Of course, I am more looking forward to relevant modifications by the community, as you mentioned before, adding an offset parameter in the function. If you don't mind, maybe I'll take the time to provide a PR that supports the time zone parameter function.

The reason why I use 'dynamicOverwrite' is because of the problem from #1341 . However, when I want to reproduce the problem, I find that the problem no longer exists. Next, I'll use the recommended API `(overwrite(Expression))`.

**Comment by zhangdove** [comment]
I am now closing the relevant issue and this PR

**Comment by RussellSpitzer** [comment]
Timezones are the worst :(

**Comment by rdblue** [comment]
@zhangdove, thanks for bringing this up, I think it is a valuable discussion to have. I'm definitely open to adding date functions that are parameterized by a zone offset because there are times when the partition boundaries matter. If you're interested in that, it would be great to have you contribute them!

**Pull request closed without merging**
