### PR TITLE
SparkBatchQueryScan logs too much - #6106

### PR DESCRIPTION
**Pull request by Omega359**
Updating log in this class as per suggestion

### CODE REVIEW

**Review by hililiwei — APPROVED** [review]

**Review by nastra — APPROVED** [review]

**Comment by nastra** [comment]
fixes #6106

**Comment by rdblue** [comment]
Running CI. The changes look good to me.

**Comment by nastra** [comment]
@Omega359 could you please fix the missing import so that the code compiles? Would be great to get this merged

**Comment by rdblue** [comment]
Running CI again.

**Comment by rdblue** [comment]
Thanks, @Omega359!

**Pull request merged**
