### PR TITLE
SPEC - Move REST catalog OpenAPI spec to new docs/rest folder

### PR DESCRIPTION
**Pull request by kbendick**
Right now, any PR that touches the OpenAPI spec for the REST catalog will trigger all CI workflows.

Given that we operate off of a limited number of hosted runners for Github Actions, and that none of these workflows are exercising anything to do with the doc currently, they should be ignored.

In the future, when we have a validation step on the OpenAPI doc, these ignores will still apply (though any that don't can be updated).

### CODE REVIEW

**Comment by kbendick** [comment]
cc @jackye1995 @nastra @RussellSpitzer @samredai 

We eventually probably want to find a better spot for this, but given how limited our capacity to run CI is, having this file trigger CI is a waste of resources.

**Comment by samredai** [comment]
lgtm. A `documentation` root folder will be added when PR #4062 is merged. Maybe this could eventually be moved to `documentation/rest`.

**Review by nastra — APPROVED** [review]

**Review by jackye1995 — APPROVED** [review]
`documentation/rest` sounds good to me. I also need to update these CI workflows for the doc PR, let me do it.

**Comment by jackye1995** [comment]
@samredai @kbendick if we agree that `documentation/rest` is the right place for this, should we just not have this change and directly move it there?

**Comment by rdblue** [comment]
`documentation` or `docs`?

**Comment by samredai** [comment]
> documentation or docs?

The PR currently is using `documentation` for the folder name but I'm ok with `docs` too. @jackye1995 do you want to update that in your PR?

As for merging this PR or moving the change to the other PR, I don't have an opinion either way. Although merging this and then rebasing the other PR might make it slightly easier since all you'll have to do then is `mkdir docs/rest && cp rest_docs/rest_docs/rest-catalog-open-api.yaml docs/rest/rest-catalog-open-api.yaml` without editing the file.

**Comment by kbendick** [comment]
Ah cool I wasn't aware (at the time) that we were updatingg to add the docs. I'll move to `docs/rest/rest-catalog-open-api.yaml` 👍

**Comment by jackye1995** [comment]
`docs` also work for me, don't have strong opinion about folder name. Updating...

**Comment by kbendick** [comment]
I updated this to move the OpenAPI spec to `docs/rest` instead. I'll wait until PR https://github.com/apache/iceberg/pull/4062 is merged and rebase again if needed.

**Comment by jackye1995** [comment]
@kbendick thanks, I've merged 4062!

**Review by jackye1995 — APPROVED** [review]

**Comment by kbendick** [comment]
> @kbendick thanks, I've merged 4062!

Thank you! I updated this one to use `docs/rest` and rebased. Once the tests pass it should be good to merge.

**Pull request merged**
