### PR TITLE
Flink 1.15/1.16: Key projection should be based on the requested Flink table schema

### PR DESCRIPTION
**Pull request by ConeyLiu**
This ports #7836 to Flink 1.15/1.16.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
cc @stevenzwu please help to review when you are free. Thanks a lot.

**Comment by pvary** [comment]
@ConeyLiu: was this a clean backport, or did you need any extra changes?

**Comment by stevenzwu** [comment]
please verify no diff related to this change. e.g.

```
git diff --no-index  flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle  flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle
```

**Comment by stevenzwu** [comment]
please verify no diff related to this change. e.g.

```
git diff --no-index  flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle  flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle
```

**Comment by ConeyLiu** [comment]
@pvary @stevenzwu, I have verified the following, and there are no other changes.
```
git diff --no-index flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/ flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/
git diff --no-index flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/ flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/ 

git diff --no-index flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/ flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/
git diff --no-index flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/ flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/ 
```

**Review by stevenzwu — APPROVED** [review]

**Comment by ConeyLiu** [comment]
Thanks @stevenzwu @pvary

**Pull request merged**
