### PR TITLE
Doc:Example of correcting the document add/drop partition truncate

### PR DESCRIPTION
**Pull request by jiamin13579**
Example of correcting the document add/drop partition truncate

### CODE REVIEW

**Comment by szehon-ho** [comment]
Not sure its necessary, looks like for now width can be any of the arguments:  https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java#L428

**Comment by jiamin13579** [comment]
> Not sure its necessary, looks like for now width can be any of the arguments: https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java#L428

I think the document will mislead users,Many partitions will be generated.

**Comment by szehon-ho** [comment]
I may be missing something but don't both truncate(data, 4) and truncate(4,data) do the same thing ?

**Comment by rdblue** [comment]
@szehon-ho, you're right that Iceberg accepts both. But in Spark, the correct one is to put the width first because that's how Spark validates the function call.

**Comment by rdblue** [comment]
Thanks, @jiamin13579!

**Comment by szehon-ho** [comment]
Hm I was trying both commands in Spark 3.2 and they did the same thing for me.  Not sure if there's any changes since then.  Anyway if thats the official way , fine with me.

**Pull request merged**
