### PR TITLE
Hive: make sure to unlock table when the finally block is not executed

### PR DESCRIPTION
**Pull request by smallx**
Avoid that the `finally` code block used to unlock hive table may not be executed due to the following conditions:
- `System.exit(N)`
- all non-daemon threads exit

### CODE REVIEW

**Comment by smallx** [comment]
Please help me to run github workflows, thanks.

**Comment by kbendick** [comment]
Can this be done using a `try-with-resources` block instead?

**Comment by smallx** [comment]
thanks @kbendick 

`try-with-resources` is just a syntactic sugar. `try-with-resources` block and `try-finally` block are the same at the bytecode level. These code block may not end normally if the thread that executing these code is terminated.

Refer the java document: https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html

**Comment by coolderli** [comment]
Does this solve the same problem as #2785?

**Comment by smallx** [comment]
> Does this solve the same problem as #2785?

Oh, I haven't found #2785 before. It's similar to my problem, but not the same.

**Comment by pvary** [comment]
@smallx: Seems that the test were timeouted after 360m. Could you please check if this was caused your PR?

Thanks,
Peter

**Comment by smallx** [comment]
close this, i will create a new pr

**Pull request closed without merging**
