### PR TITLE
Spark 3.1: Make SparkCatalog#alterTable conform to TableCatalog interface

### PR DESCRIPTION
**Pull request by wypoon**
Port of #3548 to 3.1.
Fix is due to Xinbin Huang (@xinbinhuang).

### CODE REVIEW

**Comment by wypoon** [comment]
The fix is applicable to Spark 3.1 as well (`TableCatalog#alterTable is supposed to return the updated metadata).
@RussellSpitzer can you please review? You merged #3548.

**Comment by wypoon** [comment]
cc @kbendick

**Comment by wypoon** [comment]
Added @xinbinhuang as co-author.

**Review by kbendick — APPROVED** [review]
Thanks for porting this!

**Review by rdblue — APPROVED** [review]

**Pull request merged**
