### PR TITLE
Core: Handle metrics-based deletes

### PR DESCRIPTION
**Pull request by aokolnychyi**
This PR adds support for deleting some files within a partition based on file stats.

### CODE REVIEW

**Comment by aokolnychyi** [comment]
cc @jackye1995 @rdblue @RussellSpitzer @flyrain @karuppayya @szehon-ho

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
The test failure is strange:

```
org.apache.iceberg.TestRowDelta > testOverwriteWithDeleteFile FAILED
    org.apache.iceberg.exceptions.ValidationException: Visitor org.apache.iceberg.expressions.InclusiveMetricsEvaluator$MetricsEvalVisitor@540cbff4 does not support expression: bucket[16](ref(id=2, accessor-type=string))
        at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:46)
        at org.apache.iceberg.expressions.ExpressionVisitors$BoundExpressionVisitor.predicate(ExpressionVisitors.java:124)
        at org.apache.iceberg.expressions.ExpressionVisitors.visitEvaluator(ExpressionVisitors.java:346)
        at org.apache.iceberg.expressions.InclusiveMetricsEvaluator$MetricsEvalVisitor.eval(InclusiveMetricsEvaluator.java:107)
        at org.apache.iceberg.expressions.InclusiveMetricsEvaluator$MetricsEvalVisitor.access$100(InclusiveMetricsEvaluator.java:82)
        at org.apache.iceberg.expressions.InclusiveMetricsEvaluator.eval(InclusiveMetricsEvaluator.java:76)
        at org.apache.iceberg.ManifestFilterManager$MetricsEvaluator.rowsMightMatch(ManifestFilterManager.java:452)
        at org.apache.iceberg.ManifestFilterManager.manifestHasDeletedFiles(ManifestFilterManager.java:353)
        at org.apache.iceberg.ManifestFilterManager.filterManifest(ManifestFilterManager.java:296)
        at org.apache.iceberg.ManifestFilterManager.lambda$filterManifests$0(ManifestFilterManager.java:183)
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:405)
        at org.apache.iceberg.util.Tasks$Builder.access$300(Tasks.java:71)
        at org.apache.iceberg.util.Tasks$Builder$1.run(Tasks.java:311)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Looks like the visitor is operating on a bound expression, but the term is unbound somehow.

**Comment by rdblue** [comment]
@aokolnychyi, I opened https://github.com/aokolnychyi/incubator-iceberg/pull/4 to fix this.

The problem is that the metrics eval visitors don't handle non-reference terms (i.e. transforms) in expressions. The fix was to allow them to return a default decision, like `ROWS_MIGHT_MATCH` when they encounter a non-reference term.

**Review by jackye1995 — APPROVED** [review]
looks good to me

**Comment by aokolnychyi** [comment]
I've submitted an alternative solution in #3600 as this one did not cover all use cases. Let me know if I am overthinking it too.

**Comment by aokolnychyi** [comment]
Closing this one in favor of #3600.

**Pull request closed without merging**
