### PR TITLE
Spark3.1: Backport #3728 (Binary/Fixed literals) / #3983 (Zorder strategy) to Spark3.1

### PR DESCRIPTION
**Pull request by xloya**
Port zorder strategy (https://github.com/apache/iceberg/pull/3983) and generate binary/fixed literals (https://github.com/apache/iceberg/pull/3728) to Spark 3.1, the reason for the merged port is that Zorder's tests rely on the fix in patch #3728

### CODE REVIEW

**Comment by xloya** [comment]
cc @RussellSpitzer @rdblue @xiaotianzhang01 @kbendick

**Comment by rdblue** [comment]
@xloya, can you separate backports into individual PRs, please?

**Comment by xloya** [comment]
> @xloya, can you separate backports into individual PRs, please?

Sure, but the unit tests of the patch of #3983 (Zorder strategy) would not pass until the patch of #3728 (Generate Binary/Fixed literals) is merged. When #3728 is merged, I will rebase to the backport patch of #3983

**Comment by xloya** [comment]
@rdblue Already seperate them to #5847 and #5848, please review again when you have time, thx!

**Comment by ajantha-bhat** [comment]
Closing this PR as spark-3.1 module is removed from master code.

**Pull request closed without merging**
