### PR TITLE
Python: Small fixes

### PR DESCRIPTION
**Pull request by Fokko**
Uncovered these when upgrading to Pydantic 2.0

### CODE REVIEW

**Review by JonasJ-ap — APPROVED** [review]
LGTM! @Fokko Thanks for your great work!

One minor non-blocking suggestion: I think it would be great to update `snapshot_id` parameter in these tests to use int type, to reflect the improvements made in the PR.
https://github.com/apache/iceberg/blob/1f1ec4be478feae79b04bcea3e9a8556d8076054/python/tests/table/test_init.py#L185-L189

https://github.com/apache/iceberg/blob/1f1ec4be478feae79b04bcea3e9a8556d8076054/python/tests/catalog/test_hive.py#L353-L356

**Comment by Fokko** [comment]
@JonasJ-ap Great catch!

**Comment by GadiZimerman** [comment]
@CodiumAI-Agent

**Review by nastra — APPROVED** [review]
LGTM, thanks @Fokko. And thanks @JonasJ-ap for reviewing

**Pull request merged**
