### PR TITLE
Update flink-getting-started.md

### PR DESCRIPTION
**Pull request by 911432**
I fixed a typo.

### CODE REVIEW

**Comment by Fokko** [comment]
@911432 We had a reorganization in https://github.com/apache/iceberg/pull/7099, could you rebase your PR? Fixed to the docs are very welcomed.

**Comment by 911432** [comment]
I have done rebase about https://github.com/apache/iceberg/pull/7214 and https://github.com/apache/iceberg/pull/7215

**Comment by 911432** [comment]
@Fokko I have done rebase about https://github.com/apache/iceberg/pull/7214 and https://github.com/apache/iceberg/pull/7215

**Comment by 911432** [comment]
@Fokko I have done rebase about https://github.com/apache/iceberg/pull/7245 and https://github.com/apache/iceberg/pull/7215

**Pull request closed without merging**
