### PR TITLE
Spark-3.0: support CALL procedure for rewrite_data_files

### PR DESCRIPTION
**Pull request by ajantha-bhat**
This is a back sync of #3375 and its dependent #3675 to spark-3.0 folder

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
CI failed because of [this](https://github.com/apache/iceberg/issues/1144) problem 
I will update my testcase

**Comment by ajantha-bhat** [comment]
cc: @kbendick , @RussellSpitzer , @rdblue

**Comment by ajantha-bhat** [comment]
@jackye1995 : could you please add 0.13.0 milestone for this PR ?

**Review by jackye1995 — APPROVED** [review]
looks good to me

**Review by RussellSpitzer — APPROVED** [review]
Looks identical to Spark-3.1 PR. So I think we are good to go here

**Pull request merged**
