### PR TITLE
Core: Clear unused functions of HadoopTables

### PR DESCRIPTION
**Pull request by southernriver**
Clear unused functions of HadoopTables .

### CODE REVIEW

**Comment by CodingCat** [comment]
since this was exposed as public APIs, how we assume no users use these stuffs?

**Comment by southernriver** [comment]
> since this was exposed as public APIs, how we assume no users use these stuffs?

I thought there is no need to expose two identical duplicated functions, and keep one of them is ok.  

```
default Transaction newReplaceTableTransaction(
      TableIdentifier identifier,
      Schema schema,
      PartitionSpec spec,
      String location,
      Map<String, String> properties,
      boolean orCreate) 
```

**Comment by CodingCat** [comment]
well, it is not about needed or not, but more about how we manage breaking changes

**Comment by rdblue** [comment]
These are public, so I don't think we should remove them.

**Pull request closed without merging**
