### PR TITLE
Spark: Add actions for disaster recovery.

### PR DESCRIPTION
**Pull request by flyrain**
Multiple people asked me to share the tool to rewrite the metadata files when moving tables from one location to another. Here you are. Three Spark actions are added. 
1. Action copy-table is for the source tables to rewrite metadata files
2. Action checkSnapshotIntegrity and action removeExpiredFiles are for the target tables to apply changes, integrity check, and cleanup.

### CODE REVIEW

**Comment by rdblue** [comment]
@flyrain, can you open these in separate PRs? They seem like different features to me.

**Comment by flyrain** [comment]
@rdblue, filed this mainly for sharing. I will close this first, and we can always file separated new PRs if we want to merge this into master.

**Comment by laithalzyoud** [comment]
Hello @flyrain @rdblue , are there any plans to file separate PRs and merge into master? We are already using these changes in a [forked version](https://github.com/revolut-engineering/revolut-iceberg/tree/1.4.x) of Iceberg and did some changes to make it work with 1.4.x and Spark 3.3. We want to get these changes merged to avoid updating the forked version on every Iceberg release. I can also help to push this through if needed!

**Comment by flyrain** [comment]
Hi @laithalzyoud, glad you found this useful. Would you like to take the lead for this task? I could be the co-author if that makes sense to you. I can help on the review, but we will still need at least one more committer other than me to review and approve, since I'm going to be the co-author. cc @rdblue @RussellSpitzer @aokolnychyi @szehon-ho

**Comment by szehon-ho** [comment]
+1 on adding it, I also think its useful , but was not there for the initial reason why it was not added originally.

**Comment by laithalzyoud** [comment]
@flyrain Yes I would be glad to take lead along with you as co-author. I will dedicate some time next week and start working on this 👍

**Comment by amogh-jahagirdar** [comment]
@flyrain @laithalzyoud I'm also happy to help with reviews on these PRs!

**Pull request closed without merging**
